"""COBOL generator — minimal deterministic mainframe-style legacy.

Produces .cob files representing legacy batch programs that read VSAM
datasets, write sequential files, and embed hardcoded connection info
in static DATA DIVISION sections. Analyzers detect these as legacy
patterns requiring wrapping (strangler pattern) rather than line-level
fixes.

Kept intentionally template-based — COBOL semantics are complex and the
refactor engine treats Cobol modules as opaque "wrap me" units anyway.
"""
from __future__ import annotations

import random
from dataclasses import dataclass
from pathlib import Path

from ..profile import AppRecipe


COBOL_PROGRAM = """       IDENTIFICATION DIVISION.
       PROGRAM-ID. {prog}.
       AUTHOR. LEGACY-BATCH.
       DATE-WRITTEN. 2012-03-15.
      *
      * Generated synthetic legacy module — {prog}
      * NexusForge showcase: wrap, do not rewrite.
      *
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT IN-FILE ASSIGN TO 'INPUT.DAT'
               ORGANIZATION IS SEQUENTIAL.
           SELECT OUT-FILE ASSIGN TO 'OUTPUT.DAT'
               ORGANIZATION IS SEQUENTIAL.
           SELECT VSAM-MASTER ASSIGN TO 'MASTER.VSAM'
               ORGANIZATION IS INDEXED
               ACCESS MODE IS RANDOM
               RECORD KEY IS REC-KEY.
      *
       DATA DIVISION.
       FILE SECTION.
       FD  IN-FILE.
       01  IN-RECORD           PIC X(200).
       FD  OUT-FILE.
       01  OUT-RECORD          PIC X(200).
       FD  VSAM-MASTER.
       01  MASTER-RECORD.
           05  REC-KEY         PIC X(10).
           05  REC-DATA        PIC X(190).
      *
       WORKING-STORAGE SECTION.
       01  WS-DB-CONN          PIC X(60)
           VALUE 'DSN=LEGACYDB;UID=SA;PWD=synth-fake-cobol-{n}'.
       01  WS-API-KEY          PIC X(40)
           VALUE 'synth-fake-cobol-api-key-{n}'.
       01  WS-EOF              PIC X VALUE 'N'.
      *
       PROCEDURE DIVISION.
       MAIN-LOGIC.
           OPEN INPUT IN-FILE.
           OPEN OUTPUT OUT-FILE.
           OPEN I-O VSAM-MASTER.
      *
           PERFORM READ-LOOP UNTIL WS-EOF = 'Y'.
      *
           CLOSE IN-FILE.
           CLOSE OUT-FILE.
           CLOSE VSAM-MASTER.
           STOP RUN.
      *
       READ-LOOP.
           READ IN-FILE
               AT END MOVE 'Y' TO WS-EOF
               NOT AT END
                   MOVE IN-RECORD TO OUT-RECORD
                   WRITE OUT-RECORD
                   MOVE IN-RECORD(1:10) TO REC-KEY
                   WRITE MASTER-RECORD
           END-READ.
      *
       END PROGRAM {prog}.
"""


JCL_TEMPLATE = """//{prog}JOB JOB (ACCT),'LEGACY BATCH',
//             CLASS=A,MSGCLASS=H
//STEP1    EXEC PGM={prog}
//INFILE   DD DSN=LEGACY.INPUT.DAT,DISP=SHR
//OUTFILE  DD DSN=LEGACY.OUTPUT.DAT,DISP=(NEW,CATLG,DELETE)
//MASTER   DD DSN=LEGACY.MASTER.VSAM,DISP=SHR
//SYSOUT   DD SYSOUT=*
"""


@dataclass
class CobolGenerator:
    app: AppRecipe
    rng: random.Random
    module_count: int = 4  # small by default; Cobol programs are rarely many

    def generate(self, out_dir: Path) -> list[Path]:
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "cobol").mkdir(exist_ok=True)
        (out_dir / "jcl").mkdir(exist_ok=True)

        created: list[Path] = []
        for i in range(self.module_count):
            prog = f"LGC{i:04d}"
            cob_path = out_dir / "cobol" / f"{prog}.cob"
            cob_path.write_text(
                COBOL_PROGRAM.format(prog=prog, n=self.rng.randint(1000, 9999)),
                encoding="utf-8",
            )
            created.append(cob_path)

            jcl_path = out_dir / "jcl" / f"{prog}.jcl"
            jcl_path.write_text(JCL_TEMPLATE.format(prog=prog), encoding="utf-8")
            created.append(jcl_path)

        # Schedule note — human-readable batch schedule file that the
        # refactor engine uses as a hint that this is a scheduled batch.
        schedule = out_dir / "cobol" / "SCHEDULE.md"
        schedule.write_text(
            "# Legacy batch schedule\n\n"
            "- 02:00 UTC: LGC0000 — nightly reconciliation\n"
            "- 06:00 UTC: LGC0001 — morning close\n"
            "- 14:00 UTC: LGC0002 — midday recalc\n"
            "- 22:00 UTC: LGC0003 — end-of-day posting\n\n"
            "Generated by synth — no real schedule.\n",
            encoding="utf-8",
        )
        created.append(schedule)

        return created
