"""CI/CD Pipeline Generator — auto-generate GitHub Actions for .NET and Python projects.

Generates:
  - Build + test pipeline
  - Security scan (bandit for Python, security-scan for .NET)
  - Deploy to AWS (EC2 or ECS Fargate)
  - Environment-specific configs (dev/staging/prod)

Tailored for legacy enterprise apps:
  - .NET Framework → windows-latest runner
  - .NET Core → ubuntu-latest runner
  - Python → ubuntu-latest runner
  - Multi-DB test matrix (SQL Server, MySQL, DB2)
"""

import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def generate_dotnet_pipeline(
    project_name: str,
    framework: str = "net6.0",
    test_project: str = "",
    db_engine: str = "sqlserver",
    deploy_target: str = "ec2",
) -> str:
    """Generate GitHub Actions workflow for .NET project."""

    is_framework = framework.startswith("net4") or framework.startswith("net3")
    runner = "windows-latest" if is_framework else "ubuntu-latest"
    dotnet_version = "6.0.x" if "net6" in framework else "8.0.x"

    db_service = ""
    if db_engine == "sqlserver":
        db_service = """
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: TestPassword123!
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P TestPassword123! -Q 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5"""
    elif db_engine == "mysql":
        db_service = """
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: TestPassword123!
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5"""

    test_step = ""
    if test_project:
        test_step = f"""
    - name: Run tests
      run: dotnet test {test_project} --no-build --verbosity normal --logger trx
      env:
        ConnectionStrings__Default: "Server=localhost;Database=testdb;User=sa;Password=TestPassword123!"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: "**/*.trx"
"""

    deploy_step = ""
    if deploy_target == "ec2":
        deploy_step = """
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: publish-output

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /app && ./deploy.sh
"""
    elif deploy_target == "fargate":
        deploy_step = """
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPO }}:${{ github.sha }} .
        docker push ${{ secrets.ECR_REPO }}:${{ github.sha }}

    - name: Update ECS service
      run: |
        aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER }} --service ${{ secrets.ECS_SERVICE }} --force-new-deployment
"""

    return f"""# Generated by NexusForge AI — CI/CD for {project_name}
name: {project_name} CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: {runner}
{db_service}
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '{dotnet_version}'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
{test_step}
    - name: Security scan
      run: dotnet list package --vulnerable --include-transitive 2>&1 | tee security-report.txt

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: publish-output
        path: ./publish
{deploy_step}"""


def generate_python_pipeline(
    project_name: str,
    test_framework: str = "pytest",
    deploy_target: str = "ec2",
) -> str:
    """Generate GitHub Actions workflow for Python project."""

    deploy_step = ""
    if deploy_target == "ec2":
        deploy_step = """
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /app && git pull && pip install -r requirements.txt && supervisorctl restart app
"""

    return f"""# Generated by NexusForge AI — CI/CD for {project_name}
name: {project_name} CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Lint
      run: |
        pip install ruff
        ruff check .

    - name: Security scan
      run: |
        pip install bandit
        bandit -r . -f json -o bandit-report.json || true

    - name: Run tests
      run: {test_framework} --tb=short -q

    - name: Upload security report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-report
        path: bandit-report.json
{deploy_step}"""


def generate_xunit_test_class(
    class_name: str,
    methods: list[dict],
    namespace: str = "",
    using_statements: list[str] | None = None,
) -> str:
    """Generate xUnit test class for a C# class."""
    usings = using_statements or ["System", "Xunit", "Moq"]
    using_block = "\n".join(f"using {u};" for u in usings)

    ns_open = f"\nnamespace {namespace}.Tests\n{{" if namespace else ""
    ns_close = "\n}" if namespace else ""

    tests = []
    for method in methods:
        name = method["name"]
        return_type = method.get("return_type", "void")
        param_count = method.get("params", 0)

        # Test: method returns expected result
        tests.append(f"""
    [Fact]
    public void {name}_ShouldReturnExpectedResult()
    {{
        // Arrange
        // var sut = new {class_name}();

        // Act
        // var result = sut.{name}();

        // Assert
        // Assert.NotNull(result);
        Assert.True(true); // TODO: implement real assertion
    }}""")

        # Test: handles null input
        if param_count > 0:
            tests.append(f"""
    [Fact]
    public void {name}_WithNullInput_ShouldHandleGracefully()
    {{
        // Arrange
        // var sut = new {class_name}();

        // Act & Assert
        // Assert.Throws<ArgumentNullException>(() => sut.{name}(null));
        Assert.True(true); // TODO: implement
    }}""")

    test_methods = "\n".join(tests)

    return f"""// Auto-generated tests by NexusForge AI
// Target: {class_name}
{using_block}
{ns_open}
public class {class_name}Tests
{{
    // TODO: Wire up dependency injection / mocks
    // private readonly {class_name} _sut;
    // public {class_name}Tests() {{ _sut = new {class_name}(); }}
{test_methods}
}}{ns_close}
"""


class CICDGenerator:
    """Generate CI/CD pipelines and test files for a project."""

    def __init__(self, project_root: str, dry_run: bool = False):
        self.root = Path(project_root)
        self.dry_run = dry_run

    def generate_for_project(self, project: "CSharpProject") -> dict:
        """Generate CI/CD + tests for a C# project."""
        results = {"pipelines": [], "test_files": []}

        # Generate GitHub Actions pipeline
        pipeline = generate_dotnet_pipeline(
            project_name=project.name,
            framework=project.framework,
            db_engine=self._detect_db(project),
        )

        pipeline_path = self.root / ".github" / "workflows" / f"{project.name}-ci.yml"
        if not self.dry_run:
            pipeline_path.parent.mkdir(parents=True, exist_ok=True)
            pipeline_path.write_text(pipeline, encoding="utf-8")
        results["pipelines"].append(str(pipeline_path.relative_to(self.root)))

        # Generate xUnit tests for each class
        for cls in project.classes:
            if not cls.methods or cls.name.endswith("Tests"):
                continue

            test_content = generate_xunit_test_class(
                class_name=cls.name,
                methods=cls.methods,
                namespace=cls.namespace,
            )

            test_path = self.root / project.path / "Tests" / f"{cls.name}Tests.cs"
            if not self.dry_run:
                test_path.parent.mkdir(parents=True, exist_ok=True)
                test_path.write_text(test_content, encoding="utf-8")
            results["test_files"].append({
                "class": cls.name,
                "path": str(test_path.relative_to(self.root)),
                "methods_tested": len(cls.methods),
            })

        return results

    def _detect_db(self, project) -> str:
        deps = " ".join(project.dependencies).lower()
        if "sqlclient" in deps or "sqlserver" in deps:
            return "sqlserver"
        if "mysql" in deps or "pomelo" in deps:
            return "mysql"
        return "sqlserver"  # Default for .NET apps
