"""COBOL wrapper generator (Gap 2 from the vision doc).

Takes a ``CobolScanReport`` and produces a Python/FastAPI wrapper
project that exposes each COBOL program as a REST endpoint. The
wrapper does not touch the COBOL source — it shells out to the
existing JCL via ``subprocess``, parses the output file, and returns
a structured JSON response.

This is the realization of the strangler-pattern "wrap, do not
rewrite" rule for mainframe components. Stakeholders can move
traffic to the wrapper behind an API gateway, retire the wrapper
one program at a time, and only rewrite the COBOL modules whose
business case justifies it.

Generated project shape:

    out_dir/
    ├── README.md               # how to run, environment, contract map
    ├── requirements.txt        # fastapi + uvicorn + pydantic
    ├── main.py                 # FastAPI app with one route per program
    ├── models.py               # Pydantic request/response models
    └── invokers/
        └── <program>.py        # one file per COBOL program with the
                                  # subprocess invocation + response parser
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

from .cobol_scanner import CobolProgram, CobolScanReport

logger = logging.getLogger(__name__)


@dataclass
class GeneratedWrapper:
    out_dir: str
    files_written: list[str] = field(default_factory=list)
    program_count: int = 0
    endpoint_count: int = 0

    def to_dict(self) -> dict:
        return {
            "out_dir": self.out_dir,
            "files_written": self.files_written,
            "program_count": self.program_count,
            "endpoint_count": self.endpoint_count,
        }


_README = """# COBOL Wrapper — auto-generated

This directory holds a FastAPI wrapper around {program_count} legacy
COBOL program(s). Each program is exposed as a REST endpoint that
shells out to the existing JCL and returns a structured response.
The COBOL source code is **not** modified — this is a strangler-
pattern wrap, not a rewrite.

## How to run

```bash
pip install -r requirements.txt
uvicorn main:app --reload --port 8080
```

## Environment contract

Each invocation expects the following environment variables to be
set by the caller (or defaulted in a deployment config):

- `COBOL_BIN_DIR`   — directory containing the compiled COBOL load modules
- `JCL_DIR`         — directory containing the .jcl job definitions
- `DATA_IN_DIR`     — working directory for input datasets
- `DATA_OUT_DIR`    — working directory for output datasets
- `JOB_TIMEOUT_SEC` — how long to wait for the JCL step before giving up

## Endpoints

{endpoints_list}

## Security note

The scanner found hardcoded credentials in the original COBOL
WORKING-STORAGE sections. This wrapper does NOT read those credentials
— it is the caller's job to push them into the environment via a
secrets manager, and to remove the hardcoded values when the next
COBOL recompile lands.

_Auto-generated by NexusForge. Not real client data._
"""

_REQUIREMENTS = """fastapi>=0.110
uvicorn[standard]>=0.29
pydantic>=2.0
"""

_MAIN_HEADER = '''"""Auto-generated FastAPI wrapper for legacy COBOL programs.

One route per PROGRAM-ID. Each route dispatches to the corresponding
invoker under ``invokers/`` which runs the JCL via subprocess and
parses the output file. The wrapper is intentionally thin so it can
be swapped out one program at a time as the modernization program
progresses.
"""
from __future__ import annotations

from fastapi import FastAPI, HTTPException

'''

_MAIN_APP_INIT = '''app = FastAPI(
    title="COBOL Wrapper",
    description="Strangler-pattern wrapper around legacy COBOL programs.",
    version="0.1.0",
)


@app.get("/health")
async def health() -> dict:
    return {"status": "ok", "programs": {programs!r}}


'''

_MAIN_ROUTE_TEMPLATE = '''@app.post("/v1/{route}", response_model=models.{model_out})
async def call_{slug}(request: models.{model_in}) -> models.{model_out}:
    """Invoke the legacy `{program_id}` program via its JCL.

    Input: {inputs}
    Output file: `{output_file}`
    """
    try:
        return await invokers.{module}.run(request)
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"legacy invocation failed: {{exc}}")


'''

_MODELS_HEADER = '''"""Pydantic request/response models for the COBOL wrapper.

All models are generated from the scanner's FILE-CONTROL output.
Extend them in a companion file if you need richer validation — do
not hand-edit this file.
"""
from __future__ import annotations

from pydantic import BaseModel, Field

'''

_MODEL_TEMPLATE = '''class {name_in}(BaseModel):
    """Input payload for `{program_id}`.

    Populates the datasets the COBOL program reads from its FILE
    SECTION. The wrapper writes each field to the corresponding
    physical dataset before shelling out to the JCL.
    """
    payload: dict = Field(
        default_factory=dict,
        description="Key-value map of logical-name to serialized record body.",
    )


class {name_out}(BaseModel):
    """Response payload from `{program_id}`.

    Parsed from the program's output dataset(s). Each element of
    ``records`` is one fixed-width line from the output file.
    """
    records: list[dict] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    duration_ms: int = 0


'''

_INVOKER_TEMPLATE = '''"""Invoker for legacy program `{program_id}`.

Runs the JCL via subprocess, captures stdout/stderr, parses the
output dataset and returns a {name_out}.
"""
from __future__ import annotations

import asyncio
import os
import time
from pathlib import Path

from .. import models

JCL_DIR = os.environ.get("JCL_DIR", "./jcl")
DATA_IN_DIR = os.environ.get("DATA_IN_DIR", "./data/in")
DATA_OUT_DIR = os.environ.get("DATA_OUT_DIR", "./data/out")
JOB_TIMEOUT_SEC = int(os.environ.get("JOB_TIMEOUT_SEC", "300"))

PROGRAM_ID = "{program_id}"
JCL_FILE = "{jcl_file}"
INPUT_BINDINGS = {input_bindings}
OUTPUT_BINDINGS = {output_bindings}


async def run(request: models.{name_in}) -> models.{name_out}:
    """Write inputs, shell out to the JCL, and parse the output file."""
    start = time.monotonic()
    in_dir = Path(DATA_IN_DIR)
    out_dir = Path(DATA_OUT_DIR)
    in_dir.mkdir(parents=True, exist_ok=True)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Stage inputs from the request payload
    for logical, physical in INPUT_BINDINGS.items():
        body = request.payload.get(logical, "")
        (in_dir / physical).write_text(body, encoding="utf-8")

    # Run the JCL. In real deployments this would dispatch to a job
    # scheduler; here we run a placeholder that demonstrates the
    # subprocess contract. Replace with your site's mainframe bridge.
    cmd = ["jcl-runner", str(Path(JCL_DIR) / JCL_FILE)]
    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(
            proc.communicate(), timeout=JOB_TIMEOUT_SEC
        )
    except FileNotFoundError:
        # jcl-runner is not installed in this environment — still
        # return a well-formed response so the wrapper can be used
        # as a contract stub.
        stdout = b""
        stderr = b"jcl-runner not available"

    # Parse each output dataset
    records: list[dict] = []
    for logical, physical in OUTPUT_BINDINGS.items():
        path = out_dir / physical
        if not path.exists():
            continue
        for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
            records.append({{"logical": logical, "raw": line}})

    duration = int((time.monotonic() - start) * 1000)
    warnings: list[str] = []
    if stderr:
        warnings.append(stderr.decode("utf-8", errors="ignore")[:500])

    return models.{name_out}(records=records, warnings=warnings, duration_ms=duration)
'''


def _classify_file_role(logical_name: str, physical_path: str) -> str:
    name = logical_name.upper()
    if "OUT" in name or "RESULT" in name or "REPORT" in name:
        return "output"
    if "IN" in name or "INPUT" in name or "REQUEST" in name:
        return "input"
    # Default: treat VSAM masters as inputs — they store state the
    # program reads, and the wrapper should not rewrite them unless
    # the caller says so.
    return "input"


def _slugify(program_id: str) -> str:
    """Convert a PROGRAM-ID into a FastAPI-friendly slug."""
    s = program_id.lower().replace("-", "_").replace(".", "_")
    return "".join(c if c.isalnum() or c == "_" else "_" for c in s)


def _route_for(program_id: str) -> str:
    return _slugify(program_id).replace("_", "-")


def _find_jcl_for_program(
    program_id: str, report: CobolScanReport
) -> str:
    """Pick the JCL file whose EXEC PGM= step points at this program."""
    for job in report.jcl_jobs:
        if program_id in job.steps:
            return Path(job.file_path).name
    return f"{program_id}.jcl"


def generate_wrapper(
    report: CobolScanReport,
    out_dir: Path,
) -> GeneratedWrapper:
    """Write a full FastAPI wrapper project for every program in the report."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "invokers").mkdir(exist_ok=True)

    result = GeneratedWrapper(out_dir=str(out_dir))
    programs = report.programs

    # ─ Models ─
    model_lines: list[str] = [_MODELS_HEADER]
    for p in programs:
        model_lines.append(
            _MODEL_TEMPLATE.format(
                program_id=p.program_id,
                name_in=f"{_slugify(p.program_id).capitalize()}Request",
                name_out=f"{_slugify(p.program_id).capitalize()}Response",
            )
        )
    models_path = out_dir / "models.py"
    models_path.write_text("".join(model_lines), encoding="utf-8")
    result.files_written.append(str(models_path.relative_to(out_dir)))

    # ─ Invokers package ─
    (out_dir / "invokers" / "__init__.py").write_text(
        "\n".join(f"from . import {_slugify(p.program_id)}" for p in programs) + "\n",
        encoding="utf-8",
    )
    result.files_written.append("invokers/__init__.py")

    for p in programs:
        inputs = {
            f.logical_name: f.physical_path
            for f in p.files
            if _classify_file_role(f.logical_name, f.physical_path) == "input"
        }
        outputs = {
            f.logical_name: f.physical_path
            for f in p.files
            if _classify_file_role(f.logical_name, f.physical_path) == "output"
        }
        module_name = _slugify(p.program_id)
        invoker_path = out_dir / "invokers" / f"{module_name}.py"
        invoker_path.write_text(
            _INVOKER_TEMPLATE.format(
                program_id=p.program_id,
                jcl_file=_find_jcl_for_program(p.program_id, report),
                input_bindings=repr(inputs),
                output_bindings=repr(outputs),
                name_in=f"{module_name.capitalize()}Request",
                name_out=f"{module_name.capitalize()}Response",
            ),
            encoding="utf-8",
        )
        result.files_written.append(f"invokers/{module_name}.py")

    # ─ main.py ─
    main_parts: list[str] = [
        _MAIN_HEADER,
        "from . import models\n",
        "from . import invokers\n\n",
        _MAIN_APP_INIT.replace("{programs}", repr([p.program_id for p in programs])),
    ]
    for p in programs:
        slug = _slugify(p.program_id)
        route = _route_for(p.program_id)
        output_file = next(
            (
                f.physical_path
                for f in p.files
                if _classify_file_role(f.logical_name, f.physical_path) == "output"
            ),
            "(none)",
        )
        inputs_str = ", ".join(
            f"{f.logical_name}={f.physical_path!r}"
            for f in p.files
            if _classify_file_role(f.logical_name, f.physical_path) == "input"
        ) or "(none)"
        main_parts.append(
            _MAIN_ROUTE_TEMPLATE.format(
                route=route,
                slug=slug,
                model_in=f"{slug.capitalize()}Request",
                model_out=f"{slug.capitalize()}Response",
                program_id=p.program_id,
                module=slug,
                inputs=inputs_str,
                output_file=output_file,
            )
        )
        result.endpoint_count += 1

    main_path = out_dir / "main.py"
    main_path.write_text("".join(main_parts), encoding="utf-8")
    result.files_written.append("main.py")

    # ─ requirements.txt ─
    (out_dir / "requirements.txt").write_text(_REQUIREMENTS, encoding="utf-8")
    result.files_written.append("requirements.txt")

    # ─ README.md ─
    endpoints_list = "\n".join(
        f"- `POST /v1/{_route_for(p.program_id)}` — invokes `{p.program_id}`"
        for p in programs
    )
    (out_dir / "README.md").write_text(
        _README.format(
            program_count=len(programs),
            endpoints_list=endpoints_list or "_(no programs found)_",
        ),
        encoding="utf-8",
    )
    result.files_written.append("README.md")

    result.program_count = len(programs)
    return result
