"""Post-build hooks: git init + GitHub repo creation.

Runs AFTER the synthesizer has written all template files to
disk. Each step is opt-in via flags on the BuildRequest. Failures
in this layer are NEVER fatal — the project still exists on disk
and the build is considered "complete" with warnings. The user
can re-run git/gh manually if needed.

Security posture:
  - All external commands invoked via `subprocess.run` with an
    args LIST (no shell=True). Eliminates shell injection.
  - `cwd` is the validated target directory (already path-checked
    by `synthesizer._validate_target` before we get here).
  - `project_name` is sanitized to a strict slug before being
    passed to `gh repo create` — even though `subprocess` with
    args is safe, GitHub itself rejects names with `/`, `..`,
    spaces, etc.
  - No token passed to `gh` — relies on the host's existing
    `gh auth login` state. The synthesizer process must run as
    a user that's already authenticated.

This module is sync. The post-build steps are quick (git init +
1 commit + gh repo create + push = a few seconds total) and
mixing async with subprocess.run gets ugly.
"""
from __future__ import annotations

import logging
import re
import shutil
import subprocess
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


# ── helpers ─────────────────────────────────────────────────────────


_REPO_NAME_RE = re.compile(r"^[A-Za-z0-9._-]{1,100}$")


def _sanitize_repo_name(name: str) -> Optional[str]:
    """Return a strict-valid GitHub repo name or None.

    GitHub allows alphanumeric, hyphen, underscore, period, up to
    100 chars. We additionally reject leading/trailing dots and
    consecutive dots (common abuse paths even though GitHub also
    rejects them).
    """
    if not name:
        return None
    candidate = name.strip()
    if not _REPO_NAME_RE.match(candidate):
        return None
    if candidate.startswith(".") or candidate.endswith("."):
        return None
    if ".." in candidate:
        return None
    return candidate


def _run(cmd: list[str], cwd: Path, timeout: int = 60) -> tuple[int, str, str]:
    """Run a subprocess and return (returncode, stdout, stderr).

    All calls go through here so the security posture (args list,
    no shell, capped timeout) is enforced in one place.
    """
    try:
        result = subprocess.run(
            cmd,
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
        return result.returncode, result.stdout or "", result.stderr or ""
    except subprocess.TimeoutExpired:
        return -1, "", f"timeout after {timeout}s"
    except FileNotFoundError as exc:
        return -1, "", f"command not found: {exc.filename}"
    except Exception as exc:
        return -1, "", f"unexpected: {type(exc).__name__}: {exc}"


# ── git init + first commit ────────────────────────────────────────


def init_git_repo(target_dir: Path, project_name: str) -> tuple[bool, Optional[str], list[str]]:
    """Run `git init` + first commit in `target_dir`.

    Returns (success, first_commit_sha, warnings).
    Failure does NOT raise — the project remains on disk and the
    caller surfaces the warnings.
    """
    warnings: list[str] = []

    if shutil.which("git") is None:
        warnings.append("git binary not found on PATH; skipped git init")
        return False, None, warnings

    # `git init` — idempotent on already-initialized dirs.
    rc, _, err = _run(["git", "init", "--initial-branch=main"], cwd=target_dir)
    if rc != 0:
        warnings.append(f"git init failed: {err.strip()[:200]}")
        return False, None, warnings

    # Stage and commit. Use a generated author so the host's git
    # config doesn't accidentally leak the operator's identity
    # into the user's project history. The user can `git commit
    # --amend --reset-author` later if they want their own ident.
    author = "NexusForge Synthesizer <noreply@nexusforge.ai>"

    rc, _, err = _run(["git", "add", "-A"], cwd=target_dir)
    if rc != 0:
        warnings.append(f"git add failed: {err.strip()[:200]}")
        return False, None, warnings

    commit_msg = f"Initial commit — {project_name} (generated by NexusForge)"
    rc, _, err = _run(
        [
            "git",
            "-c", f"user.name=NexusForge Synthesizer",
            "-c", f"user.email=noreply@nexusforge.ai",
            "commit",
            "-m", commit_msg,
            "--author", author,
        ],
        cwd=target_dir,
    )
    if rc != 0:
        warnings.append(f"git commit failed: {err.strip()[:200]}")
        return False, None, warnings

    # Capture the commit SHA for the response.
    rc, sha, _ = _run(["git", "rev-parse", "HEAD"], cwd=target_dir)
    sha = sha.strip() if rc == 0 else None

    logger.info("git init complete in %s, sha=%s", target_dir, sha[:12] if sha else "?")
    return True, sha, warnings


# ── gh repo create + push ──────────────────────────────────────────


def create_github_repo(
    target_dir: Path,
    project_name: str,
    visibility: str,
) -> tuple[Optional[str], list[str]]:
    """Run `gh repo create <name> --{private|public} --source=. --push`.

    Requires:
      1. `gh` CLI installed and on PATH.
      2. The host already authenticated via `gh auth login`.
      3. `target_dir` already has `git init` done (handled by the
         caller — `synthesize()` only calls this when both flags
         are set, with `git_init` running first).

    Returns (repo_url_or_None, warnings).
    """
    warnings: list[str] = []

    if shutil.which("gh") is None:
        warnings.append("gh CLI not found on PATH; skipped GitHub repo creation")
        return None, warnings

    safe_name = _sanitize_repo_name(project_name)
    if not safe_name:
        warnings.append(
            f"project_name {project_name!r} not safe for GitHub repo name; "
            f"must be alphanumeric + . _ - up to 100 chars"
        )
        return None, warnings

    if visibility not in {"private", "public"}:
        warnings.append(f"unsupported visibility {visibility!r}; defaulting to private")
        visibility = "private"

    # Check `gh auth status` first — fast-fail with a clear message
    # rather than a confusing error from `gh repo create`.
    rc, _, err = _run(["gh", "auth", "status"], cwd=target_dir, timeout=15)
    if rc != 0:
        warnings.append(
            "gh CLI not authenticated. Run `gh auth login` on the host, "
            f"then push manually: cd <project> && git push -u origin main. "
            f"Underlying error: {err.strip()[:200]}"
        )
        return None, warnings

    # Create the repo + push.
    cmd = [
        "gh", "repo", "create", safe_name,
        f"--{visibility}",
        "--source=.",
        "--push",
    ]
    rc, out, err = _run(cmd, cwd=target_dir, timeout=120)
    if rc != 0:
        warnings.append(f"gh repo create failed: {err.strip()[:300]}")
        return None, warnings

    # gh repo create prints the URL on stdout (or stderr on older versions).
    url = None
    for line in (out + "\n" + err).splitlines():
        line = line.strip()
        if line.startswith("https://github.com/"):
            url = line.split()[0]
            break

    if url:
        logger.info("github repo created: %s", url)
    else:
        # gh succeeded but we couldn't parse the URL — best-effort guess.
        rc2, who, _ = _run(["gh", "api", "user", "--jq", ".login"], cwd=target_dir, timeout=10)
        if rc2 == 0 and who.strip():
            url = f"https://github.com/{who.strip()}/{safe_name}"
            warnings.append(f"derived repo URL from gh user lookup: {url}")
        else:
            warnings.append("gh repo create succeeded but URL could not be parsed; check `gh repo view`")

    return url, warnings
