"""Template registry for the Platform Synthesizer.

A template is a curated, tested project skeleton with a known
stack. It declares which `PlatformSpec` slots it can absorb, what
its required slots are, and its scoring signals (which spec values
make it a good match).

The first iteration ships ONE template: FastAPI + React + Postgres.
That's the stack Christian uses himself, the most-tested combo in
NexusForge, and the easiest to verify end-to-end. Adding more
templates is purely additive — register a new one in `_REGISTRY`
and add a `_render_*` function below.

Each template's `_render` function is responsible for:
  1. Emitting the file tree as a dict {relative_path: content_str}
  2. Substituting spec slot values into the file contents
  3. Validating that all required slots are filled before render

The synthesizer module writes the dict to disk.
"""
from __future__ import annotations

from typing import Callable

from .feature_addons import apply_addons
from .schemas import PlatformSpec, TemplateMatch, TemplateSummary


# ── scoring helpers ─────────────────────────────────────────────────


def _score_against(template: TemplateSummary, spec: PlatformSpec) -> tuple[float, list[str]]:
    """Score a template against the user's accumulated spec.

    Returns (score in [0,1], list of matched-signal strings for
    the debug panel). Each signal that lines up adds a fixed
    weight; the final score is normalized.
    """
    signals: list[str] = []
    score = 0.0

    # If the user picked an explicit language, the template MUST
    # match or it scores zero. Same for backend framework.
    if spec.language and spec.language not in {s.lower() for s in template.stack}:
        return 0.0, [f"language mismatch: spec={spec.language}, template={template.stack}"]

    # Stack overlaps: strong signal.
    template_stack_lower = {s.lower() for s in template.stack}
    if spec.backend_framework and spec.backend_framework.lower() in template_stack_lower:
        score += 0.30
        signals.append(f"backend framework matches: {spec.backend_framework}")
    if spec.frontend_framework and spec.frontend_framework.lower() in template_stack_lower:
        score += 0.20
        signals.append(f"frontend framework matches: {spec.frontend_framework}")
    if spec.database and spec.database.lower() in template_stack_lower:
        score += 0.15
        signals.append(f"database matches: {spec.database}")

    # `best_for` matches: each phrase in best_for that appears in
    # the user's description or features adds 0.10.
    haystack = " ".join(
        [
            (spec.description or "").lower(),
            *[f.lower() for f in spec.features],
            *[i.lower() for i in spec.integrations],
        ]
    )
    for phrase in template.best_for:
        if phrase.lower() in haystack:
            score += 0.10
            signals.append(f"use-case match: {phrase!r}")

    # Floor: every COMPATIBLE template (i.e., didn't fail the
    # hard language-mismatch check above) gets a baseline score of
    # 0.10 so the UI doesn't render "0%" across the board on a
    # bare spec — that looks broken. As the user describes more,
    # signals lift each template above the floor at different
    # rates, and the ordering becomes meaningful.
    if score < 0.10:
        score = 0.10
        if not signals:
            signals.append("compatible (no specific signals matched yet)")

    # Cap at 1.0.
    return min(score, 1.0), signals


# ── template implementations ────────────────────────────────────────


def _fastapi_react_postgres_summary() -> TemplateSummary:
    return TemplateSummary(
        template_id="fastapi_react_postgres",
        name="FastAPI + React + Postgres",
        short_description=(
            "Production-ready Python backend with FastAPI, React frontend "
            "with Vite, Postgres for persistence. JWT auth optional. "
            "The stack NexusForge itself runs on."
        ),
        stack=["python", "fastapi", "react", "vite", "postgres"],
        best_for=[
            "saas",
            "dashboard",
            "internal tool",
            "api",
            "automation",
            "ai",
            "data",
            "agents",
        ],
    )


def _render_fastapi_react_postgres(spec: PlatformSpec) -> dict[str, str]:
    """Emit the file tree for the FastAPI + React + Postgres template.

    Required slots: project_name. Everything else has sensible
    defaults so the user can run it immediately and refine later.
    """
    if not spec.project_name:
        raise ValueError("project_name is required to build this template")

    name = spec.project_name
    safe_name = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in name).lower()
    description = spec.description or f"{name} — generated by NexusForge Platform Synthesizer"
    auth = spec.auth or "jwt"
    features_md = (
        "\n".join(f"- {f}" for f in spec.features) if spec.features else "- (no features yet — describe more in chat to refine)"
    )
    integrations_md = (
        "\n".join(f"- {i}" for i in spec.integrations) if spec.integrations else "- (none yet)"
    )

    files: dict[str, str] = {}

    # ── README ──
    files["README.md"] = f"""# {name}

{description}

> Generated by NexusForge AI — Platform Synthesizer (FastAPI + React + Postgres template).

## Stack
- **Backend**: Python 3.12 + FastAPI
- **Frontend**: React 18 + Vite
- **Database**: PostgreSQL 16
- **Auth**: {auth}

## Features
{features_md}

## Integrations
{integrations_md}

## Quick start

```bash
# Backend
cd backend
python -m venv .venv && source .venv/bin/activate  # or .venv\\Scripts\\activate on Windows
pip install -r requirements.txt
cp .env.example .env  # then edit DATABASE_URL
uvicorn app.main:app --reload

# Frontend (separate shell)
cd frontend
npm install
npm run dev
```

The backend listens on `http://localhost:8000`, the frontend on `http://localhost:5173`.
The frontend's `VITE_API_URL` points at `http://localhost:8000/api` by default.

## Project layout
- `backend/app/main.py` — FastAPI entry, CORS, lifespan
- `backend/app/routes/` — HTTP handlers
- `backend/app/db/` — Postgres connection + migrations
- `frontend/src/` — React UI
- `frontend/src/services/api.js` — fetch wrapper

## Next steps after generation
1. Set `DATABASE_URL` in `backend/.env`
2. Run the SQL in `backend/app/db/migrations/001_init.sql` against your Postgres
3. Generate a JWT secret: `python -c "import secrets; print(secrets.token_urlsafe(48))"` and put it in `JWT_SECRET`
4. Replace the stub endpoints in `backend/app/routes/items.py` with your real domain
"""

    # ── Backend ──
    files["backend/requirements.txt"] = """fastapi==0.115.0
uvicorn[standard]==0.30.0
pydantic>=2.10.0,<3.0.0
pydantic-settings>=2.5.0,<3.0.0
asyncpg==0.29.0
python-multipart==0.0.9
PyJWT>=2.8.0,<3.0.0
bcrypt>=4.1.0,<5.0.0
"""

    files["backend/.env.example"] = """# Postgres connection — same shape as on Render / Supabase / local docker
DATABASE_URL=postgres://user:password@localhost:5432/dbname

# JWT signing secret (generate with: python -c "import secrets; print(secrets.token_urlsafe(48))")
JWT_SECRET=changeme-in-production-use-token-urlsafe-48

# CORS allowlist for browser callers (comma-separated)
ALLOWED_ORIGINS=http://localhost:5173
"""

    files["backend/app/__init__.py"] = ""

    files["backend/app/main.py"] = f'''"""FastAPI entry for {name}.

Generated by NexusForge AI Platform Synthesizer.
"""
import os
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.routes.health import router as health_router
from app.routes.items import router as items_router
from app.routes.auth import router as auth_router
from app.db.client import get_pool, close_pool


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Eager-warm the pool so the first request doesn't pay the latency.
    try:
        await get_pool()
    except Exception as exc:
        print(f"Warning: DB pool not warmed at startup: {{exc}}")
    yield
    await close_pool()


app = FastAPI(title="{name}", lifespan=lifespan)

origins = [o.strip() for o in os.environ.get("ALLOWED_ORIGINS", "*").split(",") if o.strip()]
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=False,
    allow_methods=["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
    allow_headers=["Authorization", "Content-Type"],
)

app.include_router(health_router, prefix="/api", tags=["health"])
app.include_router(auth_router, prefix="/api/auth", tags=["auth"])
app.include_router(items_router, prefix="/api/items", tags=["items"])
'''

    files["backend/app/routes/__init__.py"] = ""

    files["backend/app/routes/health.py"] = '''"""Liveness + readiness probes."""
from fastapi import APIRouter

router = APIRouter()


@router.get("/health")
async def health():
    return {"status": "healthy"}


@router.get("/ping")
async def ping():
    return {"pong": True}
'''

    files["backend/app/routes/auth.py"] = f'''"""Stub JWT auth.

Generated baseline — replace with your real user store.
"""
import os
import time

import jwt
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

router = APIRouter()
JWT_SECRET = os.environ.get("JWT_SECRET", "")


class LoginRequest(BaseModel):
    email: str
    password: str


@router.post("/login")
async def login(body: LoginRequest):
    """Stub: accepts any email + password=demo for now.

    Replace with a real lookup against your users table.
    """
    if body.password != "demo":
        raise HTTPException(401, "Invalid credentials")
    if not JWT_SECRET:
        raise HTTPException(500, "JWT_SECRET not configured")
    payload = {{
        "sub": body.email,
        "iat": int(time.time()),
        "exp": int(time.time()) + 8 * 3600,
    }}
    token = jwt.encode(payload, JWT_SECRET, algorithm="HS256")
    return {{"token": token}}
'''

    files["backend/app/routes/items.py"] = '''"""Items CRUD — example domain you'll replace."""
from uuid import UUID

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from app.db.client import get_pool

router = APIRouter()


class ItemCreate(BaseModel):
    name: str
    description: str | None = None


@router.get("/")
async def list_items():
    pool = await get_pool()
    async with pool.acquire() as conn:
        rows = await conn.fetch("SELECT id, name, description FROM items ORDER BY id DESC LIMIT 100")
    return [{"id": str(r["id"]), "name": r["name"], "description": r["description"]} for r in rows]


@router.post("/", status_code=201)
async def create_item(body: ItemCreate):
    pool = await get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "INSERT INTO items (name, description) VALUES ($1, $2) RETURNING id, name, description",
            body.name, body.description,
        )
    return {"id": str(row["id"]), "name": row["name"], "description": row["description"]}


@router.get("/{item_id}")
async def get_item(item_id: UUID):
    pool = await get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow("SELECT id, name, description FROM items WHERE id = $1", item_id)
    if not row:
        raise HTTPException(404, "Item not found")
    return {"id": str(row["id"]), "name": row["name"], "description": row["description"]}
'''

    files["backend/app/db/__init__.py"] = ""

    files["backend/app/db/client.py"] = '''"""Asyncpg pool — warm once, share across requests."""
import os

import asyncpg

_pool: asyncpg.Pool | None = None


async def get_pool() -> asyncpg.Pool:
    global _pool
    if _pool is None:
        url = os.environ.get("DATABASE_URL")
        if not url:
            raise RuntimeError("DATABASE_URL not set")
        _pool = await asyncpg.create_pool(url, min_size=1, max_size=10)
    return _pool


async def close_pool() -> None:
    global _pool
    if _pool is not None:
        await _pool.close()
        _pool = None
'''

    files["backend/app/db/migrations/001_init.sql"] = '''-- Run this once against your Postgres before starting the app.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_items_created ON items(created_at DESC);
'''

    # ── Frontend ──
    files["frontend/package.json"] = f"""{{
  "name": "{safe_name}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "react": "^18.3.0",
    "react-dom": "^18.3.0",
    "react-router-dom": "^6.26.0"
  }},
  "devDependencies": {{
    "@vitejs/plugin-react": "^4.3.0",
    "vite": "^5.4.0"
  }}
}}
"""

    files["frontend/vite.config.js"] = """import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: { port: 5173 },
})
"""

    files["frontend/index.html"] = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
"""

    files["frontend/src/main.jsx"] = '''import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
'''

    files["frontend/src/App.jsx"] = f'''import {{ useEffect, useState }} from 'react'
import {{ fetchAPI }} from './services/api.js'

export default function App() {{
  const [items, setItems] = useState([])
  const [name, setName] = useState('')
  const [error, setError] = useState(null)

  useEffect(() => {{
    fetchAPI('/items/').then(res => {{
      if (res.error) setError(res.error)
      else setItems(res.data || [])
    }})
  }}, [])

  async function add() {{
    if (!name.trim()) return
    const res = await fetchAPI('/items/', {{
      method: 'POST',
      body: JSON.stringify({{ name }}),
    }})
    if (res.error) {{ setError(res.error); return }}
    setItems([res.data, ...items])
    setName('')
  }}

  return (
    <div style={{{{ fontFamily: 'system-ui', maxWidth: 720, margin: '40px auto', padding: 20 }}}}>
      <h1>{name}</h1>
      <p style={{{{ color: '#666' }}}}>{description}</p>
      <div style={{{{ display: 'flex', gap: 8, marginBottom: 20 }}}}>
        <input
          value={{name}}
          onChange={{e => setName(e.target.value)}}
          placeholder="New item name"
          style={{{{ flex: 1, padding: 8, border: '1px solid #ddd', borderRadius: 4 }}}}
        />
        <button onClick={{add}} style={{{{ padding: '8px 16px' }}}}>Add</button>
      </div>
      {{error && <p style={{{{ color: 'crimson' }}}}>{{error}}</p>}}
      <ul>
        {{items.map(it => (
          <li key={{it.id}}>{{it.name}}</li>
        ))}}
      </ul>
    </div>
  )
}}
'''

    files["frontend/src/services/api.js"] = '''const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000/api'

export async function fetchAPI(endpoint, options = {}) {
  try {
    const res = await fetch(`${API_URL}${endpoint}`, {
      ...options,
      headers: { 'Content-Type': 'application/json', ...(options.headers || {}) },
    })
    if (!res.ok) {
      let detail = `HTTP ${res.status}`
      try { const body = await res.json(); detail = body.detail || detail } catch {}
      return { data: null, error: detail }
    }
    return { data: await res.json(), error: null }
  } catch (err) {
    return { data: null, error: err.message }
  }
}
'''

    files[".gitignore"] = """# Python
__pycache__/
*.py[cod]
.venv/
*.egg-info/

# Node
node_modules/
dist/

# Env
.env
.env.local
"""

    apply_addons(files, spec, "fastapi_react_postgres")
    return files


# ── registry ────────────────────────────────────────────────────────


# ── Express + Next.js + Postgres ────────────────────────────────────


def _express_next_postgres_summary() -> TemplateSummary:
    return TemplateSummary(
        template_id="express_next_postgres",
        name="Express + Next.js + Postgres",
        short_description=(
            "Modern Node-only stack. Express API in TypeScript, Next.js 14 "
            "frontend with the App Router, Postgres for persistence. Ideal "
            "when the team prefers JS/TS end-to-end."
        ),
        stack=["typescript", "javascript", "node", "express", "next", "postgres"],
        best_for=[
            "saas",
            "dashboard",
            "marketing site",
            "e-commerce",
            "auth",
            "blog",
            "ssr",
        ],
    )


def _render_express_next_postgres(spec: PlatformSpec) -> dict[str, str]:
    if not spec.project_name:
        raise ValueError("project_name is required to build this template")

    name = spec.project_name
    safe_name = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in name).lower()
    description = spec.description or f"{name} — generated by NexusForge Platform Synthesizer"
    features_md = (
        "\n".join(f"- {f}" for f in spec.features) if spec.features else "- (none yet)"
    )

    files: dict[str, str] = {}

    files["README.md"] = f"""# {name}

{description}

> Generated by NexusForge AI — Platform Synthesizer (Express + Next.js + Postgres template).

## Stack
- **Backend**: Node 20 + Express + TypeScript
- **Frontend**: Next.js 14 (App Router) + React 18
- **Database**: PostgreSQL 16
- **ORM**: `pg` (raw queries — swap to Prisma/Drizzle later if you want)

## Features
{features_md}

## Quick start

```bash
# Backend
cd backend
npm install
cp .env.example .env  # then edit DATABASE_URL
npm run dev   # http://localhost:8000

# Frontend (separate shell)
cd frontend
npm install
npm run dev   # http://localhost:3000
```

The frontend expects `NEXT_PUBLIC_API_URL=http://localhost:8000` (set in `frontend/.env.local`).

## Project layout
- `backend/src/index.ts` — Express entry, CORS, route mounting
- `backend/src/routes/items.ts` — CRUD example
- `backend/src/db.ts` — pg pool
- `frontend/app/page.tsx` — home (lists items, form to add)
- `frontend/lib/api.ts` — fetch wrapper

## Next steps
1. Set DATABASE_URL in `backend/.env`
2. Run `psql $DATABASE_URL -f backend/migrations/001_init.sql`
3. Replace the items example with your real domain
"""

    # ── Backend ──
    files["backend/package.json"] = f"""{{
  "name": "{safe_name}-backend",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "tsx watch src/index.ts",
    "build": "tsc",
    "start": "node dist/index.js"
  }},
  "dependencies": {{
    "cors": "^2.8.5",
    "dotenv": "^16.4.5",
    "express": "^4.21.0",
    "pg": "^8.13.0"
  }},
  "devDependencies": {{
    "@types/cors": "^2.8.17",
    "@types/express": "^5.0.0",
    "@types/node": "^22.7.0",
    "@types/pg": "^8.11.10",
    "tsx": "^4.19.0",
    "typescript": "^5.6.0"
  }}
}}
"""

    files["backend/tsconfig.json"] = """{
  "compilerOptions": {
    "target": "ES2022",
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "outDir": "dist",
    "declaration": false,
    "sourceMap": true
  },
  "include": ["src"]
}
"""

    files["backend/.env.example"] = """DATABASE_URL=postgres://user:password@localhost:5432/dbname
PORT=8000
ALLOWED_ORIGINS=http://localhost:3000
"""

    files["backend/src/index.ts"] = '''import "dotenv/config";
import express from "express";
import cors from "cors";

import { itemsRouter } from "./routes/items";
import { closePool } from "./db";

const app = express();
const PORT = Number(process.env.PORT || 8000);

const origins = (process.env.ALLOWED_ORIGINS || "*")
  .split(",")
  .map((o) => o.trim())
  .filter(Boolean);

app.use(cors({ origin: origins.includes("*") ? true : origins }));
app.use(express.json({ limit: "1mb" }));

app.get("/api/health", (_req, res) => {
  res.json({ status: "healthy" });
});

app.get("/api/ping", (_req, res) => {
  res.json({ pong: true });
});

app.use("/api/items", itemsRouter);

app.use((err: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
  console.error(err);
  res.status(500).json({ error: "Internal server error" });
});

const server = app.listen(PORT, () => {
  console.log(`Listening on :${PORT}`);
});

process.on("SIGTERM", async () => {
  server.close();
  await closePool();
  process.exit(0);
});
'''

    files["backend/src/db.ts"] = '''import { Pool } from "pg";

let pool: Pool | null = null;

export function getPool(): Pool {
  if (!pool) {
    const url = process.env.DATABASE_URL;
    if (!url) throw new Error("DATABASE_URL not set");
    pool = new Pool({ connectionString: url, max: 10 });
  }
  return pool;
}

export async function closePool(): Promise<void> {
  if (pool) {
    await pool.end();
    pool = null;
  }
}
'''

    files["backend/src/routes/items.ts"] = '''import { Router } from "express";
import { getPool } from "../db";

export const itemsRouter = Router();

itemsRouter.get("/", async (_req, res, next) => {
  try {
    const pool = getPool();
    const { rows } = await pool.query(
      "SELECT id, name, description FROM items ORDER BY id DESC LIMIT 100"
    );
    res.json(rows);
  } catch (e) {
    next(e);
  }
});

itemsRouter.post("/", async (req, res, next) => {
  try {
    const { name, description } = req.body || {};
    if (!name || typeof name !== "string") {
      return res.status(422).json({ error: "name required" });
    }
    const pool = getPool();
    const { rows } = await pool.query(
      "INSERT INTO items (name, description) VALUES ($1, $2) RETURNING id, name, description",
      [name, description || null]
    );
    res.status(201).json(rows[0]);
  } catch (e) {
    next(e);
  }
});

itemsRouter.get("/:id", async (req, res, next) => {
  try {
    const pool = getPool();
    const { rows } = await pool.query(
      "SELECT id, name, description FROM items WHERE id = $1",
      [req.params.id]
    );
    if (!rows.length) return res.status(404).json({ error: "Not found" });
    res.json(rows[0]);
  } catch (e) {
    next(e);
  }
});
'''

    files["backend/migrations/001_init.sql"] = '''CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_items_created ON items(created_at DESC);
'''

    # ── Frontend (Next.js 14 App Router) ──
    files["frontend/package.json"] = f"""{{
  "name": "{safe_name}-frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  }},
  "dependencies": {{
    "next": "^14.2.0",
    "react": "^18.3.0",
    "react-dom": "^18.3.0"
  }},
  "devDependencies": {{
    "@types/node": "^22.7.0",
    "@types/react": "^18.3.0",
    "@types/react-dom": "^18.3.0",
    "typescript": "^5.6.0"
  }}
}}
"""

    files["frontend/.env.local.example"] = "NEXT_PUBLIC_API_URL=http://localhost:8000\n"

    files["frontend/next.config.js"] = """/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
};
"""

    files["frontend/tsconfig.json"] = """{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
"""

    files["frontend/app/layout.tsx"] = f'''export const metadata = {{
  title: "{name}",
  description: "{description.replace('"', "'")}",
}};

export default function RootLayout({{ children }}: {{ children: React.ReactNode }}) {{
  return (
    <html lang="en">
      <body style={{{{ fontFamily: "system-ui", margin: 0 }}}}>{{children}}</body>
    </html>
  );
}}
'''

    files["frontend/app/page.tsx"] = f'''"use client";

import {{ useEffect, useState }} from "react";
import {{ fetchAPI }} from "../lib/api";

interface Item {{
  id: string;
  name: string;
  description: string | null;
}}

export default function Home() {{
  const [items, setItems] = useState<Item[]>([]);
  const [name, setName] = useState("");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {{
    fetchAPI<Item[]>("/items/").then((res) => {{
      if (res.error) setError(res.error);
      else setItems(res.data || []);
    }});
  }}, []);

  async function add() {{
    if (!name.trim()) return;
    const res = await fetchAPI<Item>("/items/", {{
      method: "POST",
      body: JSON.stringify({{ name }}),
    }});
    if (res.error) {{ setError(res.error); return; }}
    setItems([res.data!, ...items]);
    setName("");
  }}

  return (
    <main style={{{{ maxWidth: 720, margin: "40px auto", padding: 20 }}}}>
      <h1>{name}</h1>
      <p style={{{{ color: "#666" }}}}>{description}</p>
      <div style={{{{ display: "flex", gap: 8, marginBottom: 20 }}}}>
        <input
          value={{name}}
          onChange={{(e) => setName(e.target.value)}}
          placeholder="New item name"
          style={{{{ flex: 1, padding: 8, border: "1px solid #ddd", borderRadius: 4 }}}}
        />
        <button onClick={{add}} style={{{{ padding: "8px 16px" }}}}>Add</button>
      </div>
      {{error && <p style={{{{ color: "crimson" }}}}>{{error}}</p>}}
      <ul>{{items.map((it) => <li key={{it.id}}>{{it.name}}</li>)}}</ul>
    </main>
  );
}}
'''

    files["frontend/lib/api.ts"] = '''const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

export interface ApiResponse<T> {
  data: T | null;
  error: string | null;
}

export async function fetchAPI<T>(
  endpoint: string,
  options: RequestInit = {}
): Promise<ApiResponse<T>> {
  try {
    const res = await fetch(`${API_URL}/api${endpoint}`, {
      ...options,
      headers: { "Content-Type": "application/json", ...(options.headers || {}) },
    });
    if (!res.ok) {
      const body = await res.json().catch(() => ({}));
      return { data: null, error: body.error || `HTTP ${res.status}` };
    }
    return { data: (await res.json()) as T, error: null };
  } catch (err) {
    return { data: null, error: err instanceof Error ? err.message : "unknown" };
  }
}
'''

    files[".gitignore"] = """node_modules/
dist/
.next/
.env
.env.local
*.log
"""

    apply_addons(files, spec, "express_next_postgres")
    return files


# ── Django + Postgres ────────────────────────────────────────────────


def _django_postgres_summary() -> TemplateSummary:
    return TemplateSummary(
        template_id="django_postgres",
        name="Django + Postgres",
        short_description=(
            "Batteries-included Python web framework. Built-in admin UI "
            "(huge for internal tools), ORM, auth, sessions. Server-rendered "
            "templates — no separate frontend build."
        ),
        stack=["python", "django", "postgres"],
        best_for=[
            "internal tool",
            "admin",
            "crud",
            "back office",
            "cms",
            "monolith",
        ],
    )


def _render_django_postgres(spec: PlatformSpec) -> dict[str, str]:
    if not spec.project_name:
        raise ValueError("project_name is required to build this template")

    name = spec.project_name
    safe_name = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in name).lower()
    py_module = safe_name.replace("-", "_")
    description = spec.description or f"{name} — generated by NexusForge Platform Synthesizer"

    files: dict[str, str] = {}

    files["README.md"] = f"""# {name}

{description}

> Generated by NexusForge AI — Platform Synthesizer (Django + Postgres template).

## Stack
- **Framework**: Django 5
- **Database**: PostgreSQL 16
- **Frontend**: Django templates (server-rendered) — no separate JS build
- **Admin**: Django Admin at `/admin/` (auto-CRUD for any registered model)

## Quick start

```bash
python -m venv .venv && source .venv/bin/activate  # or .venv\\Scripts\\activate
pip install -r requirements.txt
cp .env.example .env  # edit DATABASE_URL
python manage.py migrate
python manage.py createsuperuser
python manage.py runserver
```

Visit:
- Public site: http://localhost:8000/
- Admin: http://localhost:8000/admin/

## Project layout
- `manage.py` — Django CLI entry
- `{py_module}/settings.py` — config (env-driven)
- `{py_module}/urls.py` — root URL conf
- `core/` — your domain app (Item model + views + admin)

## Next steps
1. Replace the `Item` model in `core/models.py` with your real domain
2. Run `python manage.py makemigrations core && python manage.py migrate`
3. Register more models in `core/admin.py` for instant admin UI
"""

    files["requirements.txt"] = """Django==5.1.0
psycopg[binary]==3.2.0
python-dotenv==1.0.1
gunicorn==23.0.0
"""

    files[".env.example"] = """DATABASE_URL=postgres://user:password@localhost:5432/dbname
SECRET_KEY=changeme-django-secret-key-50-chars-or-more-and-random
DEBUG=True
ALLOWED_HOSTS=localhost,127.0.0.1
"""

    files["manage.py"] = f"""#!/usr/bin/env python
import os
import sys


def main():
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{py_module}.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError("Couldn't import Django. Did you install requirements.txt?") from exc
    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
"""

    files[f"{py_module}/__init__.py"] = ""

    files[f"{py_module}/settings.py"] = f'''"""Django settings for {name}."""
from pathlib import Path
import os

from dotenv import load_dotenv
from urllib.parse import urlparse

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-change-me-in-production")
DEBUG = os.environ.get("DEBUG", "True") == "True"
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "*").split(",")]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "{py_module}.urls"

TEMPLATES = [
    {{
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {{
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        }},
    }},
]

WSGI_APPLICATION = "{py_module}.wsgi.application"

# DATABASE_URL parser (avoids dj-database-url dependency)
_db_url = os.environ.get("DATABASE_URL", "")
if _db_url:
    _parsed = urlparse(_db_url)
    DATABASES = {{
        "default": {{
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _parsed.path.lstrip("/"),
            "USER": _parsed.username or "",
            "PASSWORD": _parsed.password or "",
            "HOST": _parsed.hostname or "localhost",
            "PORT": _parsed.port or 5432,
        }}
    }}
else:
    DATABASES = {{
        "default": {{
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }}
    }}

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
'''

    files[f"{py_module}/urls.py"] = '''from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
]
'''

    files[f"{py_module}/wsgi.py"] = f'''import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{py_module}.settings")
application = get_wsgi_application()
'''

    files[f"{py_module}/asgi.py"] = f'''import os

from django.core.asgi import get_asgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{py_module}.settings")
application = get_asgi_application()
'''

    # ── Core app (the domain) ──
    files["core/__init__.py"] = ""

    files["core/apps.py"] = '''from django.apps import AppConfig


class CoreConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "core"
'''

    files["core/models.py"] = '''from django.db import models


class Item(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-created_at"]
'''

    files["core/admin.py"] = '''from django.contrib import admin

from .models import Item


@admin.register(Item)
class ItemAdmin(admin.ModelAdmin):
    list_display = ("name", "created_at")
    search_fields = ("name", "description")
'''

    files["core/views.py"] = '''from django.shortcuts import render
from django.http import JsonResponse

from .models import Item


def home(request):
    items = Item.objects.all()[:50]
    return render(request, "core/home.html", {"items": items})


def health(request):
    return JsonResponse({"status": "healthy"})
'''

    files["core/urls.py"] = '''from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("health/", views.health, name="health"),
]
'''

    files["core/templates/core/home.html"] = f"""<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{name}</title>
    <style>
        body {{ font-family: system-ui; max-width: 720px; margin: 40px auto; padding: 20px; }}
        h1 {{ font-size: 24px; }}
        p.subtitle {{ color: #666; }}
        ul {{ padding-left: 20px; }}
    </style>
</head>
<body>
    <h1>{name}</h1>
    <p class="subtitle">{description}</p>
    <p>Sign in to <a href="/admin/">/admin/</a> to manage records.</p>
    <h2>Items</h2>
    <ul>
        {{% for item in items %}}
            <li>{{{{ item.name }}}}</li>
        {{% empty %}}
            <li><em>No items yet — add some via /admin/</em></li>
        {{% endfor %}}
    </ul>
</body>
</html>
"""

    files[".gitignore"] = """__pycache__/
*.py[cod]
.venv/
*.egg-info/
.env
db.sqlite3
staticfiles/
"""

    apply_addons(files, spec, "django_postgres")
    return files


# ── Go + Gin + Postgres ──────────────────────────────────────────────


def _go_gin_postgres_summary() -> TemplateSummary:
    return TemplateSummary(
        template_id="go_gin_postgres",
        name="Go + Gin + Postgres",
        short_description=(
            "Compiled Go binary, Gin HTTP framework, Postgres driver. "
            "Single binary deploys, low memory footprint, fast cold starts. "
            "API-only; no built-in frontend."
        ),
        stack=["go", "gin", "postgres"],
        best_for=[
            "api",
            "microservice",
            "high throughput",
            "low latency",
            "backend",
        ],
    )


def _render_go_gin_postgres(spec: PlatformSpec) -> dict[str, str]:
    if not spec.project_name:
        raise ValueError("project_name is required to build this template")

    name = spec.project_name
    safe_name = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in name).lower()
    description = spec.description or f"{name} — generated by NexusForge Platform Synthesizer"

    files: dict[str, str] = {}

    files["README.md"] = f"""# {name}

{description}

> Generated by NexusForge AI — Platform Synthesizer (Go + Gin + Postgres template).

## Stack
- **Language**: Go 1.22+
- **Framework**: Gin
- **Driver**: pgx/v5
- **API only** — pair with any frontend (or none)

## Quick start

```bash
go mod download
cp .env.example .env  # edit DATABASE_URL
psql $DATABASE_URL -f migrations/001_init.sql
go run .
```

Listens on `:8000` by default. Endpoints:
- `GET  /api/health` — liveness
- `GET  /api/items` — list
- `POST /api/items` — create (`{{ "name": "...", "description": "..." }}`)
- `GET  /api/items/:id` — get one

## Project layout
- `main.go` — entry, router setup
- `db.go` — pgx pool
- `items.go` — items handlers
- `migrations/` — SQL files

## Build for production

```bash
CGO_ENABLED=0 go build -ldflags="-s -w" -o bin/{safe_name} .
./bin/{safe_name}
```

Single static binary, ~10 MB. Drop in a Docker scratch image.
"""

    files["go.mod"] = f"""module {safe_name}

go 1.22

require (
\tgithub.com/gin-contrib/cors v1.7.2
\tgithub.com/gin-gonic/gin v1.10.0
\tgithub.com/jackc/pgx/v5 v5.7.0
\tgithub.com/joho/godotenv v1.5.1
)
"""

    files[".env.example"] = """DATABASE_URL=postgres://user:password@localhost:5432/dbname
PORT=8000
ALLOWED_ORIGINS=http://localhost:3000
"""

    files["main.go"] = f'''package main

import (
\t"context"
\t"log"
\t"os"
\t"strings"

\t"github.com/gin-contrib/cors"
\t"github.com/gin-gonic/gin"
\t"github.com/joho/godotenv"
)

func main() {{
\t_ = godotenv.Load()

\tctx := context.Background()
\tif err := initPool(ctx); err != nil {{
\t\tlog.Fatalf("db: %v", err)
\t}}
\tdefer closePool()

\tport := os.Getenv("PORT")
\tif port == "" {{
\t\tport = "8000"
\t}}

\tr := gin.Default()

\torigins := strings.Split(os.Getenv("ALLOWED_ORIGINS"), ",")
\tif len(origins) == 0 || (len(origins) == 1 && origins[0] == "") {{
\t\torigins = []string{{"*"}}
\t}}
\tr.Use(cors.New(cors.Config{{
\t\tAllowOrigins: origins,
\t\tAllowMethods: []string{{"GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"}},
\t\tAllowHeaders: []string{{"Authorization", "Content-Type"}},
\t}}))

\tr.GET("/api/health", func(c *gin.Context) {{
\t\tc.JSON(200, gin.H{{"status": "healthy"}})
\t}})
\tr.GET("/api/ping", func(c *gin.Context) {{
\t\tc.JSON(200, gin.H{{"pong": true}})
\t}})

\tregisterItemRoutes(r)

\tlog.Printf("Listening on :%s", port)
\tif err := r.Run(":" + port); err != nil {{
\t\tlog.Fatalf("listen: %v", err)
\t}}
}}
'''

    files["db.go"] = '''package main

import (
	"context"
	"errors"
	"os"

	"github.com/jackc/pgx/v5/pgxpool"
)

var pool *pgxpool.Pool

func initPool(ctx context.Context) error {
	url := os.Getenv("DATABASE_URL")
	if url == "" {
		return errors.New("DATABASE_URL not set")
	}
	p, err := pgxpool.New(ctx, url)
	if err != nil {
		return err
	}
	pool = p
	return nil
}

func closePool() {
	if pool != nil {
		pool.Close()
	}
}
'''

    files["items.go"] = '''package main

import (
	"context"

	"github.com/gin-gonic/gin"
)

type Item struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type itemCreate struct {
	Name        string  `json:"name" binding:"required"`
	Description *string `json:"description"`
}

func registerItemRoutes(r *gin.Engine) {
	g := r.Group("/api/items")
	g.GET("", listItems)
	g.POST("", createItem)
	g.GET("/:id", getItem)
}

func listItems(c *gin.Context) {
	rows, err := pool.Query(context.Background(),
		"SELECT id, name, description FROM items ORDER BY id DESC LIMIT 100")
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}
	defer rows.Close()

	out := []Item{}
	for rows.Next() {
		var it Item
		if err := rows.Scan(&it.ID, &it.Name, &it.Description); err != nil {
			c.JSON(500, gin.H{"error": err.Error()})
			return
		}
		out = append(out, it)
	}
	c.JSON(200, out)
}

func createItem(c *gin.Context) {
	var body itemCreate
	if err := c.ShouldBindJSON(&body); err != nil {
		c.JSON(422, gin.H{"error": err.Error()})
		return
	}
	var it Item
	err := pool.QueryRow(context.Background(),
		"INSERT INTO items (name, description) VALUES ($1, $2) RETURNING id, name, description",
		body.Name, body.Description).Scan(&it.ID, &it.Name, &it.Description)
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}
	c.JSON(201, it)
}

func getItem(c *gin.Context) {
	var it Item
	err := pool.QueryRow(context.Background(),
		"SELECT id, name, description FROM items WHERE id = $1",
		c.Param("id")).Scan(&it.ID, &it.Name, &it.Description)
	if err != nil {
		c.JSON(404, gin.H{"error": "Not found"})
		return
	}
	c.JSON(200, it)
}
'''

    files["migrations/001_init.sql"] = '''CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_items_created ON items(created_at DESC);
'''

    files[".gitignore"] = """bin/
*.exe
.env
*.log
"""

    apply_addons(files, spec, "go_gin_postgres")
    return files


# ── Rails + Postgres ─────────────────────────────────────────────────


def _rails_postgres_summary() -> TemplateSummary:
    return TemplateSummary(
        template_id="rails_postgres",
        name="Rails + Postgres",
        short_description=(
            "Ruby on Rails 7 in API mode with Postgres. Convention over "
            "configuration, ActiveRecord, generators, and a 20-year ecosystem. "
            "Fastest path from idea to working CRUD."
        ),
        stack=["ruby", "rails", "postgres"],
        best_for=[
            "saas",
            "crud",
            "api",
            "internal tool",
            "monolith",
            "back office",
            "mvp",
        ],
    )


def _render_rails_postgres(spec: PlatformSpec) -> dict[str, str]:
    if not spec.project_name:
        raise ValueError("project_name is required to build this template")

    name = spec.project_name
    safe_name = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in name).lower()
    snake_name = safe_name.replace("-", "_")
    rails_module = "".join(p.capitalize() for p in snake_name.split("_") if p)
    description = spec.description or f"{name} — generated by NexusForge Platform Synthesizer"

    files: dict[str, str] = {}

    files["README.md"] = f"""# {name}

{description}

> Generated by NexusForge AI — Platform Synthesizer (Rails + Postgres template).

## Stack
- **Framework**: Rails 7 (API mode)
- **Language**: Ruby 3.2+
- **Database**: PostgreSQL 16
- **Server**: Puma

## Quick start

```bash
bundle install
cp .env.example .env  # edit DATABASE_URL
bin/rails db:create db:migrate
bin/rails s   # http://localhost:3000
```

Endpoints:
- `GET  /up` — Rails health probe
- `GET  /api/items` — list
- `POST /api/items` — create (`{{ "item": {{ "name": "...", "description": "..." }} }}`)
- `GET  /api/items/:id` — get one

## Project layout
- `config/application.rb` — Rails config
- `config/routes.rb` — URL → controller mapping
- `app/controllers/api/items_controller.rb` — CRUD
- `app/models/item.rb` — ActiveRecord model
- `db/migrate/` — schema migrations

## Next steps
1. Add your domain models: `bin/rails g model Foo name:string`
2. Run migration: `bin/rails db:migrate`
3. Generate a controller: `bin/rails g controller api/foos index show create`
"""

    files["Gemfile"] = """source 'https://rubygems.org'

ruby '~> 3.2'

gem 'rails', '~> 7.1'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'bootsnap', require: false
gem 'dotenv-rails', groups: [:development, :test]

group :development do
  gem 'listen'
end
"""

    files[".env.example"] = """DATABASE_URL=postgres://user:password@localhost:5432/dbname
RAILS_ENV=development
RAILS_LOG_LEVEL=info
RAILS_MAX_THREADS=5
SECRET_KEY_BASE=changeme-rails-secret-key-base-128-chars-or-more-and-random
"""

    files["config.ru"] = """require_relative "config/environment"

run Rails.application
Rails.application.load_server
"""

    files["Rakefile"] = """require_relative "config/application"

Rails.application.load_tasks
"""

    files["bin/rails"] = """#!/usr/bin/env ruby
APP_PATH = File.expand_path("../config/application", __dir__)
require_relative "../config/boot"
require "rails/commands"
"""

    files["bin/setup"] = """#!/usr/bin/env ruby
require "fileutils"

APP_ROOT = File.expand_path("..", __dir__)

FileUtils.chdir APP_ROOT do
  system!("bundle install")
  system!("bin/rails db:prepare")
end
"""

    files["config/boot.rb"] = """ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)

require "bundler/setup"
require "bootsnap/setup"
"""

    files["config/application.rb"] = f'''require_relative "boot"

require "rails"
require "active_model/railtie"
require "active_record/railtie"
require "action_controller/railtie"
require "action_view/railtie"

Bundler.require(*Rails.groups)

module {rails_module}
  class Application < Rails::Application
    config.load_defaults 7.1
    config.api_only = true
  end
end
'''

    files["config/environment.rb"] = """require_relative "application"

Rails.application.initialize!
"""

    files["config/database.yml"] = """default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
"""

    files["config/routes.rb"] = """Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :api do
    resources :items, only: [:index, :show, :create, :update, :destroy]
  end
end
"""

    files["config/puma.rb"] = """max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count

worker_timeout 3600 if ENV.fetch("RAILS_ENV", "development") == "development"

port ENV.fetch("PORT") { 3000 }
environment ENV.fetch("RAILS_ENV") { "development" }

pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }
plugin :tmp_restart
"""

    files["config/environments/development.rb"] = """require "active_support/core_ext/integer/time"

Rails.application.configure do
  config.cache_classes = false
  config.eager_load = false
  config.consider_all_requests_local = true
  config.server_timing = true
  config.active_record.migration_error = :page_load
  config.active_record.verbose_query_logs = true
  config.active_support.disallowed_deprecation = :raise
  config.active_support.disallowed_deprecation_warnings = []
end
"""

    files["config/environments/production.rb"] = """require "active_support/core_ext/integer/time"

Rails.application.configure do
  config.cache_classes = true
  config.eager_load = true
  config.consider_all_requests_local = false
  config.public_file_server.enabled = ENV["RAILS_SERVE_STATIC_FILES"].present?
  config.log_level = ENV.fetch("RAILS_LOG_LEVEL", "info").to_sym
  config.active_record.dump_schema_after_migration = false
  config.force_ssl = false
end
"""

    files["app/controllers/application_controller.rb"] = """class ApplicationController < ActionController::API
  rescue_from ActiveRecord::RecordNotFound do
    render json: { error: "Not found" }, status: :not_found
  end
end
"""

    files["app/controllers/api/items_controller.rb"] = """module Api
  class ItemsController < ApplicationController
    before_action :set_item, only: [:show, :update, :destroy]

    def index
      render json: Item.order(created_at: :desc).limit(100)
    end

    def show
      render json: @item
    end

    def create
      item = Item.new(item_params)
      if item.save
        render json: item, status: :created
      else
        render json: { errors: item.errors }, status: :unprocessable_entity
      end
    end

    def update
      if @item.update(item_params)
        render json: @item
      else
        render json: { errors: @item.errors }, status: :unprocessable_entity
      end
    end

    def destroy
      @item.destroy
      head :no_content
    end

    private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :description)
    end
  end
end
"""

    files["app/models/application_record.rb"] = """class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end
"""

    files["app/models/item.rb"] = """class Item < ApplicationRecord
  validates :name, presence: true, length: { maximum: 200 }
end
"""

    files["db/migrate/20260101000000_create_items.rb"] = """class CreateItems < ActiveRecord::Migration[7.1]
  def change
    create_table :items do |t|
      t.string :name, null: false, limit: 200
      t.text :description
      t.timestamps
    end

    add_index :items, :created_at, order: :desc
  end
end
"""

    files[".gitignore"] = """*.log
*.sqlite3
*.sqlite3-journal
/.bundle
/log/*
/tmp/*
!/log/.keep
!/tmp/.keep
/storage/*
!/storage/.keep
.env
.env.local
"""

    files["log/.keep"] = ""
    files["tmp/.keep"] = ""

    apply_addons(files, spec, "rails_postgres")
    return files


# ── Phoenix + Postgres ───────────────────────────────────────────────


def _phoenix_postgres_summary() -> TemplateSummary:
    return TemplateSummary(
        template_id="phoenix_postgres",
        name="Phoenix + Postgres",
        short_description=(
            "Elixir + Phoenix 1.7 with Ecto/Postgres. Erlang/BEAM concurrency, "
            "tiny memory footprint, soft real-time. Best for high-concurrency "
            "APIs and channels (websockets/PubSub built-in)."
        ),
        stack=["elixir", "phoenix", "postgres"],
        best_for=[
            "api",
            "real-time",
            "websocket",
            "chat",
            "high concurrency",
            "low latency",
            "fault tolerant",
        ],
    )


def _render_phoenix_postgres(spec: PlatformSpec) -> dict[str, str]:
    if not spec.project_name:
        raise ValueError("project_name is required to build this template")

    name = spec.project_name
    safe_name = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in name).lower()
    snake_name = safe_name.replace("-", "_")
    module_name = "".join(p.capitalize() for p in snake_name.split("_"))
    description = spec.description or f"{name} — generated by NexusForge Platform Synthesizer"

    files: dict[str, str] = {}

    files["README.md"] = f"""# {name}

{description}

> Generated by NexusForge AI — Platform Synthesizer (Phoenix + Postgres template).

## Stack
- **Language**: Elixir 1.16+ on Erlang/OTP 26+
- **Framework**: Phoenix 1.7 (API mode, no LiveView/HTML by default)
- **Database**: PostgreSQL 16 via Ecto
- **Server**: Bandit (HTTP/2 + WebSockets)

## Quick start

```bash
mix deps.get
cp .env.example .env  # edit DATABASE_URL
mix ecto.create
mix ecto.migrate
mix phx.server   # http://localhost:4000
```

Endpoints:
- `GET  /api/health` — liveness
- `GET  /api/items` — list
- `POST /api/items` — create (`{{ "item": {{ "name": "...", "description": "..." }} }}`)
- `GET  /api/items/:id` — get one

## Project layout
- `mix.exs` — deps + project metadata
- `config/` — environment-driven config
- `lib/{snake_name}/application.ex` — supervision tree
- `lib/{snake_name}/items.ex` — domain context (Ecto queries)
- `lib/{snake_name}_web/router.ex` — URL routes
- `lib/{snake_name}_web/controllers/item_controller.ex` — HTTP handlers
- `priv/repo/migrations/` — schema migrations

## Next steps
1. Add a context: `mix phx.gen.json Posts Post posts title:string body:text`
2. Run migration: `mix ecto.migrate`
3. Add the resource to `lib/{snake_name}_web/router.ex`
"""

    files["mix.exs"] = f'''defmodule {module_name}.MixProject do
  use Mix.Project

  def project do
    [
      app: :{snake_name},
      version: "0.1.0",
      elixir: "~> 1.16",
      elixirc_paths: elixirc_paths(Mix.env()),
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  def application do
    [
      mod: {{{module_name}.Application, []}},
      extra_applications: [:logger, :runtime_tools]
    ]
  end

  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_), do: ["lib"]

  defp deps do
    [
      {{:phoenix, "~> 1.7.10"}},
      {{:phoenix_ecto, "~> 4.4"}},
      {{:ecto_sql, "~> 3.10"}},
      {{:postgrex, ">= 0.0.0"}},
      {{:phoenix_html, "~> 4.0"}},
      {{:jason, "~> 1.2"}},
      {{:bandit, "~> 1.2"}},
      {{:plug_cowboy, "~> 2.5"}},
      {{:dotenvy, "~> 0.8"}}
    ]
  end
end
'''

    files[".env.example"] = """DATABASE_URL=postgres://user:password@localhost:5432/dbname
SECRET_KEY_BASE=changeme-phoenix-secret-key-base-64-chars-or-more-and-random-aaaaaa
PORT=4000
PHX_HOST=localhost
"""

    files["config/config.exs"] = f'''import Config

config :{snake_name},
  ecto_repos: [{module_name}.Repo],
  generators: [timestamp_type: :utc_datetime]

config :{snake_name}, {module_name}Web.Endpoint,
  url: [host: "localhost"],
  adapter: Bandit.PhoenixAdapter,
  render_errors: [
    formats: [json: {module_name}Web.ErrorJSON],
    layout: false
  ],
  pubsub_server: {module_name}.PubSub

config :logger, :console,
  format: "$time $metadata[$level] $message\\n",
  metadata: [:request_id]

config :phoenix, :json_library, Jason

import_config "#{{config_env()}}.exs"
'''

    files["config/dev.exs"] = f'''import Config

config :{snake_name}, {module_name}.Repo,
  url: System.get_env("DATABASE_URL") || "postgres://postgres:postgres@localhost:5432/{snake_name}_dev",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :{snake_name}, {module_name}Web.Endpoint,
  http: [ip: {{0, 0, 0, 0}}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: System.get_env("SECRET_KEY_BASE") || "dev-secret-key-base-must-be-at-least-64-chars-aaaaaaaaaaaaaaaaaaaaaaa",
  watchers: []

config :logger, :console, format: "[$level] $message\\n"
config :phoenix, :stacktrace_depth, 20
config :phoenix, :plug_init_mode, :runtime
'''

    files["config/prod.exs"] = f'''import Config

config :{snake_name}, {module_name}Web.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :logger, level: :info
'''

    files["config/runtime.exs"] = f'''import Config

if config_env() == :prod do
  database_url = System.get_env("DATABASE_URL") || raise "DATABASE_URL not set"
  config :{snake_name}, {module_name}.Repo,
    url: database_url,
    pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")

  secret_key_base = System.get_env("SECRET_KEY_BASE") || raise "SECRET_KEY_BASE not set"
  port = String.to_integer(System.get_env("PORT") || "4000")
  host = System.get_env("PHX_HOST") || "example.com"

  config :{snake_name}, {module_name}Web.Endpoint,
    url: [host: host, port: 443, scheme: "https"],
    http: [ip: {{0, 0, 0, 0, 0, 0, 0, 0}}, port: port],
    secret_key_base: secret_key_base
end
'''

    files["config/test.exs"] = f'''import Config

config :{snake_name}, {module_name}.Repo,
  url: System.get_env("DATABASE_URL") || "postgres://postgres:postgres@localhost:5432/{snake_name}_test",
  pool: Ecto.Adapters.SQL.Sandbox,
  pool_size: 10

config :{snake_name}, {module_name}Web.Endpoint,
  http: [ip: {{127, 0, 0, 1}}, port: 4002],
  secret_key_base: "test-secret-key-base-must-be-at-least-64-chars-aaaaaaaaaaaaaaaaaaaaa",
  server: false

config :logger, level: :warning
config :phoenix, :plug_init_mode, :runtime
'''

    files[f"lib/{snake_name}.ex"] = f'''defmodule {module_name} do
  @moduledoc """
  {description}

  Top-level module — domain code lives in submodules under
  `{module_name}.*` (e.g., `{module_name}.Items`).
  """
end
'''

    files[f"lib/{snake_name}/application.ex"] = f'''defmodule {module_name}.Application do
  @moduledoc false
  use Application

  @impl true
  def start(_type, _args) do
    children = [
      {module_name}.Repo,
      {{Phoenix.PubSub, name: {module_name}.PubSub}},
      {module_name}Web.Endpoint
    ]

    opts = [strategy: :one_for_one, name: {module_name}.Supervisor]
    Supervisor.start_link(children, opts)
  end

  @impl true
  def config_change(changed, _new, removed) do
    {module_name}Web.Endpoint.config_change(changed, removed)
    :ok
  end
end
'''

    files[f"lib/{snake_name}/repo.ex"] = f'''defmodule {module_name}.Repo do
  use Ecto.Repo,
    otp_app: :{snake_name},
    adapter: Ecto.Adapters.Postgres
end
'''

    files[f"lib/{snake_name}/items.ex"] = f'''defmodule {module_name}.Items do
  @moduledoc """
  Items context — domain logic + Ecto queries for the `items` table.
  """
  import Ecto.Query, warn: false
  alias {module_name}.Repo
  alias {module_name}.Items.Item

  def list_items, do: Repo.all(from i in Item, order_by: [desc: i.inserted_at], limit: 100)

  def get_item!(id), do: Repo.get!(Item, id)

  def create_item(attrs \\\\ %{{}}) do
    %Item{{}}
    |> Item.changeset(attrs)
    |> Repo.insert()
  end

  def update_item(%Item{{}} = item, attrs) do
    item
    |> Item.changeset(attrs)
    |> Repo.update()
  end

  def delete_item(%Item{{}} = item), do: Repo.delete(item)
end
'''

    files[f"lib/{snake_name}/items/item.ex"] = f'''defmodule {module_name}.Items.Item do
  use Ecto.Schema
  import Ecto.Changeset

  schema "items" do
    field :name, :string
    field :description, :string
    timestamps(type: :utc_datetime)
  end

  def changeset(item, attrs) do
    item
    |> cast(attrs, [:name, :description])
    |> validate_required([:name])
    |> validate_length(:name, max: 200)
  end
end
'''

    files[f"lib/{snake_name}_web/endpoint.ex"] = f'''defmodule {module_name}Web.Endpoint do
  use Phoenix.Endpoint, otp_app: :{snake_name}

  @session_options [
    store: :cookie,
    key: "_{snake_name}_key",
    signing_salt: "changeme-signing-salt",
    same_site: "Lax"
  ]

  socket "/socket", {module_name}Web.UserSocket,
    websocket: true,
    longpoll: false

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug {module_name}Web.Router
end
'''

    files[f"lib/{snake_name}_web/router.ex"] = f'''defmodule {module_name}Web.Router do
  use Phoenix.Router

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", {module_name}Web do
    pipe_through :api
    get "/health", HealthController, :show
    resources "/items", ItemController, except: [:new, :edit]
  end
end
'''

    files[f"lib/{snake_name}_web/controllers/health_controller.ex"] = f'''defmodule {module_name}Web.HealthController do
  use Phoenix.Controller, formats: [:json]

  def show(conn, _params) do
    json(conn, %{{status: "healthy"}})
  end
end
'''

    files[f"lib/{snake_name}_web/controllers/item_controller.ex"] = f'''defmodule {module_name}Web.ItemController do
  use Phoenix.Controller, formats: [:json]
  alias {module_name}.Items
  alias {module_name}.Items.Item

  action_fallback {module_name}Web.FallbackController

  def index(conn, _params) do
    items = Items.list_items()
    json(conn, Enum.map(items, &item_to_map/1))
  end

  def show(conn, %{{"id" => id}}) do
    item = Items.get_item!(id)
    json(conn, item_to_map(item))
  end

  def create(conn, %{{"item" => params}}) do
    with {{:ok, %Item{{}} = item}} <- Items.create_item(params) do
      conn |> put_status(:created) |> json(item_to_map(item))
    end
  end

  def update(conn, %{{"id" => id, "item" => params}}) do
    item = Items.get_item!(id)
    with {{:ok, %Item{{}} = updated}} <- Items.update_item(item, params) do
      json(conn, item_to_map(updated))
    end
  end

  def delete(conn, %{{"id" => id}}) do
    item = Items.get_item!(id)
    {{:ok, _}} = Items.delete_item(item)
    send_resp(conn, :no_content, "")
  end

  defp item_to_map(%Item{{}} = i) do
    %{{id: i.id, name: i.name, description: i.description, inserted_at: i.inserted_at}}
  end
end
'''

    files[f"lib/{snake_name}_web/controllers/fallback_controller.ex"] = f'''defmodule {module_name}Web.FallbackController do
  use Phoenix.Controller, formats: [:json]

  def call(conn, {{:error, %Ecto.Changeset{{}} = changeset}}) do
    conn
    |> put_status(:unprocessable_entity)
    |> json(%{{errors: translate_errors(changeset)}})
  end

  def call(conn, {{:error, :not_found}}) do
    conn |> put_status(:not_found) |> json(%{{error: "Not found"}})
  end

  defp translate_errors(changeset) do
    Ecto.Changeset.traverse_errors(changeset, fn {{msg, opts}} ->
      Enum.reduce(opts, msg, fn {{k, v}}, acc -> String.replace(acc, "%{{#{{k}}}}", to_string(v)) end)
    end)
  end
end
'''

    files[f"lib/{snake_name}_web/controllers/error_json.ex"] = f'''defmodule {module_name}Web.ErrorJSON do
  def render(template, _assigns) do
    %{{errors: %{{detail: Phoenix.Controller.status_message_from_template(template)}}}}
  end
end
'''

    files[f"lib/{snake_name}_web/channels/user_socket.ex"] = f'''defmodule {module_name}Web.UserSocket do
  use Phoenix.Socket

  @impl true
  def connect(_params, socket, _connect_info), do: {{:ok, socket}}

  @impl true
  def id(_socket), do: nil
end
'''

    files["priv/repo/migrations/20260101000000_create_items.exs"] = f'''defmodule {module_name}.Repo.Migrations.CreateItems do
  use Ecto.Migration

  def change do
    create table(:items) do
      add :name, :string, null: false, size: 200
      add :description, :text
      timestamps(type: :utc_datetime)
    end

    create index(:items, [:inserted_at])
  end
end
'''

    files[".gitignore"] = """/_build/
/cover/
/deps/
/doc/
/.fetch
erl_crash.dump
*.ez
/priv/static/
/tmp/
.env
.env.local
.elixir_ls/
"""

    apply_addons(files, spec, "phoenix_postgres")
    return files


# ── Spring Boot + Postgres ──────────────────────────────────────────


def _spring_boot_postgres_summary() -> TemplateSummary:
    return TemplateSummary(
        template_id="spring_boot_postgres",
        name="Spring Boot + Postgres",
        short_description=(
            "Java 21 + Spring Boot 3 + Spring Data JPA + Postgres. The "
            "enterprise-grade JVM stack — strong typing, mature tooling, and "
            "the choice for orgs already on the JVM ecosystem."
        ),
        stack=["java", "spring", "postgres"],
        best_for=[
            "enterprise",
            "saas",
            "api",
            "back office",
            "monolith",
            "jvm",
            "compliance",
        ],
    )


def _render_spring_boot_postgres(spec: PlatformSpec) -> dict[str, str]:
    if not spec.project_name:
        raise ValueError("project_name is required to build this template")

    name = spec.project_name
    safe_name = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in name).lower()
    artifact_id = safe_name
    pkg_segment = safe_name.replace("-", "").replace("_", "")
    pkg = f"com.example.{pkg_segment}"
    pkg_path = pkg.replace(".", "/")
    description = spec.description or f"{name} — generated by NexusForge Platform Synthesizer"
    main_class = "".join(p.capitalize() for p in safe_name.replace("_", "-").split("-")) + "Application"

    files: dict[str, str] = {}

    files["README.md"] = f"""# {name}

{description}

> Generated by NexusForge AI — Platform Synthesizer (Spring Boot + Postgres template).

## Stack
- **Language**: Java 21
- **Framework**: Spring Boot 3.3 + Spring Web + Spring Data JPA
- **Database**: PostgreSQL 16
- **Build tool**: Gradle (Kotlin DSL)

## Quick start

```bash
cp .env.example .env  # edit DATABASE_URL or use SPRING_DATASOURCE_*
./gradlew bootRun     # http://localhost:8080
```

The app reads `SPRING_DATASOURCE_URL` (jdbc style) — `.env.example` shows
how to derive it from a standard `postgres://` URL.

Endpoints:
- `GET  /api/health` — liveness
- `GET  /api/items` — list
- `POST /api/items` — create (`{{ "name": "...", "description": "..." }}`)
- `GET  /api/items/{{id}}` — get one
- `DELETE /api/items/{{id}}` — delete

## Project layout
- `build.gradle.kts` — deps + plugins
- `src/main/java/{pkg_path}/{main_class}.java` — entry
- `src/main/java/{pkg_path}/items/` — domain (Entity / Repository / Controller)
- `src/main/resources/application.yaml` — config
- `src/main/resources/db/migration/` — Flyway migrations

## Next steps
1. Set `SPRING_DATASOURCE_URL`, `SPRING_DATASOURCE_USERNAME`, `SPRING_DATASOURCE_PASSWORD`
2. Run: `./gradlew flywayMigrate` (or let app auto-migrate on first boot)
3. Add a domain: copy `items/` and adjust the table name + fields
"""

    files["build.gradle.kts"] = f'''plugins {{
    java
    id("org.springframework.boot") version "3.3.0"
    id("io.spring.dependency-management") version "1.1.4"
    id("org.flywaydb.flyway") version "10.10.0"
}}

group = "com.example"
version = "0.1.0"

java {{
    toolchain {{
        languageVersion.set(JavaLanguageVersion.of(21))
    }}
}}

repositories {{
    mavenCentral()
}}

dependencies {{
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.flywaydb:flyway-core")
    implementation("org.flywaydb:flyway-database-postgresql")
    runtimeOnly("org.postgresql:postgresql")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}}

tasks.withType<Test> {{
    useJUnitPlatform()
}}
'''

    files["settings.gradle.kts"] = f'''rootProject.name = "{artifact_id}"
'''

    files["gradle.properties"] = """org.gradle.jvmargs=-Xmx2g
org.gradle.parallel=true
"""

    files[".env.example"] = """# Spring expects JDBC-style URLs:
SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/dbname
SPRING_DATASOURCE_USERNAME=user
SPRING_DATASOURCE_PASSWORD=password

# Optional runtime overrides
SERVER_PORT=8080
"""

    files["src/main/resources/application.yaml"] = """spring:
  application:
    name: ${SPRING_APPLICATION_NAME:app}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
"""

    files["src/main/resources/db/migration/V1__init.sql"] = """CREATE TABLE IF NOT EXISTS items (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_items_created ON items(created_at DESC);
"""

    files[f"src/main/java/{pkg_path}/{main_class}.java"] = f'''package {pkg};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class {main_class} {{
    public static void main(String[] args) {{
        SpringApplication.run({main_class}.class, args);
    }}
}}
'''

    files[f"src/main/java/{pkg_path}/health/HealthController.java"] = f'''package {pkg}.health;

import java.util.Map;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api")
public class HealthController {{
    @GetMapping("/health")
    public Map<String, String> health() {{
        return Map.of("status", "healthy");
    }}
}}
'''

    files[f"src/main/java/{pkg_path}/items/Item.java"] = f'''package {pkg}.items;

import java.time.OffsetDateTime;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

@Entity
@Table(name = "items")
public class Item {{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank
    @Size(max = 200)
    @Column(nullable = false, length = 200)
    private String name;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt = OffsetDateTime.now();

    public Long getId() {{ return id; }}
    public String getName() {{ return name; }}
    public void setName(String name) {{ this.name = name; }}
    public String getDescription() {{ return description; }}
    public void setDescription(String description) {{ this.description = description; }}
    public OffsetDateTime getCreatedAt() {{ return createdAt; }}
}}
'''

    files[f"src/main/java/{pkg_path}/items/ItemRepository.java"] = f'''package {pkg}.items;

import org.springframework.data.jpa.repository.JpaRepository;

public interface ItemRepository extends JpaRepository<Item, Long> {{
}}
'''

    files[f"src/main/java/{pkg_path}/items/ItemController.java"] = f'''package {pkg}.items;

import java.util.List;

import jakarta.validation.Valid;

import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/items")
public class ItemController {{
    private final ItemRepository repo;

    public ItemController(ItemRepository repo) {{
        this.repo = repo;
    }}

    @GetMapping
    public List<Item> list() {{
        return repo.findAll(
            PageRequest.of(0, 100, Sort.by(Sort.Direction.DESC, "createdAt"))
        ).getContent();
    }}

    @GetMapping("/{{id}}")
    public ResponseEntity<Item> get(@PathVariable Long id) {{
        return repo.findById(id)
            .map(ResponseEntity::ok)
            .orElse(ResponseEntity.notFound().build());
    }}

    @PostMapping
    public ResponseEntity<Item> create(@Valid @RequestBody Item input) {{
        Item saved = repo.save(input);
        return ResponseEntity.status(201).body(saved);
    }}

    @DeleteMapping("/{{id}}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {{
        if (!repo.existsById(id)) return ResponseEntity.notFound().build();
        repo.deleteById(id);
        return ResponseEntity.noContent().build();
    }}
}}
'''

    files[".gitignore"] = """.gradle/
build/
out/
*.class
.idea/
*.iml
.env
.env.local
"""

    apply_addons(files, spec, "spring_boot_postgres")
    return files


# ── Registry ────────────────────────────────────────────────────────


# Keyed by template_id. Each value is (summary, render_fn).
_REGISTRY: dict[str, tuple[TemplateSummary, Callable[[PlatformSpec], dict[str, str]]]] = {
    "fastapi_react_postgres": (
        _fastapi_react_postgres_summary(),
        _render_fastapi_react_postgres,
    ),
    "express_next_postgres": (
        _express_next_postgres_summary(),
        _render_express_next_postgres,
    ),
    "django_postgres": (
        _django_postgres_summary(),
        _render_django_postgres,
    ),
    "go_gin_postgres": (
        _go_gin_postgres_summary(),
        _render_go_gin_postgres,
    ),
    "rails_postgres": (
        _rails_postgres_summary(),
        _render_rails_postgres,
    ),
    "phoenix_postgres": (
        _phoenix_postgres_summary(),
        _render_phoenix_postgres,
    ),
    "spring_boot_postgres": (
        _spring_boot_postgres_summary(),
        _render_spring_boot_postgres,
    ),
}


def list_templates() -> list[TemplateSummary]:
    """Return all registered template summaries."""
    return [summary for summary, _ in _REGISTRY.values()]


def get_template(template_id: str) -> tuple[TemplateSummary, Callable[[PlatformSpec], dict[str, str]]]:
    """Look up a template by id. Raises KeyError if not found."""
    return _REGISTRY[template_id]


def rank_for_spec(spec: PlatformSpec) -> list[TemplateMatch]:
    """Score every template against the spec and return them sorted
    by score descending. Templates with score == 0 are still
    included so the frontend can show "incompatible" state."""
    matches: list[TemplateMatch] = []
    for summary, _render in _REGISTRY.values():
        score, signals = _score_against(summary, spec)
        matches.append(TemplateMatch(template=summary, score=score, matched_signals=signals))
    matches.sort(key=lambda m: m.score, reverse=True)
    return matches
