"""Template registry for the Platform Synthesizer.

A template is a curated, tested project skeleton with a known
stack. It declares which `PlatformSpec` slots it can absorb, what
its required slots are, and its scoring signals (which spec values
make it a good match).

The first iteration ships ONE template: FastAPI + React + Postgres.
That's the stack Christian uses himself, the most-tested combo in
NexusForge, and the easiest to verify end-to-end. Adding more
templates is purely additive — register a new one in `_REGISTRY`
and add a `_render_*` function below.

Each template's `_render` function is responsible for:
  1. Emitting the file tree as a dict {relative_path: content_str}
  2. Substituting spec slot values into the file contents
  3. Validating that all required slots are filled before render

The synthesizer module writes the dict to disk.
"""
from __future__ import annotations

from typing import Callable

from .schemas import PlatformSpec, TemplateMatch, TemplateSummary


# ── scoring helpers ─────────────────────────────────────────────────


def _score_against(template: TemplateSummary, spec: PlatformSpec) -> tuple[float, list[str]]:
    """Score a template against the user's accumulated spec.

    Returns (score in [0,1], list of matched-signal strings for
    the debug panel). Each signal that lines up adds a fixed
    weight; the final score is normalized.
    """
    signals: list[str] = []
    score = 0.0

    # If the user picked an explicit language, the template MUST
    # match or it scores zero. Same for backend framework.
    if spec.language and spec.language not in {s.lower() for s in template.stack}:
        return 0.0, [f"language mismatch: spec={spec.language}, template={template.stack}"]

    # Stack overlaps: strong signal.
    template_stack_lower = {s.lower() for s in template.stack}
    if spec.backend_framework and spec.backend_framework.lower() in template_stack_lower:
        score += 0.30
        signals.append(f"backend framework matches: {spec.backend_framework}")
    if spec.frontend_framework and spec.frontend_framework.lower() in template_stack_lower:
        score += 0.20
        signals.append(f"frontend framework matches: {spec.frontend_framework}")
    if spec.database and spec.database.lower() in template_stack_lower:
        score += 0.15
        signals.append(f"database matches: {spec.database}")

    # `best_for` matches: each phrase in best_for that appears in
    # the user's description or features adds 0.10.
    haystack = " ".join(
        [
            (spec.description or "").lower(),
            *[f.lower() for f in spec.features],
            *[i.lower() for i in spec.integrations],
        ]
    )
    for phrase in template.best_for:
        if phrase.lower() in haystack:
            score += 0.10
            signals.append(f"use-case match: {phrase!r}")

    # Floor: every COMPATIBLE template (i.e., didn't fail the
    # hard language-mismatch check above) gets a baseline score of
    # 0.10 so the UI doesn't render "0%" across the board on a
    # bare spec — that looks broken. As the user describes more,
    # signals lift each template above the floor at different
    # rates, and the ordering becomes meaningful.
    if score < 0.10:
        score = 0.10
        if not signals:
            signals.append("compatible (no specific signals matched yet)")

    # Cap at 1.0.
    return min(score, 1.0), signals


# ── template implementations ────────────────────────────────────────


def _fastapi_react_postgres_summary() -> TemplateSummary:
    return TemplateSummary(
        template_id="fastapi_react_postgres",
        name="FastAPI + React + Postgres",
        short_description=(
            "Production-ready Python backend with FastAPI, React frontend "
            "with Vite, Postgres for persistence. JWT auth optional. "
            "The stack NexusForge itself runs on."
        ),
        stack=["python", "fastapi", "react", "vite", "postgres"],
        best_for=[
            "saas",
            "dashboard",
            "internal tool",
            "api",
            "automation",
            "ai",
            "data",
            "agents",
        ],
    )


def _render_fastapi_react_postgres(spec: PlatformSpec) -> dict[str, str]:
    """Emit the file tree for the FastAPI + React + Postgres template.

    Required slots: project_name. Everything else has sensible
    defaults so the user can run it immediately and refine later.
    """
    if not spec.project_name:
        raise ValueError("project_name is required to build this template")

    name = spec.project_name
    safe_name = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in name).lower()
    description = spec.description or f"{name} — generated by NexusForge Platform Synthesizer"
    auth = spec.auth or "jwt"
    features_md = (
        "\n".join(f"- {f}" for f in spec.features) if spec.features else "- (no features yet — describe more in chat to refine)"
    )
    integrations_md = (
        "\n".join(f"- {i}" for i in spec.integrations) if spec.integrations else "- (none yet)"
    )

    files: dict[str, str] = {}

    # ── README ──
    files["README.md"] = f"""# {name}

{description}

> Generated by NexusForge AI — Platform Synthesizer (FastAPI + React + Postgres template).

## Stack
- **Backend**: Python 3.12 + FastAPI
- **Frontend**: React 18 + Vite
- **Database**: PostgreSQL 16
- **Auth**: {auth}

## Features
{features_md}

## Integrations
{integrations_md}

## Quick start

```bash
# Backend
cd backend
python -m venv .venv && source .venv/bin/activate  # or .venv\\Scripts\\activate on Windows
pip install -r requirements.txt
cp .env.example .env  # then edit DATABASE_URL
uvicorn app.main:app --reload

# Frontend (separate shell)
cd frontend
npm install
npm run dev
```

The backend listens on `http://localhost:8000`, the frontend on `http://localhost:5173`.
The frontend's `VITE_API_URL` points at `http://localhost:8000/api` by default.

## Project layout
- `backend/app/main.py` — FastAPI entry, CORS, lifespan
- `backend/app/routes/` — HTTP handlers
- `backend/app/db/` — Postgres connection + migrations
- `frontend/src/` — React UI
- `frontend/src/services/api.js` — fetch wrapper

## Next steps after generation
1. Set `DATABASE_URL` in `backend/.env`
2. Run the SQL in `backend/app/db/migrations/001_init.sql` against your Postgres
3. Generate a JWT secret: `python -c "import secrets; print(secrets.token_urlsafe(48))"` and put it in `JWT_SECRET`
4. Replace the stub endpoints in `backend/app/routes/items.py` with your real domain
"""

    # ── Backend ──
    files["backend/requirements.txt"] = """fastapi==0.115.0
uvicorn[standard]==0.30.0
pydantic>=2.10.0,<3.0.0
pydantic-settings>=2.5.0,<3.0.0
asyncpg==0.29.0
python-multipart==0.0.9
PyJWT>=2.8.0,<3.0.0
bcrypt>=4.1.0,<5.0.0
"""

    files["backend/.env.example"] = """# Postgres connection — same shape as on Render / Supabase / local docker
DATABASE_URL=postgres://user:password@localhost:5432/dbname

# JWT signing secret (generate with: python -c "import secrets; print(secrets.token_urlsafe(48))")
JWT_SECRET=changeme-in-production-use-token-urlsafe-48

# CORS allowlist for browser callers (comma-separated)
ALLOWED_ORIGINS=http://localhost:5173
"""

    files["backend/app/__init__.py"] = ""

    files["backend/app/main.py"] = f'''"""FastAPI entry for {name}.

Generated by NexusForge AI Platform Synthesizer.
"""
import os
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.routes.health import router as health_router
from app.routes.items import router as items_router
from app.routes.auth import router as auth_router
from app.db.client import get_pool, close_pool


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Eager-warm the pool so the first request doesn't pay the latency.
    try:
        await get_pool()
    except Exception as exc:
        print(f"Warning: DB pool not warmed at startup: {{exc}}")
    yield
    await close_pool()


app = FastAPI(title="{name}", lifespan=lifespan)

origins = [o.strip() for o in os.environ.get("ALLOWED_ORIGINS", "*").split(",") if o.strip()]
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=False,
    allow_methods=["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
    allow_headers=["Authorization", "Content-Type"],
)

app.include_router(health_router, prefix="/api", tags=["health"])
app.include_router(auth_router, prefix="/api/auth", tags=["auth"])
app.include_router(items_router, prefix="/api/items", tags=["items"])
'''

    files["backend/app/routes/__init__.py"] = ""

    files["backend/app/routes/health.py"] = '''"""Liveness + readiness probes."""
from fastapi import APIRouter

router = APIRouter()


@router.get("/health")
async def health():
    return {"status": "healthy"}


@router.get("/ping")
async def ping():
    return {"pong": True}
'''

    files["backend/app/routes/auth.py"] = f'''"""Stub JWT auth.

Generated baseline — replace with your real user store.
"""
import os
import time

import jwt
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

router = APIRouter()
JWT_SECRET = os.environ.get("JWT_SECRET", "")


class LoginRequest(BaseModel):
    email: str
    password: str


@router.post("/login")
async def login(body: LoginRequest):
    """Stub: accepts any email + password=demo for now.

    Replace with a real lookup against your users table.
    """
    if body.password != "demo":
        raise HTTPException(401, "Invalid credentials")
    if not JWT_SECRET:
        raise HTTPException(500, "JWT_SECRET not configured")
    payload = {{
        "sub": body.email,
        "iat": int(time.time()),
        "exp": int(time.time()) + 8 * 3600,
    }}
    token = jwt.encode(payload, JWT_SECRET, algorithm="HS256")
    return {{"token": token}}
'''

    files["backend/app/routes/items.py"] = '''"""Items CRUD — example domain you'll replace."""
from uuid import UUID

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from app.db.client import get_pool

router = APIRouter()


class ItemCreate(BaseModel):
    name: str
    description: str | None = None


@router.get("/")
async def list_items():
    pool = await get_pool()
    async with pool.acquire() as conn:
        rows = await conn.fetch("SELECT id, name, description FROM items ORDER BY id DESC LIMIT 100")
    return [{"id": str(r["id"]), "name": r["name"], "description": r["description"]} for r in rows]


@router.post("/", status_code=201)
async def create_item(body: ItemCreate):
    pool = await get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "INSERT INTO items (name, description) VALUES ($1, $2) RETURNING id, name, description",
            body.name, body.description,
        )
    return {"id": str(row["id"]), "name": row["name"], "description": row["description"]}


@router.get("/{item_id}")
async def get_item(item_id: UUID):
    pool = await get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow("SELECT id, name, description FROM items WHERE id = $1", item_id)
    if not row:
        raise HTTPException(404, "Item not found")
    return {"id": str(row["id"]), "name": row["name"], "description": row["description"]}
'''

    files["backend/app/db/__init__.py"] = ""

    files["backend/app/db/client.py"] = '''"""Asyncpg pool — warm once, share across requests."""
import os

import asyncpg

_pool: asyncpg.Pool | None = None


async def get_pool() -> asyncpg.Pool:
    global _pool
    if _pool is None:
        url = os.environ.get("DATABASE_URL")
        if not url:
            raise RuntimeError("DATABASE_URL not set")
        _pool = await asyncpg.create_pool(url, min_size=1, max_size=10)
    return _pool


async def close_pool() -> None:
    global _pool
    if _pool is not None:
        await _pool.close()
        _pool = None
'''

    files["backend/app/db/migrations/001_init.sql"] = '''-- Run this once against your Postgres before starting the app.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_items_created ON items(created_at DESC);
'''

    # ── Frontend ──
    files["frontend/package.json"] = f"""{{
  "name": "{safe_name}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "react": "^18.3.0",
    "react-dom": "^18.3.0",
    "react-router-dom": "^6.26.0"
  }},
  "devDependencies": {{
    "@vitejs/plugin-react": "^4.3.0",
    "vite": "^5.4.0"
  }}
}}
"""

    files["frontend/vite.config.js"] = """import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: { port: 5173 },
})
"""

    files["frontend/index.html"] = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
"""

    files["frontend/src/main.jsx"] = '''import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
'''

    files["frontend/src/App.jsx"] = f'''import {{ useEffect, useState }} from 'react'
import {{ fetchAPI }} from './services/api.js'

export default function App() {{
  const [items, setItems] = useState([])
  const [name, setName] = useState('')
  const [error, setError] = useState(null)

  useEffect(() => {{
    fetchAPI('/items/').then(res => {{
      if (res.error) setError(res.error)
      else setItems(res.data || [])
    }})
  }}, [])

  async function add() {{
    if (!name.trim()) return
    const res = await fetchAPI('/items/', {{
      method: 'POST',
      body: JSON.stringify({{ name }}),
    }})
    if (res.error) {{ setError(res.error); return }}
    setItems([res.data, ...items])
    setName('')
  }}

  return (
    <div style={{{{ fontFamily: 'system-ui', maxWidth: 720, margin: '40px auto', padding: 20 }}}}>
      <h1>{name}</h1>
      <p style={{{{ color: '#666' }}}}>{description}</p>
      <div style={{{{ display: 'flex', gap: 8, marginBottom: 20 }}}}>
        <input
          value={{name}}
          onChange={{e => setName(e.target.value)}}
          placeholder="New item name"
          style={{{{ flex: 1, padding: 8, border: '1px solid #ddd', borderRadius: 4 }}}}
        />
        <button onClick={{add}} style={{{{ padding: '8px 16px' }}}}>Add</button>
      </div>
      {{error && <p style={{{{ color: 'crimson' }}}}>{{error}}</p>}}
      <ul>
        {{items.map(it => (
          <li key={{it.id}}>{{it.name}}</li>
        ))}}
      </ul>
    </div>
  )
}}
'''

    files["frontend/src/services/api.js"] = '''const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000/api'

export async function fetchAPI(endpoint, options = {}) {
  try {
    const res = await fetch(`${API_URL}${endpoint}`, {
      ...options,
      headers: { 'Content-Type': 'application/json', ...(options.headers || {}) },
    })
    if (!res.ok) {
      let detail = `HTTP ${res.status}`
      try { const body = await res.json(); detail = body.detail || detail } catch {}
      return { data: null, error: detail }
    }
    return { data: await res.json(), error: null }
  } catch (err) {
    return { data: null, error: err.message }
  }
}
'''

    files[".gitignore"] = """# Python
__pycache__/
*.py[cod]
.venv/
*.egg-info/

# Node
node_modules/
dist/

# Env
.env
.env.local
"""

    return files


# ── registry ────────────────────────────────────────────────────────


# ── Express + Next.js + Postgres ────────────────────────────────────


def _express_next_postgres_summary() -> TemplateSummary:
    return TemplateSummary(
        template_id="express_next_postgres",
        name="Express + Next.js + Postgres",
        short_description=(
            "Modern Node-only stack. Express API in TypeScript, Next.js 14 "
            "frontend with the App Router, Postgres for persistence. Ideal "
            "when the team prefers JS/TS end-to-end."
        ),
        stack=["typescript", "javascript", "node", "express", "next", "postgres"],
        best_for=[
            "saas",
            "dashboard",
            "marketing site",
            "e-commerce",
            "auth",
            "blog",
            "ssr",
        ],
    )


def _render_express_next_postgres(spec: PlatformSpec) -> dict[str, str]:
    if not spec.project_name:
        raise ValueError("project_name is required to build this template")

    name = spec.project_name
    safe_name = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in name).lower()
    description = spec.description or f"{name} — generated by NexusForge Platform Synthesizer"
    features_md = (
        "\n".join(f"- {f}" for f in spec.features) if spec.features else "- (none yet)"
    )

    files: dict[str, str] = {}

    files["README.md"] = f"""# {name}

{description}

> Generated by NexusForge AI — Platform Synthesizer (Express + Next.js + Postgres template).

## Stack
- **Backend**: Node 20 + Express + TypeScript
- **Frontend**: Next.js 14 (App Router) + React 18
- **Database**: PostgreSQL 16
- **ORM**: `pg` (raw queries — swap to Prisma/Drizzle later if you want)

## Features
{features_md}

## Quick start

```bash
# Backend
cd backend
npm install
cp .env.example .env  # then edit DATABASE_URL
npm run dev   # http://localhost:8000

# Frontend (separate shell)
cd frontend
npm install
npm run dev   # http://localhost:3000
```

The frontend expects `NEXT_PUBLIC_API_URL=http://localhost:8000` (set in `frontend/.env.local`).

## Project layout
- `backend/src/index.ts` — Express entry, CORS, route mounting
- `backend/src/routes/items.ts` — CRUD example
- `backend/src/db.ts` — pg pool
- `frontend/app/page.tsx` — home (lists items, form to add)
- `frontend/lib/api.ts` — fetch wrapper

## Next steps
1. Set DATABASE_URL in `backend/.env`
2. Run `psql $DATABASE_URL -f backend/migrations/001_init.sql`
3. Replace the items example with your real domain
"""

    # ── Backend ──
    files["backend/package.json"] = f"""{{
  "name": "{safe_name}-backend",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "tsx watch src/index.ts",
    "build": "tsc",
    "start": "node dist/index.js"
  }},
  "dependencies": {{
    "cors": "^2.8.5",
    "dotenv": "^16.4.5",
    "express": "^4.21.0",
    "pg": "^8.13.0"
  }},
  "devDependencies": {{
    "@types/cors": "^2.8.17",
    "@types/express": "^5.0.0",
    "@types/node": "^22.7.0",
    "@types/pg": "^8.11.10",
    "tsx": "^4.19.0",
    "typescript": "^5.6.0"
  }}
}}
"""

    files["backend/tsconfig.json"] = """{
  "compilerOptions": {
    "target": "ES2022",
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "outDir": "dist",
    "declaration": false,
    "sourceMap": true
  },
  "include": ["src"]
}
"""

    files["backend/.env.example"] = """DATABASE_URL=postgres://user:password@localhost:5432/dbname
PORT=8000
ALLOWED_ORIGINS=http://localhost:3000
"""

    files["backend/src/index.ts"] = '''import "dotenv/config";
import express from "express";
import cors from "cors";

import { itemsRouter } from "./routes/items";
import { closePool } from "./db";

const app = express();
const PORT = Number(process.env.PORT || 8000);

const origins = (process.env.ALLOWED_ORIGINS || "*")
  .split(",")
  .map((o) => o.trim())
  .filter(Boolean);

app.use(cors({ origin: origins.includes("*") ? true : origins }));
app.use(express.json({ limit: "1mb" }));

app.get("/api/health", (_req, res) => {
  res.json({ status: "healthy" });
});

app.get("/api/ping", (_req, res) => {
  res.json({ pong: true });
});

app.use("/api/items", itemsRouter);

app.use((err: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
  console.error(err);
  res.status(500).json({ error: "Internal server error" });
});

const server = app.listen(PORT, () => {
  console.log(`Listening on :${PORT}`);
});

process.on("SIGTERM", async () => {
  server.close();
  await closePool();
  process.exit(0);
});
'''

    files["backend/src/db.ts"] = '''import { Pool } from "pg";

let pool: Pool | null = null;

export function getPool(): Pool {
  if (!pool) {
    const url = process.env.DATABASE_URL;
    if (!url) throw new Error("DATABASE_URL not set");
    pool = new Pool({ connectionString: url, max: 10 });
  }
  return pool;
}

export async function closePool(): Promise<void> {
  if (pool) {
    await pool.end();
    pool = null;
  }
}
'''

    files["backend/src/routes/items.ts"] = '''import { Router } from "express";
import { getPool } from "../db";

export const itemsRouter = Router();

itemsRouter.get("/", async (_req, res, next) => {
  try {
    const pool = getPool();
    const { rows } = await pool.query(
      "SELECT id, name, description FROM items ORDER BY id DESC LIMIT 100"
    );
    res.json(rows);
  } catch (e) {
    next(e);
  }
});

itemsRouter.post("/", async (req, res, next) => {
  try {
    const { name, description } = req.body || {};
    if (!name || typeof name !== "string") {
      return res.status(422).json({ error: "name required" });
    }
    const pool = getPool();
    const { rows } = await pool.query(
      "INSERT INTO items (name, description) VALUES ($1, $2) RETURNING id, name, description",
      [name, description || null]
    );
    res.status(201).json(rows[0]);
  } catch (e) {
    next(e);
  }
});

itemsRouter.get("/:id", async (req, res, next) => {
  try {
    const pool = getPool();
    const { rows } = await pool.query(
      "SELECT id, name, description FROM items WHERE id = $1",
      [req.params.id]
    );
    if (!rows.length) return res.status(404).json({ error: "Not found" });
    res.json(rows[0]);
  } catch (e) {
    next(e);
  }
});
'''

    files["backend/migrations/001_init.sql"] = '''CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_items_created ON items(created_at DESC);
'''

    # ── Frontend (Next.js 14 App Router) ──
    files["frontend/package.json"] = f"""{{
  "name": "{safe_name}-frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  }},
  "dependencies": {{
    "next": "^14.2.0",
    "react": "^18.3.0",
    "react-dom": "^18.3.0"
  }},
  "devDependencies": {{
    "@types/node": "^22.7.0",
    "@types/react": "^18.3.0",
    "@types/react-dom": "^18.3.0",
    "typescript": "^5.6.0"
  }}
}}
"""

    files["frontend/.env.local.example"] = "NEXT_PUBLIC_API_URL=http://localhost:8000\n"

    files["frontend/next.config.js"] = """/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
};
"""

    files["frontend/tsconfig.json"] = """{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
"""

    files["frontend/app/layout.tsx"] = f'''export const metadata = {{
  title: "{name}",
  description: "{description.replace('"', "'")}",
}};

export default function RootLayout({{ children }}: {{ children: React.ReactNode }}) {{
  return (
    <html lang="en">
      <body style={{{{ fontFamily: "system-ui", margin: 0 }}}}>{{children}}</body>
    </html>
  );
}}
'''

    files["frontend/app/page.tsx"] = f'''"use client";

import {{ useEffect, useState }} from "react";
import {{ fetchAPI }} from "../lib/api";

interface Item {{
  id: string;
  name: string;
  description: string | null;
}}

export default function Home() {{
  const [items, setItems] = useState<Item[]>([]);
  const [name, setName] = useState("");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {{
    fetchAPI<Item[]>("/items/").then((res) => {{
      if (res.error) setError(res.error);
      else setItems(res.data || []);
    }});
  }}, []);

  async function add() {{
    if (!name.trim()) return;
    const res = await fetchAPI<Item>("/items/", {{
      method: "POST",
      body: JSON.stringify({{ name }}),
    }});
    if (res.error) {{ setError(res.error); return; }}
    setItems([res.data!, ...items]);
    setName("");
  }}

  return (
    <main style={{{{ maxWidth: 720, margin: "40px auto", padding: 20 }}}}>
      <h1>{name}</h1>
      <p style={{{{ color: "#666" }}}}>{description}</p>
      <div style={{{{ display: "flex", gap: 8, marginBottom: 20 }}}}>
        <input
          value={{name}}
          onChange={{(e) => setName(e.target.value)}}
          placeholder="New item name"
          style={{{{ flex: 1, padding: 8, border: "1px solid #ddd", borderRadius: 4 }}}}
        />
        <button onClick={{add}} style={{{{ padding: "8px 16px" }}}}>Add</button>
      </div>
      {{error && <p style={{{{ color: "crimson" }}}}>{{error}}</p>}}
      <ul>{{items.map((it) => <li key={{it.id}}>{{it.name}}</li>)}}</ul>
    </main>
  );
}}
'''

    files["frontend/lib/api.ts"] = '''const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

export interface ApiResponse<T> {
  data: T | null;
  error: string | null;
}

export async function fetchAPI<T>(
  endpoint: string,
  options: RequestInit = {}
): Promise<ApiResponse<T>> {
  try {
    const res = await fetch(`${API_URL}/api${endpoint}`, {
      ...options,
      headers: { "Content-Type": "application/json", ...(options.headers || {}) },
    });
    if (!res.ok) {
      const body = await res.json().catch(() => ({}));
      return { data: null, error: body.error || `HTTP ${res.status}` };
    }
    return { data: (await res.json()) as T, error: null };
  } catch (err) {
    return { data: null, error: err instanceof Error ? err.message : "unknown" };
  }
}
'''

    files[".gitignore"] = """node_modules/
dist/
.next/
.env
.env.local
*.log
"""

    return files


# ── Django + Postgres ────────────────────────────────────────────────


def _django_postgres_summary() -> TemplateSummary:
    return TemplateSummary(
        template_id="django_postgres",
        name="Django + Postgres",
        short_description=(
            "Batteries-included Python web framework. Built-in admin UI "
            "(huge for internal tools), ORM, auth, sessions. Server-rendered "
            "templates — no separate frontend build."
        ),
        stack=["python", "django", "postgres"],
        best_for=[
            "internal tool",
            "admin",
            "crud",
            "back office",
            "cms",
            "monolith",
        ],
    )


def _render_django_postgres(spec: PlatformSpec) -> dict[str, str]:
    if not spec.project_name:
        raise ValueError("project_name is required to build this template")

    name = spec.project_name
    safe_name = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in name).lower()
    py_module = safe_name.replace("-", "_")
    description = spec.description or f"{name} — generated by NexusForge Platform Synthesizer"

    files: dict[str, str] = {}

    files["README.md"] = f"""# {name}

{description}

> Generated by NexusForge AI — Platform Synthesizer (Django + Postgres template).

## Stack
- **Framework**: Django 5
- **Database**: PostgreSQL 16
- **Frontend**: Django templates (server-rendered) — no separate JS build
- **Admin**: Django Admin at `/admin/` (auto-CRUD for any registered model)

## Quick start

```bash
python -m venv .venv && source .venv/bin/activate  # or .venv\\Scripts\\activate
pip install -r requirements.txt
cp .env.example .env  # edit DATABASE_URL
python manage.py migrate
python manage.py createsuperuser
python manage.py runserver
```

Visit:
- Public site: http://localhost:8000/
- Admin: http://localhost:8000/admin/

## Project layout
- `manage.py` — Django CLI entry
- `{py_module}/settings.py` — config (env-driven)
- `{py_module}/urls.py` — root URL conf
- `core/` — your domain app (Item model + views + admin)

## Next steps
1. Replace the `Item` model in `core/models.py` with your real domain
2. Run `python manage.py makemigrations core && python manage.py migrate`
3. Register more models in `core/admin.py` for instant admin UI
"""

    files["requirements.txt"] = """Django==5.1.0
psycopg[binary]==3.2.0
python-dotenv==1.0.1
gunicorn==23.0.0
"""

    files[".env.example"] = """DATABASE_URL=postgres://user:password@localhost:5432/dbname
SECRET_KEY=changeme-django-secret-key-50-chars-or-more-and-random
DEBUG=True
ALLOWED_HOSTS=localhost,127.0.0.1
"""

    files["manage.py"] = f"""#!/usr/bin/env python
import os
import sys


def main():
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{py_module}.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError("Couldn't import Django. Did you install requirements.txt?") from exc
    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
"""

    files[f"{py_module}/__init__.py"] = ""

    files[f"{py_module}/settings.py"] = f'''"""Django settings for {name}."""
from pathlib import Path
import os

from dotenv import load_dotenv
from urllib.parse import urlparse

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-change-me-in-production")
DEBUG = os.environ.get("DEBUG", "True") == "True"
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "*").split(",")]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "{py_module}.urls"

TEMPLATES = [
    {{
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {{
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        }},
    }},
]

WSGI_APPLICATION = "{py_module}.wsgi.application"

# DATABASE_URL parser (avoids dj-database-url dependency)
_db_url = os.environ.get("DATABASE_URL", "")
if _db_url:
    _parsed = urlparse(_db_url)
    DATABASES = {{
        "default": {{
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _parsed.path.lstrip("/"),
            "USER": _parsed.username or "",
            "PASSWORD": _parsed.password or "",
            "HOST": _parsed.hostname or "localhost",
            "PORT": _parsed.port or 5432,
        }}
    }}
else:
    DATABASES = {{
        "default": {{
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }}
    }}

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
'''

    files[f"{py_module}/urls.py"] = '''from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
]
'''

    files[f"{py_module}/wsgi.py"] = f'''import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{py_module}.settings")
application = get_wsgi_application()
'''

    files[f"{py_module}/asgi.py"] = f'''import os

from django.core.asgi import get_asgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{py_module}.settings")
application = get_asgi_application()
'''

    # ── Core app (the domain) ──
    files["core/__init__.py"] = ""

    files["core/apps.py"] = '''from django.apps import AppConfig


class CoreConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "core"
'''

    files["core/models.py"] = '''from django.db import models


class Item(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-created_at"]
'''

    files["core/admin.py"] = '''from django.contrib import admin

from .models import Item


@admin.register(Item)
class ItemAdmin(admin.ModelAdmin):
    list_display = ("name", "created_at")
    search_fields = ("name", "description")
'''

    files["core/views.py"] = '''from django.shortcuts import render
from django.http import JsonResponse

from .models import Item


def home(request):
    items = Item.objects.all()[:50]
    return render(request, "core/home.html", {"items": items})


def health(request):
    return JsonResponse({"status": "healthy"})
'''

    files["core/urls.py"] = '''from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("health/", views.health, name="health"),
]
'''

    files["core/templates/core/home.html"] = f"""<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{name}</title>
    <style>
        body {{ font-family: system-ui; max-width: 720px; margin: 40px auto; padding: 20px; }}
        h1 {{ font-size: 24px; }}
        p.subtitle {{ color: #666; }}
        ul {{ padding-left: 20px; }}
    </style>
</head>
<body>
    <h1>{name}</h1>
    <p class="subtitle">{description}</p>
    <p>Sign in to <a href="/admin/">/admin/</a> to manage records.</p>
    <h2>Items</h2>
    <ul>
        {{% for item in items %}}
            <li>{{{{ item.name }}}}</li>
        {{% empty %}}
            <li><em>No items yet — add some via /admin/</em></li>
        {{% endfor %}}
    </ul>
</body>
</html>
"""

    files[".gitignore"] = """__pycache__/
*.py[cod]
.venv/
*.egg-info/
.env
db.sqlite3
staticfiles/
"""

    return files


# ── Go + Gin + Postgres ──────────────────────────────────────────────


def _go_gin_postgres_summary() -> TemplateSummary:
    return TemplateSummary(
        template_id="go_gin_postgres",
        name="Go + Gin + Postgres",
        short_description=(
            "Compiled Go binary, Gin HTTP framework, Postgres driver. "
            "Single binary deploys, low memory footprint, fast cold starts. "
            "API-only; no built-in frontend."
        ),
        stack=["go", "gin", "postgres"],
        best_for=[
            "api",
            "microservice",
            "high throughput",
            "low latency",
            "backend",
        ],
    )


def _render_go_gin_postgres(spec: PlatformSpec) -> dict[str, str]:
    if not spec.project_name:
        raise ValueError("project_name is required to build this template")

    name = spec.project_name
    safe_name = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in name).lower()
    description = spec.description or f"{name} — generated by NexusForge Platform Synthesizer"

    files: dict[str, str] = {}

    files["README.md"] = f"""# {name}

{description}

> Generated by NexusForge AI — Platform Synthesizer (Go + Gin + Postgres template).

## Stack
- **Language**: Go 1.22+
- **Framework**: Gin
- **Driver**: pgx/v5
- **API only** — pair with any frontend (or none)

## Quick start

```bash
go mod download
cp .env.example .env  # edit DATABASE_URL
psql $DATABASE_URL -f migrations/001_init.sql
go run .
```

Listens on `:8000` by default. Endpoints:
- `GET  /api/health` — liveness
- `GET  /api/items` — list
- `POST /api/items` — create (`{{ "name": "...", "description": "..." }}`)
- `GET  /api/items/:id` — get one

## Project layout
- `main.go` — entry, router setup
- `db.go` — pgx pool
- `items.go` — items handlers
- `migrations/` — SQL files

## Build for production

```bash
CGO_ENABLED=0 go build -ldflags="-s -w" -o bin/{safe_name} .
./bin/{safe_name}
```

Single static binary, ~10 MB. Drop in a Docker scratch image.
"""

    files["go.mod"] = f"""module {safe_name}

go 1.22

require (
\tgithub.com/gin-contrib/cors v1.7.2
\tgithub.com/gin-gonic/gin v1.10.0
\tgithub.com/jackc/pgx/v5 v5.7.0
\tgithub.com/joho/godotenv v1.5.1
)
"""

    files[".env.example"] = """DATABASE_URL=postgres://user:password@localhost:5432/dbname
PORT=8000
ALLOWED_ORIGINS=http://localhost:3000
"""

    files["main.go"] = f'''package main

import (
\t"context"
\t"log"
\t"os"
\t"strings"

\t"github.com/gin-contrib/cors"
\t"github.com/gin-gonic/gin"
\t"github.com/joho/godotenv"
)

func main() {{
\t_ = godotenv.Load()

\tctx := context.Background()
\tif err := initPool(ctx); err != nil {{
\t\tlog.Fatalf("db: %v", err)
\t}}
\tdefer closePool()

\tport := os.Getenv("PORT")
\tif port == "" {{
\t\tport = "8000"
\t}}

\tr := gin.Default()

\torigins := strings.Split(os.Getenv("ALLOWED_ORIGINS"), ",")
\tif len(origins) == 0 || (len(origins) == 1 && origins[0] == "") {{
\t\torigins = []string{{"*"}}
\t}}
\tr.Use(cors.New(cors.Config{{
\t\tAllowOrigins: origins,
\t\tAllowMethods: []string{{"GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"}},
\t\tAllowHeaders: []string{{"Authorization", "Content-Type"}},
\t}}))

\tr.GET("/api/health", func(c *gin.Context) {{
\t\tc.JSON(200, gin.H{{"status": "healthy"}})
\t}})
\tr.GET("/api/ping", func(c *gin.Context) {{
\t\tc.JSON(200, gin.H{{"pong": true}})
\t}})

\tregisterItemRoutes(r)

\tlog.Printf("Listening on :%s", port)
\tif err := r.Run(":" + port); err != nil {{
\t\tlog.Fatalf("listen: %v", err)
\t}}
}}
'''

    files["db.go"] = '''package main

import (
	"context"
	"errors"
	"os"

	"github.com/jackc/pgx/v5/pgxpool"
)

var pool *pgxpool.Pool

func initPool(ctx context.Context) error {
	url := os.Getenv("DATABASE_URL")
	if url == "" {
		return errors.New("DATABASE_URL not set")
	}
	p, err := pgxpool.New(ctx, url)
	if err != nil {
		return err
	}
	pool = p
	return nil
}

func closePool() {
	if pool != nil {
		pool.Close()
	}
}
'''

    files["items.go"] = '''package main

import (
	"context"

	"github.com/gin-gonic/gin"
)

type Item struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type itemCreate struct {
	Name        string  `json:"name" binding:"required"`
	Description *string `json:"description"`
}

func registerItemRoutes(r *gin.Engine) {
	g := r.Group("/api/items")
	g.GET("", listItems)
	g.POST("", createItem)
	g.GET("/:id", getItem)
}

func listItems(c *gin.Context) {
	rows, err := pool.Query(context.Background(),
		"SELECT id, name, description FROM items ORDER BY id DESC LIMIT 100")
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}
	defer rows.Close()

	out := []Item{}
	for rows.Next() {
		var it Item
		if err := rows.Scan(&it.ID, &it.Name, &it.Description); err != nil {
			c.JSON(500, gin.H{"error": err.Error()})
			return
		}
		out = append(out, it)
	}
	c.JSON(200, out)
}

func createItem(c *gin.Context) {
	var body itemCreate
	if err := c.ShouldBindJSON(&body); err != nil {
		c.JSON(422, gin.H{"error": err.Error()})
		return
	}
	var it Item
	err := pool.QueryRow(context.Background(),
		"INSERT INTO items (name, description) VALUES ($1, $2) RETURNING id, name, description",
		body.Name, body.Description).Scan(&it.ID, &it.Name, &it.Description)
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}
	c.JSON(201, it)
}

func getItem(c *gin.Context) {
	var it Item
	err := pool.QueryRow(context.Background(),
		"SELECT id, name, description FROM items WHERE id = $1",
		c.Param("id")).Scan(&it.ID, &it.Name, &it.Description)
	if err != nil {
		c.JSON(404, gin.H{"error": "Not found"})
		return
	}
	c.JSON(200, it)
}
'''

    files["migrations/001_init.sql"] = '''CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_items_created ON items(created_at DESC);
'''

    files[".gitignore"] = """bin/
*.exe
.env
*.log
"""

    return files


# ── Registry ────────────────────────────────────────────────────────


# Keyed by template_id. Each value is (summary, render_fn).
_REGISTRY: dict[str, tuple[TemplateSummary, Callable[[PlatformSpec], dict[str, str]]]] = {
    "fastapi_react_postgres": (
        _fastapi_react_postgres_summary(),
        _render_fastapi_react_postgres,
    ),
    "express_next_postgres": (
        _express_next_postgres_summary(),
        _render_express_next_postgres,
    ),
    "django_postgres": (
        _django_postgres_summary(),
        _render_django_postgres,
    ),
    "go_gin_postgres": (
        _go_gin_postgres_summary(),
        _render_go_gin_postgres,
    ),
}


def list_templates() -> list[TemplateSummary]:
    """Return all registered template summaries."""
    return [summary for summary, _ in _REGISTRY.values()]


def get_template(template_id: str) -> tuple[TemplateSummary, Callable[[PlatformSpec], dict[str, str]]]:
    """Look up a template by id. Raises KeyError if not found."""
    return _REGISTRY[template_id]


def rank_for_spec(spec: PlatformSpec) -> list[TemplateMatch]:
    """Score every template against the spec and return them sorted
    by score descending. Templates with score == 0 are still
    included so the frontend can show "incompatible" state."""
    matches: list[TemplateMatch] = []
    for summary, _render in _REGISTRY.values():
        score, signals = _score_against(summary, spec)
        matches.append(TemplateMatch(template=summary, score=score, matched_signals=signals))
    matches.sort(key=lambda m: m.score, reverse=True)
    return matches
