"""Template registry for the Platform Synthesizer.

A template is a curated, tested project skeleton with a known
stack. It declares which `PlatformSpec` slots it can absorb, what
its required slots are, and its scoring signals (which spec values
make it a good match).

The first iteration ships ONE template: FastAPI + React + Postgres.
That's the stack Christian uses himself, the most-tested combo in
NexusForge, and the easiest to verify end-to-end. Adding more
templates is purely additive — register a new one in `_REGISTRY`
and add a `_render_*` function below.

Each template's `_render` function is responsible for:
  1. Emitting the file tree as a dict {relative_path: content_str}
  2. Substituting spec slot values into the file contents
  3. Validating that all required slots are filled before render

The synthesizer module writes the dict to disk.
"""
from __future__ import annotations

from typing import Callable

from .schemas import PlatformSpec, TemplateMatch, TemplateSummary


# ── scoring helpers ─────────────────────────────────────────────────


def _score_against(template: TemplateSummary, spec: PlatformSpec) -> tuple[float, list[str]]:
    """Score a template against the user's accumulated spec.

    Returns (score in [0,1], list of matched-signal strings for
    the debug panel). Each signal that lines up adds a fixed
    weight; the final score is normalized.
    """
    signals: list[str] = []
    score = 0.0

    # If the user picked an explicit language, the template MUST
    # match or it scores zero. Same for backend framework.
    if spec.language and spec.language not in {s.lower() for s in template.stack}:
        return 0.0, [f"language mismatch: spec={spec.language}, template={template.stack}"]

    # Stack overlaps: strong signal.
    template_stack_lower = {s.lower() for s in template.stack}
    if spec.backend_framework and spec.backend_framework.lower() in template_stack_lower:
        score += 0.30
        signals.append(f"backend framework matches: {spec.backend_framework}")
    if spec.frontend_framework and spec.frontend_framework.lower() in template_stack_lower:
        score += 0.20
        signals.append(f"frontend framework matches: {spec.frontend_framework}")
    if spec.database and spec.database.lower() in template_stack_lower:
        score += 0.15
        signals.append(f"database matches: {spec.database}")

    # `best_for` matches: each phrase in best_for that appears in
    # the user's description or features adds 0.10.
    haystack = " ".join(
        [
            (spec.description or "").lower(),
            *[f.lower() for f in spec.features],
            *[i.lower() for i in spec.integrations],
        ]
    )
    for phrase in template.best_for:
        if phrase.lower() in haystack:
            score += 0.10
            signals.append(f"use-case match: {phrase!r}")

    # If the user has any spec at all (description filled), give
    # the default template (FastAPI+React+Postgres) a small floor
    # score so it's always at least visible as a fallback.
    if template.template_id == "fastapi_react_postgres" and (
        spec.description or spec.project_name or spec.language is None
    ):
        score = max(score, 0.20)
        if not signals:
            signals.append("default fallback (always visible)")

    # Cap at 1.0.
    return min(score, 1.0), signals


# ── template implementations ────────────────────────────────────────


def _fastapi_react_postgres_summary() -> TemplateSummary:
    return TemplateSummary(
        template_id="fastapi_react_postgres",
        name="FastAPI + React + Postgres",
        short_description=(
            "Production-ready Python backend with FastAPI, React frontend "
            "with Vite, Postgres for persistence. JWT auth optional. "
            "The stack NexusForge itself runs on."
        ),
        stack=["python", "fastapi", "react", "vite", "postgres"],
        best_for=[
            "saas",
            "dashboard",
            "internal tool",
            "api",
            "automation",
            "ai",
            "data",
            "agents",
        ],
    )


def _render_fastapi_react_postgres(spec: PlatformSpec) -> dict[str, str]:
    """Emit the file tree for the FastAPI + React + Postgres template.

    Required slots: project_name. Everything else has sensible
    defaults so the user can run it immediately and refine later.
    """
    if not spec.project_name:
        raise ValueError("project_name is required to build this template")

    name = spec.project_name
    safe_name = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in name).lower()
    description = spec.description or f"{name} — generated by NexusForge Platform Synthesizer"
    auth = spec.auth or "jwt"
    features_md = (
        "\n".join(f"- {f}" for f in spec.features) if spec.features else "- (no features yet — describe more in chat to refine)"
    )
    integrations_md = (
        "\n".join(f"- {i}" for i in spec.integrations) if spec.integrations else "- (none yet)"
    )

    files: dict[str, str] = {}

    # ── README ──
    files["README.md"] = f"""# {name}

{description}

> Generated by NexusForge AI — Platform Synthesizer (FastAPI + React + Postgres template).

## Stack
- **Backend**: Python 3.12 + FastAPI
- **Frontend**: React 18 + Vite
- **Database**: PostgreSQL 16
- **Auth**: {auth}

## Features
{features_md}

## Integrations
{integrations_md}

## Quick start

```bash
# Backend
cd backend
python -m venv .venv && source .venv/bin/activate  # or .venv\\Scripts\\activate on Windows
pip install -r requirements.txt
cp .env.example .env  # then edit DATABASE_URL
uvicorn app.main:app --reload

# Frontend (separate shell)
cd frontend
npm install
npm run dev
```

The backend listens on `http://localhost:8000`, the frontend on `http://localhost:5173`.
The frontend's `VITE_API_URL` points at `http://localhost:8000/api` by default.

## Project layout
- `backend/app/main.py` — FastAPI entry, CORS, lifespan
- `backend/app/routes/` — HTTP handlers
- `backend/app/db/` — Postgres connection + migrations
- `frontend/src/` — React UI
- `frontend/src/services/api.js` — fetch wrapper

## Next steps after generation
1. Set `DATABASE_URL` in `backend/.env`
2. Run the SQL in `backend/app/db/migrations/001_init.sql` against your Postgres
3. Generate a JWT secret: `python -c "import secrets; print(secrets.token_urlsafe(48))"` and put it in `JWT_SECRET`
4. Replace the stub endpoints in `backend/app/routes/items.py` with your real domain
"""

    # ── Backend ──
    files["backend/requirements.txt"] = """fastapi==0.115.0
uvicorn[standard]==0.30.0
pydantic>=2.10.0,<3.0.0
pydantic-settings>=2.5.0,<3.0.0
asyncpg==0.29.0
python-multipart==0.0.9
PyJWT>=2.8.0,<3.0.0
bcrypt>=4.1.0,<5.0.0
"""

    files["backend/.env.example"] = """# Postgres connection — same shape as on Render / Supabase / local docker
DATABASE_URL=postgres://user:password@localhost:5432/dbname

# JWT signing secret (generate with: python -c "import secrets; print(secrets.token_urlsafe(48))")
JWT_SECRET=changeme-in-production-use-token-urlsafe-48

# CORS allowlist for browser callers (comma-separated)
ALLOWED_ORIGINS=http://localhost:5173
"""

    files["backend/app/__init__.py"] = ""

    files["backend/app/main.py"] = f'''"""FastAPI entry for {name}.

Generated by NexusForge AI Platform Synthesizer.
"""
import os
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.routes.health import router as health_router
from app.routes.items import router as items_router
from app.routes.auth import router as auth_router
from app.db.client import get_pool, close_pool


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Eager-warm the pool so the first request doesn't pay the latency.
    try:
        await get_pool()
    except Exception as exc:
        print(f"Warning: DB pool not warmed at startup: {{exc}}")
    yield
    await close_pool()


app = FastAPI(title="{name}", lifespan=lifespan)

origins = [o.strip() for o in os.environ.get("ALLOWED_ORIGINS", "*").split(",") if o.strip()]
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=False,
    allow_methods=["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
    allow_headers=["Authorization", "Content-Type"],
)

app.include_router(health_router, prefix="/api", tags=["health"])
app.include_router(auth_router, prefix="/api/auth", tags=["auth"])
app.include_router(items_router, prefix="/api/items", tags=["items"])
'''

    files["backend/app/routes/__init__.py"] = ""

    files["backend/app/routes/health.py"] = '''"""Liveness + readiness probes."""
from fastapi import APIRouter

router = APIRouter()


@router.get("/health")
async def health():
    return {"status": "healthy"}


@router.get("/ping")
async def ping():
    return {"pong": True}
'''

    files["backend/app/routes/auth.py"] = f'''"""Stub JWT auth.

Generated baseline — replace with your real user store.
"""
import os
import time

import jwt
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

router = APIRouter()
JWT_SECRET = os.environ.get("JWT_SECRET", "")


class LoginRequest(BaseModel):
    email: str
    password: str


@router.post("/login")
async def login(body: LoginRequest):
    """Stub: accepts any email + password=demo for now.

    Replace with a real lookup against your users table.
    """
    if body.password != "demo":
        raise HTTPException(401, "Invalid credentials")
    if not JWT_SECRET:
        raise HTTPException(500, "JWT_SECRET not configured")
    payload = {{
        "sub": body.email,
        "iat": int(time.time()),
        "exp": int(time.time()) + 8 * 3600,
    }}
    token = jwt.encode(payload, JWT_SECRET, algorithm="HS256")
    return {{"token": token}}
'''

    files["backend/app/routes/items.py"] = '''"""Items CRUD — example domain you'll replace."""
from uuid import UUID

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from app.db.client import get_pool

router = APIRouter()


class ItemCreate(BaseModel):
    name: str
    description: str | None = None


@router.get("/")
async def list_items():
    pool = await get_pool()
    async with pool.acquire() as conn:
        rows = await conn.fetch("SELECT id, name, description FROM items ORDER BY id DESC LIMIT 100")
    return [{"id": str(r["id"]), "name": r["name"], "description": r["description"]} for r in rows]


@router.post("/", status_code=201)
async def create_item(body: ItemCreate):
    pool = await get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "INSERT INTO items (name, description) VALUES ($1, $2) RETURNING id, name, description",
            body.name, body.description,
        )
    return {"id": str(row["id"]), "name": row["name"], "description": row["description"]}


@router.get("/{item_id}")
async def get_item(item_id: UUID):
    pool = await get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow("SELECT id, name, description FROM items WHERE id = $1", item_id)
    if not row:
        raise HTTPException(404, "Item not found")
    return {"id": str(row["id"]), "name": row["name"], "description": row["description"]}
'''

    files["backend/app/db/__init__.py"] = ""

    files["backend/app/db/client.py"] = '''"""Asyncpg pool — warm once, share across requests."""
import os

import asyncpg

_pool: asyncpg.Pool | None = None


async def get_pool() -> asyncpg.Pool:
    global _pool
    if _pool is None:
        url = os.environ.get("DATABASE_URL")
        if not url:
            raise RuntimeError("DATABASE_URL not set")
        _pool = await asyncpg.create_pool(url, min_size=1, max_size=10)
    return _pool


async def close_pool() -> None:
    global _pool
    if _pool is not None:
        await _pool.close()
        _pool = None
'''

    files["backend/app/db/migrations/001_init.sql"] = '''-- Run this once against your Postgres before starting the app.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_items_created ON items(created_at DESC);
'''

    # ── Frontend ──
    files["frontend/package.json"] = f"""{{
  "name": "{safe_name}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "react": "^18.3.0",
    "react-dom": "^18.3.0",
    "react-router-dom": "^6.26.0"
  }},
  "devDependencies": {{
    "@vitejs/plugin-react": "^4.3.0",
    "vite": "^5.4.0"
  }}
}}
"""

    files["frontend/vite.config.js"] = """import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: { port: 5173 },
})
"""

    files["frontend/index.html"] = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
"""

    files["frontend/src/main.jsx"] = '''import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
'''

    files["frontend/src/App.jsx"] = f'''import {{ useEffect, useState }} from 'react'
import {{ fetchAPI }} from './services/api.js'

export default function App() {{
  const [items, setItems] = useState([])
  const [name, setName] = useState('')
  const [error, setError] = useState(null)

  useEffect(() => {{
    fetchAPI('/items/').then(res => {{
      if (res.error) setError(res.error)
      else setItems(res.data || [])
    }})
  }}, [])

  async function add() {{
    if (!name.trim()) return
    const res = await fetchAPI('/items/', {{
      method: 'POST',
      body: JSON.stringify({{ name }}),
    }})
    if (res.error) {{ setError(res.error); return }}
    setItems([res.data, ...items])
    setName('')
  }}

  return (
    <div style={{{{ fontFamily: 'system-ui', maxWidth: 720, margin: '40px auto', padding: 20 }}}}>
      <h1>{name}</h1>
      <p style={{{{ color: '#666' }}}}>{description}</p>
      <div style={{{{ display: 'flex', gap: 8, marginBottom: 20 }}}}>
        <input
          value={{name}}
          onChange={{e => setName(e.target.value)}}
          placeholder="New item name"
          style={{{{ flex: 1, padding: 8, border: '1px solid #ddd', borderRadius: 4 }}}}
        />
        <button onClick={{add}} style={{{{ padding: '8px 16px' }}}}>Add</button>
      </div>
      {{error && <p style={{{{ color: 'crimson' }}}}>{{error}}</p>}}
      <ul>
        {{items.map(it => (
          <li key={{it.id}}>{{it.name}}</li>
        ))}}
      </ul>
    </div>
  )
}}
'''

    files["frontend/src/services/api.js"] = '''const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000/api'

export async function fetchAPI(endpoint, options = {}) {
  try {
    const res = await fetch(`${API_URL}${endpoint}`, {
      ...options,
      headers: { 'Content-Type': 'application/json', ...(options.headers || {}) },
    })
    if (!res.ok) {
      let detail = `HTTP ${res.status}`
      try { const body = await res.json(); detail = body.detail || detail } catch {}
      return { data: null, error: detail }
    }
    return { data: await res.json(), error: null }
  } catch (err) {
    return { data: null, error: err.message }
  }
}
'''

    files[".gitignore"] = """# Python
__pycache__/
*.py[cod]
.venv/
*.egg-info/

# Node
node_modules/
dist/

# Env
.env
.env.local
"""

    return files


# ── registry ────────────────────────────────────────────────────────


# Keyed by template_id. Each value is (summary, render_fn).
_REGISTRY: dict[str, tuple[TemplateSummary, Callable[[PlatformSpec], dict[str, str]]]] = {
    "fastapi_react_postgres": (
        _fastapi_react_postgres_summary(),
        _render_fastapi_react_postgres,
    ),
}


def list_templates() -> list[TemplateSummary]:
    """Return all registered template summaries."""
    return [summary for summary, _ in _REGISTRY.values()]


def get_template(template_id: str) -> tuple[TemplateSummary, Callable[[PlatformSpec], dict[str, str]]]:
    """Look up a template by id. Raises KeyError if not found."""
    return _REGISTRY[template_id]


def rank_for_spec(spec: PlatformSpec) -> list[TemplateMatch]:
    """Score every template against the spec and return them sorted
    by score descending. Templates with score == 0 are still
    included so the frontend can show "incompatible" state."""
    matches: list[TemplateMatch] = []
    for summary, _render in _REGISTRY.values():
        score, signals = _score_against(summary, spec)
        matches.append(TemplateMatch(template=summary, score=score, matched_signals=signals))
    matches.sort(key=lambda m: m.score, reverse=True)
    return matches
