"""Tests for decision-gate parsing + markdown rendering in strangler_planner."""
from __future__ import annotations

from pathlib import Path

from app.refactor.strangler_planner import (
    PreAssignedDecision,
    StranglerPhase,
    StranglerPlan,
    _read_pre_assigned_decision,
    render_markdown,
)


# ── PreAssignedDecision dataclass ─────────────────────────────────────


def test_default_pre_assigned_decision_is_not_a_gate():
    d = PreAssignedDecision()
    assert d.is_gate is False


def test_tbd_action_marks_as_gate():
    d = PreAssignedDecision(action="tbd")
    assert d.is_gate is True


def test_explicit_gate_type_marks_as_gate():
    d = PreAssignedDecision(action="refactor", gate_type="retire-vs-refactor")
    assert d.is_gate is True


# ── Parser: decision gate from refactor_decision.md ──────────────────


def _write_decision_md(app_dir: Path, body: str) -> None:
    app_dir.mkdir(parents=True, exist_ok=True)
    (app_dir / "refactor_decision.md").write_text(body, encoding="utf-8")


def test_parser_ignores_non_gate_files(tmp_path):
    body = """# Refactor Decision — `app-07`

**App:** Foo
**Action:** `REFACTOR`
**Phase:** Q3

## Rationale

Clean refactor.

## Validation checklist

- [ ] Write tests

## Blockers

- (none)
"""
    _write_decision_md(tmp_path, body)
    d = _read_pre_assigned_decision(tmp_path)
    assert d is not None
    assert d.is_gate is False
    assert d.gate_type == ""
    assert d.evidence_for == []


def test_parser_extracts_full_gate_section(tmp_path):
    body = """# Refactor Decision — `app-03`

**App:** Refunds
**Action:** `TBD`
**Phase:** IMMEDIATE

## Rationale

Needs owner confirmation.

## Validation checklist

- [ ] Confirm business owner

## Blockers

- Vendor veto

## Decision gate — `retire-vs-refactor`

**Evidence FOR the proposed action:**
- 0% activity since 2023-03
- Replaced by RAM + Riffle

**Evidence AGAINST (blockers for the action):**
- Business owner not confirmed
- Regulatory retention unknown

**Blocker to resolve:** Escalate to business owner + compliance

**Estimated savings if taken:** ~4-6 weeks refactor effort avoided

**Stakeholders to confirm:** cliente-business-owner-refunds, compliance-office, ram-product-owner

_Auto-generated by synth._
"""
    _write_decision_md(tmp_path, body)
    d = _read_pre_assigned_decision(tmp_path)
    assert d is not None
    assert d.is_gate is True
    assert d.gate_type == "retire-vs-refactor"
    assert len(d.evidence_for) == 2
    assert "0% activity" in d.evidence_for[0]
    assert len(d.evidence_against) == 2
    assert "Business owner" in d.evidence_against[0]
    assert "compliance" in d.blocker_to_resolve.lower()
    assert "4-6 weeks" in d.estimated_savings_if_taken
    assert len(d.stakeholders_to_confirm) == 3
    assert "ram-product-owner" in d.stakeholders_to_confirm


# ── Markdown rendering ────────────────────────────────────────────────


def _minimal_plan(decision: PreAssignedDecision | None = None) -> StranglerPlan:
    return StranglerPlan(
        app_name="app-03",
        app_path="/tmp/app-03",
        total_modules=3,
        total_loc=80_000,
        total_vulns=316,
        phases=[
            StranglerPhase(
                index=1,
                title="Phase 1",
                role="core",
                risk="high",
                effort_days=20,
                rationale="example",
                strategy="refactor",
                rollback="rollback",
                modules=[],
            )
        ],
        narrative="Narrative body.",
        pre_assigned_decision=decision,
    )


def test_render_markdown_without_gate_has_no_gate_section():
    decision = PreAssignedDecision(action="refactor", phase="Q3")
    plan = _minimal_plan(decision=decision)
    md = render_markdown(plan)
    assert "Decision gate" not in md


def test_render_markdown_with_gate_adds_top_section():
    decision = PreAssignedDecision(
        action="tbd",
        phase="IMMEDIATE",
        gate_type="retire-vs-refactor",
        evidence_for=["0% activity since 2023-03", "RAM + Riffle replacement"],
        evidence_against=["Business owner not confirmed"],
        blocker_to_resolve="Escalate to business owner",
        estimated_savings_if_taken="~4 weeks",
        stakeholders_to_confirm=["cliente-owner", "compliance"],
    )
    plan = _minimal_plan(decision=decision)
    md = render_markdown(plan)

    assert "Decision gate — pending stakeholder call" in md
    assert "`retire-vs-refactor`" in md
    assert "0% activity since 2023-03" in md
    assert "Business owner not confirmed" in md
    assert "Escalate to business owner" in md
    assert "~4 weeks" in md
    assert "cliente-owner" in md

    # Gate must appear BEFORE the narrative section
    gate_idx = md.index("Decision gate")
    narrative_idx = md.index("## Narrative")
    assert gate_idx < narrative_idx


def test_render_markdown_gate_with_tbd_but_no_explicit_type_still_renders():
    """action=tbd alone is enough to render the gate block."""
    decision = PreAssignedDecision(action="tbd", phase="IMMEDIATE")
    plan = _minimal_plan(decision=decision)
    md = render_markdown(plan)
    assert "Decision gate" in md
    # Falls back to the action label when gate_type is blank
    assert "`tbd`" in md or "`TBD`" in md
