"""Tests for Phase B scaffolding — non-scope app discovery-pending stubs.

The scaffolding brings the tenant-alpha footprint from 5 scope apps
to the 31-app target documented in
``docs/integration/03_future_platform_vision.md`` §15, without
fabricating realistic code for the 26 apps we have no Report Out
data on. Each non-scope app gets a single ``DISCOVERY_PENDING.md``
stub so ingestion and dependency mapping correctly count the app
toward the overall footprint.

Covers:

- ``NonScopeAppStub`` dataclass + markdown emission
- YAML parsing of the ``non_scope_apps`` section, both dict and
  short-form string shapes
- ``TenantProfile.total_apps`` aggregation
- ``generate_tenant`` emits one directory per stub with a
  DISCOVERY_PENDING.md file and nothing else
- ``GenerationReport.non_scope_stubs_generated`` tracks the stubs
  separately from the full-recipe apps
- ``--only-app`` (scope filter) skips stubs so single-app dev
  iteration stays fast
- The real committed ``tenant_alpha.yaml`` fixture reaches 31 apps
"""
from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from app.synth.generator import GenerationReport, generate_tenant
from app.synth.profile import (
    NonScopeAppStub,
    TenantProfile,
    load_profile,
)


# ── NonScopeAppStub dataclass ─────────────────────────────────────────


def test_stub_markdown_contains_required_sections():
    stub = NonScopeAppStub(
        codename="app-42",
        label="Answer Service",
        category="satellite",
        notes="Consumed by app-01 once a month.",
    )
    md = stub.to_stub_markdown()

    assert "`app-42`" in md
    assert "DISCOVERY PENDING" in md
    assert "Answer Service" in md
    assert "`satellite`" in md
    assert "TBD" in md
    assert "In scope:" in md
    assert "Consumed by app-01 once a month." in md
    # Auto-generated marker so humans know not to hand-edit
    assert "Auto-generated by the synth Phase B scaffolding" in md


def test_stub_markdown_handles_missing_optional_fields():
    stub = NonScopeAppStub(codename="app-99")
    md = stub.to_stub_markdown()

    assert "`app-99`" in md
    # Label falls back to the codename
    assert "app-99" in md
    # Default category is "satellite"
    assert "`satellite`" in md
    # Empty notes render the placeholder
    assert "(no additional notes)" in md


# ── YAML parser ───────────────────────────────────────────────────────


def _write_fixture(tmp_path: Path, apps: list[dict], non_scope_apps: list | None = None) -> Path:
    data = {
        "tenant_id": "test-tenant",
        "display_name": "Test",
        "seed": 1,
        "apps": apps,
    }
    if non_scope_apps is not None:
        data["non_scope_apps"] = non_scope_apps
    path = tmp_path / "fixture.yaml"
    path.write_text(yaml.dump(data), encoding="utf-8")
    return path


_MIN_APP = {
    "codename": "app-01",
    "label": "Scope App",
    "loc_target": 1000,
    "primary_language": "python",
    "modules": 2,
}


def test_parser_handles_dict_form_stubs(tmp_path: Path):
    path = _write_fixture(
        tmp_path,
        apps=[_MIN_APP],
        non_scope_apps=[
            {
                "codename": "app-06",
                "label": "Customer Portal",
                "category": "satellite",
                "notes": "Peripheral",
            },
            {"codename": "app-07", "category": "utility"},
        ],
    )
    profile = load_profile(path)
    assert len(profile.non_scope_apps) == 2
    assert profile.non_scope_apps[0].codename == "app-06"
    assert profile.non_scope_apps[0].label == "Customer Portal"
    assert profile.non_scope_apps[0].category == "satellite"
    assert profile.non_scope_apps[0].notes == "Peripheral"
    # Second stub has defaults for missing fields
    assert profile.non_scope_apps[1].label == ""
    assert profile.non_scope_apps[1].category == "utility"


def test_parser_handles_short_form_string_stubs(tmp_path: Path):
    """A YAML entry that is just a codename string (no label, no
    category) must parse as a NonScopeAppStub with defaults."""
    path = _write_fixture(
        tmp_path,
        apps=[_MIN_APP],
        non_scope_apps=["app-50", "app-51"],
    )
    profile = load_profile(path)
    assert [s.codename for s in profile.non_scope_apps] == ["app-50", "app-51"]
    # Defaults
    assert all(s.label == "" for s in profile.non_scope_apps)
    assert all(s.category == "satellite" for s in profile.non_scope_apps)


def test_parser_missing_section_leaves_empty_list(tmp_path: Path):
    """Fixtures predating Phase B (no non_scope_apps section) must
    still load cleanly with an empty stubs list."""
    path = _write_fixture(tmp_path, apps=[_MIN_APP])
    profile = load_profile(path)
    assert profile.non_scope_apps == []
    assert profile.total_apps() == 1


def test_parser_null_section_leaves_empty_list(tmp_path: Path):
    """A ``non_scope_apps: null`` line should be tolerated — same as
    an empty list."""
    path = _write_fixture(tmp_path, apps=[_MIN_APP], non_scope_apps=None)
    profile = load_profile(path)
    assert profile.non_scope_apps == []


# ── TenantProfile.total_apps ──────────────────────────────────────────


def test_total_apps_sums_scope_and_stubs():
    profile = TenantProfile(
        tenant_id="t",
        display_name="T",
        non_scope_apps=[
            NonScopeAppStub(codename="a"),
            NonScopeAppStub(codename="b"),
            NonScopeAppStub(codename="c"),
        ],
    )
    # 0 scope apps + 3 stubs = 3
    assert profile.total_apps() == 3


# ── Generator ─────────────────────────────────────────────────────────


def test_generate_tenant_emits_one_stub_per_non_scope_app(tmp_path: Path):
    profile = TenantProfile(
        tenant_id="stub-test",
        display_name="Stub Test",
        seed=1,
        non_scope_apps=[
            NonScopeAppStub(codename="app-s1", label="First Stub", category="satellite"),
            NonScopeAppStub(codename="app-s2", label="Second Stub", category="archival"),
            NonScopeAppStub(codename="app-s3", category="utility"),
        ],
    )
    report = generate_tenant(profile, tmp_path)

    # Report state
    assert report.non_scope_stubs_generated == ["app-s1", "app-s2", "app-s3"]
    assert report.apps_generated == []
    assert report.total_apps == 3

    tenant_dir = tmp_path / "stub-test"
    # One directory per stub, each containing exactly one file
    for cn in ("app-s1", "app-s2", "app-s3"):
        stub_dir = tenant_dir / cn
        assert stub_dir.is_dir()
        files = list(stub_dir.iterdir())
        assert len(files) == 1
        assert files[0].name == "DISCOVERY_PENDING.md"
        # Markdown sanity checks
        content = files[0].read_text(encoding="utf-8")
        assert cn in content
        assert "DISCOVERY PENDING" in content


def test_generate_tenant_only_app_filter_skips_stubs(tmp_path: Path):
    """``--app`` single-app mode must not emit stubs. This keeps dev
    iteration fast when the caller only wants to regenerate one
    scope app."""
    profile = TenantProfile(
        tenant_id="filter-test",
        display_name="Filter Test",
        seed=1,
        non_scope_apps=[
            NonScopeAppStub(codename="app-s1"),
            NonScopeAppStub(codename="app-s2"),
        ],
    )
    # Filter on a codename that does NOT exist in apps[] — the
    # generator should skip the scope loop entirely and also skip
    # the stub loop (because only_app was set).
    report = generate_tenant(profile, tmp_path, only_app="app-99")

    assert report.non_scope_stubs_generated == []
    assert report.apps_generated == []
    # No stub dirs should exist
    tenant_dir = tmp_path / "filter-test"
    if tenant_dir.exists():
        assert not (tenant_dir / "app-s1").exists()
        assert not (tenant_dir / "app-s2").exists()


# ── Real committed fixture ────────────────────────────────────────────


def test_committed_fixture_reaches_31_app_footprint():
    """End-to-end check that the committed tenant_alpha.yaml fixture
    now reaches the 31-app target from
    ``docs/integration/03_future_platform_vision.md`` §15.

    Guards against accidental removal of the Phase B scaffolding
    section or accidental drift from 31."""
    fixture_path = (
        Path(__file__).resolve().parents[1]
        / "app"
        / "synth"
        / "fixtures"
        / "tenant_alpha.yaml"
    )
    profile = load_profile(fixture_path)
    assert len(profile.apps) == 5, "Scope apps should stay at 5 until a new one ships"
    assert len(profile.non_scope_apps) == 26, "Phase B stubs should be 26"
    assert profile.total_apps() == 31, "Footprint must match the 31-app research-doc target"

    # Every stub has a non-empty codename and a recognized category
    valid_categories = {"satellite", "shared-library", "archival", "utility", "integration"}
    for stub in profile.non_scope_apps:
        assert stub.codename, "Stub must have a codename"
        assert stub.codename.startswith("app-"), f"Unexpected codename: {stub.codename}"
        assert stub.category in valid_categories, f"Unknown category in {stub.codename}: {stub.category}"

    # Scope apps and stubs must not share codenames (avoids double
    # counting in downstream tooling)
    scope_names = {a.codename for a in profile.apps}
    stub_names = {s.codename for s in profile.non_scope_apps}
    assert scope_names.isdisjoint(stub_names)
