"""Refactoring API — ingest repos, auto-fix vulnerabilities, generate PRs.

Endpoints:
  POST /refactor/ingest         — Scan and map a repository
  POST /refactor/execute        — Run automated refactoring on ingested project
  POST /refactor/pr             — Generate PR from refactoring results
  GET  /refactor/status         — Check refactoring job status
  GET  /refactor/showcase       — List available showcase tenants (public)
  GET  /refactor/showcase/{id}  — Get showcase report for a tenant (public)
  GET  /refactor/showcase/{id}/strangler/{app} — Get strangler plan for app (public)
"""

import json
import logging
from pathlib import Path
from fastapi import APIRouter, Request, HTTPException
from pydantic import BaseModel
from typing import Optional

logger = logging.getLogger(__name__)

# Showcase data directory — static JSON fixtures committed to the repo so
# the /showcase endpoints work in production without needing synth_output/
# (which is gitignored). Fixtures are generated by
# backend/scripts/showcase_run.py + strangler_planner locally, then
# sanitized and copied here.
_SHOWCASE_DATA_DIR = Path(__file__).resolve().parents[2] / "showcase_data"

router = APIRouter(prefix="/refactor", tags=["refactor-engine"])


class IngestRequest(BaseModel):
    path: str                          # Local path or Git URL
    name: str = ""                     # Project name

class RefactorRequest(BaseModel):
    project_path: str                  # Path to ingested project
    fix_types: list[str] | None = None # Filter: ["sql_injection", "hardcoded_secret"]
    use_llm: bool = True               # Use LLM for complex fixes
    dry_run: bool = False              # Don't modify files
    max_parallel: int = 5              # Concurrent file processing

class PRRequest(BaseModel):
    project_path: str
    base_branch: str = "main"


def _get_user_id(request: Request) -> str:
    user = getattr(request.state, "user", None)
    if not user:
        raise HTTPException(status_code=401, detail="Login required")
    return user.get("sub", user.get("user_id", ""))


# In-memory job storage (replace with Redis for production)
_jobs: dict[str, dict] = {}


@router.post("/ingest")
async def ingest_repo(body: IngestRequest, request: Request):
    """Ingest a repository: scan, detect languages, build dependency graph."""
    _get_user_id(request)

    from app.auth.rate_limit import check_rate_limit
    await check_rate_limit(request)

    from app.refactor.ingestion import RepoIngestionEngine

    engine = RepoIngestionEngine()
    try:
        graph = await engine.ingest(body.path, body.name)
        return graph.to_dict()
    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as exc:
        logger.exception("Ingestion failed")
        raise HTTPException(status_code=500, detail="Ingestion failed")


@router.post("/execute")
async def execute_refactoring(body: RefactorRequest, request: Request):
    """Execute automated refactoring on a project.

    Processes vulnerability hotspots in DAG order with parallel execution.
    """
    _get_user_id(request)

    from app.auth.rate_limit import check_rate_limit
    await check_rate_limit(request)

    from app.refactor.ingestion import RepoIngestionEngine
    from app.refactor.engine import RefactoringEngine

    # First ingest
    ingestion = RepoIngestionEngine()
    try:
        graph = await ingestion.ingest(body.project_path)
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Ingestion failed: {type(exc).__name__}")

    # Then refactor
    engine = RefactoringEngine(
        project_root=body.project_path,
        use_llm=body.use_llm,
        dry_run=body.dry_run,
    )

    report = await engine.refactor_project(
        graph=graph,
        fix_types=body.fix_types,
        max_parallel=body.max_parallel,
    )

    # Store result for PR generation
    _jobs[body.project_path] = {
        "graph": graph.to_dict(),
        "report": report.to_dict(),
    }

    return report.to_dict()


@router.post("/pr")
async def generate_pr(body: PRRequest, request: Request):
    """Generate a PR-ready branch from refactoring results."""
    _get_user_id(request)

    job = _jobs.get(body.project_path)
    if not job:
        raise HTTPException(status_code=404, detail="No refactoring results found. Run /refactor/execute first.")

    from app.refactor.pr_generator import PRGenerator
    from app.refactor.engine import RefactorReport

    generator = PRGenerator(body.project_path)

    # Reconstruct report
    report_data = job["report"]
    report = RefactorReport(project_name=report_data["project"])
    report.files_fixed = report_data["summary"]["fixed"]
    report.vulnerabilities_fixed = report_data["summary"]["vulnerabilities_fixed"]
    report.tests_passing = report_data["summary"]["tests_passing"]
    report.files_failed = report_data["summary"]["failed"]
    report.total_cost_usd = report_data["cost"]["usd"]
    report.duration_ms = report_data["duration_ms"]

    result = await generator.generate_pr(report, base_branch=body.base_branch)
    return result


class TestGenRequest(BaseModel):
    project_path: str
    languages: list[str] | None = None  # Filter: ["python", "csharp"]
    dry_run: bool = False


@router.post("/generate-tests")
async def generate_tests(body: TestGenRequest, request: Request):
    """Auto-generate test files for codebases with zero test coverage."""
    _get_user_id(request)

    from app.auth.rate_limit import check_rate_limit
    await check_rate_limit(request)

    from app.refactor.ingestion import RepoIngestionEngine
    from app.refactor.test_generator import TestGeneratorEngine

    ingestion = RepoIngestionEngine()
    try:
        graph = await ingestion.ingest(body.project_path)
    except Exception:
        raise HTTPException(status_code=400, detail="Ingestion failed")

    generator = TestGeneratorEngine(
        project_root=body.project_path,
        dry_run=body.dry_run,
    )
    report = await generator.generate_tests(graph, languages=body.languages)
    return report.to_dict()


class MultiRepoRequest(BaseModel):
    repos: list[dict]              # [{"path": str, "name": str}, ...]
    fix_types: list[str] | None = None
    use_llm: bool = True
    dry_run: bool = False
    generate_tests: bool = True
    max_repos_parallel: int = 3


@router.post("/multi-repo")
async def multi_repo_refactor(body: MultiRepoRequest, request: Request):
    """Process multiple repositories in parallel — enterprise pipeline.

    Ingests all repos, builds cross-repo dependency map,
    refactors in safe order, generates tests, and produces consolidated report.
    """
    _get_user_id(request)

    from app.auth.rate_limit import check_rate_limit
    await check_rate_limit(request)

    from app.refactor.multi_repo import MultiRepoOrchestrator

    orchestrator = MultiRepoOrchestrator(
        use_llm=body.use_llm,
        dry_run=body.dry_run,
        max_repos_parallel=body.max_repos_parallel,
    )

    report = await orchestrator.process(
        repos=body.repos,
        fix_types=body.fix_types,
        generate_tests=body.generate_tests,
    )

    return report.to_dict()


class CSharpAnalyzeRequest(BaseModel):
    project_path: str


@router.post("/analyze-csharp")
async def analyze_csharp(body: CSharpAnalyzeRequest, request: Request):
    """Deep C#/.NET analysis — classes, vulnerabilities, god classes, auth gaps."""
    _get_user_id(request)

    from app.refactor.csharp_analyzer import CSharpAnalyzer

    analyzer = CSharpAnalyzer(body.project_path)
    projects = await analyzer.analyze()
    return [p.to_dict() for p in projects]


@router.post("/fix-csharp")
async def fix_csharp(body: CSharpAnalyzeRequest, request: Request):
    """Auto-fix SQL injection and hardcoded credentials in C# files."""
    _get_user_id(request)

    from app.refactor.csharp_analyzer import CSharpAnalyzer
    from app.refactor.csharp_fixer import CSharpFixer

    # First analyze
    analyzer = CSharpAnalyzer(body.project_path)
    projects = await analyzer.analyze()

    # Then fix files with findings
    fixer = CSharpFixer(body.project_path, dry_run=True)
    results = []
    for proj in projects:
        for finding in proj.findings:
            if finding.category in ("sql_injection", "hardcoded_cred"):
                result = fixer.fix_file(finding.file_path)
                if result.fixes_applied > 0:
                    results.append({
                        "file": result.file_path,
                        "fixes": result.fixes_applied,
                        "diff": result.diff_summary,
                        "details": result.fixes,
                    })
    return {"files_fixed": len(results), "results": results}


@router.post("/generate-cicd")
async def generate_cicd(body: CSharpAnalyzeRequest, request: Request):
    """Generate GitHub Actions CI/CD pipelines for .NET and Python projects."""
    _get_user_id(request)

    from app.refactor.csharp_analyzer import CSharpAnalyzer
    from app.refactor.cicd_generator import CICDGenerator

    analyzer = CSharpAnalyzer(body.project_path)
    projects = await analyzer.analyze()

    generator = CICDGenerator(body.project_path, dry_run=True)
    results = []
    for proj in projects:
        result = generator.generate_for_project(proj)
        results.append({
            "project": proj.name,
            "pipelines": result["pipelines"],
            "test_files": len(result["test_files"]),
        })
    return {"projects": len(results), "results": results}


@router.post("/scan-rpa")
async def scan_rpa(body: CSharpAnalyzeRequest, request: Request):
    """Scan RPA code for fragile Playwright selectors and stability issues."""
    _get_user_id(request)

    from app.refactor.rpa_scanner import RPAScanner

    scanner = RPAScanner(body.project_path)
    report = await scanner.scan()
    return report.to_dict()


class TriageRequest(BaseModel):
    project_path: str
    issues: list[dict] = []        # Pre-loaded issues, or empty to scan from code
    apps: list[str] | None = None  # Filter to specific apps


@router.post("/triage")
async def triage_issues(body: TriageRequest, request: Request):
    """Prioritize issues into remediation batches (handles 166K+ issues)."""
    _get_user_id(request)

    from app.refactor.triage import IssuTriageEngine

    engine = IssuTriageEngine()

    # If no pre-loaded issues, generate from code analysis
    if not body.issues:
        from app.refactor.ingestion import RepoIngestionEngine
        from app.refactor.csharp_analyzer import CSharpAnalyzer

        ingestion = RepoIngestionEngine()
        graph = await ingestion.ingest(body.project_path)

        issues = []
        # Add ingestion hotspots as issues
        for h in graph.vulnerability_hotspots:
            issues.append({
                "title": f"Vulnerability in {h['file']}",
                "category": "code_quality",
                "severity": "high" if h["vulnerabilities"] > 2 else "medium",
                "file_path": h["file"],
                "app": "",
            })

        # Add C# findings
        analyzer = CSharpAnalyzer(body.project_path)
        projects = await analyzer.analyze()
        for p in projects:
            for f in p.findings:
                issues.append({
                    "title": f.title,
                    "category": f.category,
                    "severity": f.severity,
                    "cwe": f.cwe,
                    "file_path": f.file_path,
                    "line_number": f.line_number,
                    "app": p.name,
                })

        body.issues = issues

    report = engine.triage(body.issues, apps=body.apps)
    return report.to_dict()


class BatchRequest(BaseModel):
    project_path: str
    triage_report: dict = {}       # Pre-computed triage, or empty to auto-triage
    batch_filter: list[int] | None = None  # [1, 2] = only critical batches
    max_workers: int = 4
    dry_run: bool = True


@router.post("/batch-remediate")
async def batch_remediate(body: BatchRequest, request: Request):
    """Execute batch remediation pipeline — 500+ fixes/hour target."""
    _get_user_id(request)

    from app.auth.rate_limit import check_rate_limit
    await check_rate_limit(request)

    # Auto-triage if no pre-computed report
    if not body.triage_report:
        from app.refactor.triage import IssuTriageEngine
        from app.refactor.ingestion import RepoIngestionEngine
        from app.refactor.csharp_analyzer import CSharpAnalyzer

        ingestion = RepoIngestionEngine()
        graph = await ingestion.ingest(body.project_path)

        issues = []
        for h in graph.vulnerability_hotspots:
            issues.append({
                "title": f"Vulnerability in {h['file']}",
                "category": "code_quality",
                "severity": "high" if h["vulnerabilities"] > 2 else "medium",
                "file_path": h["file"],
            })

        analyzer = CSharpAnalyzer(body.project_path)
        for p in await analyzer.analyze():
            for f in p.findings:
                issues.append({
                    "title": f.title, "category": f.category,
                    "severity": f.severity, "file_path": f.file_path,
                    "line_number": f.line_number, "app": p.name,
                })

        engine = IssuTriageEngine()
        body.triage_report = engine.triage(issues).to_dict()

    from app.refactor.batch_pipeline import BatchRemediationPipeline

    pipeline = BatchRemediationPipeline(
        project_root=body.project_path,
        max_workers=body.max_workers,
        dry_run=body.dry_run,
    )

    report = await pipeline.execute(body.triage_report, batch_filter=body.batch_filter)
    return report.to_dict()


@router.post("/scan-db")
async def scan_database(body: CSharpAnalyzeRequest, request: Request):
    """Analyze database integrity — missing FK, PII columns, schema issues."""
    _get_user_id(request)

    from app.refactor.db_analyzer import DatabaseIntegrityAnalyzer

    analyzer = DatabaseIntegrityAnalyzer(body.project_path)
    report = await analyzer.analyze()
    return report.to_dict()


@router.post("/scan-pii")
async def scan_pii(body: CSharpAnalyzeRequest, request: Request):
    """Scan codebase for personal data exposure (25 PII types)."""
    _get_user_id(request)

    from app.refactor.pii_scanner import PIIScanner

    scanner = PIIScanner(body.project_path)
    report = await scanner.scan()
    return report.to_dict()


class MultiLangScanRequest(BaseModel):
    project_path: str
    languages: list[str] | None = None  # None = all registered languages


@router.post("/scan-multilang")
async def scan_multilang(body: MultiLangScanRequest, request: Request):
    """Multi-language vulnerability scan — Python, VB.NET, and more.

    Complements `/analyze-csharp` by covering the languages it does not
    handle. Runs regex-based SQL injection, hardcoded-credential,
    weak-crypto, command-injection, suppressed-exception and info-leak
    detectors for each registered language.
    """
    _get_user_id(request)

    from app.refactor.multi_lang_scanner import MultiLangScanner

    scanner = MultiLangScanner(body.project_path, languages=body.languages)
    report = scanner.scan()
    return report.to_dict()


class StranglerPlanRequest(BaseModel):
    project_path: str
    name: str = ""
    format: str = "json"  # "json" or "markdown"


@router.post("/strangler-plan")
async def strangler_plan(body: StranglerPlanRequest, request: Request):
    """Produce a phased strangler-pattern migration plan for a legacy app.

    Ingests the target project, classifies modules by architectural role
    (controller / repository / service / shared / mainframe), and emits
    an ordered decomposition plan with per-phase risk, effort estimate,
    rollback strategy and stakeholder narrative. Mainframe components
    are always wrap-only, never rewritten.

    Response format:
      - "json" (default): StranglerPlan.to_dict()
      - "markdown": {"markdown": "<rendered plan>"}
    """
    _get_user_id(request)

    from app.refactor.strangler_planner import build_plan, render_markdown

    plan = await build_plan(body.project_path, body.name)
    if body.format.lower() == "markdown":
        return {"markdown": render_markdown(plan)}
    return plan.to_dict()


# ── Showcase endpoints (public — no auth required) ───────────────────────
#
# These serve static JSON fixtures representing pre-computed showcase
# tenants. They let the frontend render a polished "platform of the
# future" demo without running live scans. Anyone visiting /showcase
# on the frontend can browse the synthetic tenant-alpha results.


@router.get("/showcase")
async def list_showcase_tenants():
    """List the showcase tenants for which static reports are available."""
    if not _SHOWCASE_DATA_DIR.exists():
        return {"tenants": []}
    tenants = []
    for tenant_dir in sorted(_SHOWCASE_DATA_DIR.iterdir()):
        if not tenant_dir.is_dir():
            continue
        report_path = tenant_dir / "showcase_report.json"
        if not report_path.exists():
            continue
        try:
            data = json.loads(report_path.read_text(encoding="utf-8"))
            totals = data.get("totals", {})
            tenants.append({
                "tenant_id": tenant_dir.name,
                "apps": totals.get("apps", 0),
                "files": totals.get("files", 0),
                "lines_of_code": totals.get("lines_of_code", 0),
                "findings": totals.get("findings", 0),
                "risk_score": totals.get("risk_score", 0),
            })
        except (OSError, json.JSONDecodeError) as exc:
            logger.warning("Failed to read showcase report for %s: %s", tenant_dir.name, exc)
    return {"tenants": tenants}


@router.get("/showcase/{tenant_id}")
async def get_showcase_report(tenant_id: str):
    """Return the full showcase report JSON for one tenant."""
    # Guard against path traversal — tenant_id must be a plain directory name
    if "/" in tenant_id or ".." in tenant_id or "\\" in tenant_id:
        raise HTTPException(status_code=400, detail="Invalid tenant id")

    report_path = _SHOWCASE_DATA_DIR / tenant_id / "showcase_report.json"
    if not report_path.exists():
        raise HTTPException(status_code=404, detail="Tenant not found")
    try:
        return json.loads(report_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        logger.exception("Corrupt showcase report for %s", tenant_id)
        raise HTTPException(status_code=500, detail="Corrupt showcase report")


@router.get("/showcase/{tenant_id}/compliance")
async def get_compliance_profile(tenant_id: str):
    """Return the compliance countdown data for one tenant.

    Structured as a ComplianceProfile.to_dict() payload: hard_deadline,
    certifications, phases, audit_cadence and narrative. Frontend uses
    this to render a countdown card and a per-certification readiness
    widget on the /showcase page.
    """
    if "/" in tenant_id or ".." in tenant_id or "\\" in tenant_id:
        raise HTTPException(status_code=400, detail="Invalid tenant id")

    compliance_path = _SHOWCASE_DATA_DIR / tenant_id / "compliance.json"
    if not compliance_path.exists():
        raise HTTPException(status_code=404, detail="Compliance profile not found")
    try:
        return json.loads(compliance_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        logger.exception("Corrupt compliance profile for %s", tenant_id)
        raise HTTPException(status_code=500, detail="Corrupt compliance profile")


@router.get("/showcase/{tenant_id}/strangler/{app_codename}")
async def get_strangler_plan(tenant_id: str, app_codename: str):
    """Return the pre-computed strangler migration plan for a single app."""
    for component in (tenant_id, app_codename):
        if "/" in component or ".." in component or "\\" in component:
            raise HTTPException(status_code=400, detail="Invalid path component")

    plan_path = (
        _SHOWCASE_DATA_DIR / tenant_id / "strangler_plans" / f"{app_codename}.json"
    )
    if not plan_path.exists():
        raise HTTPException(status_code=404, detail="Strangler plan not found")
    try:
        return json.loads(plan_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        logger.exception("Corrupt strangler plan for %s/%s", tenant_id, app_codename)
        raise HTTPException(status_code=500, detail="Corrupt strangler plan")


@router.get("/status/{project_path:path}")
async def get_status(project_path: str, request: Request):
    """Check status of a refactoring job."""
    job = _jobs.get(project_path)
    if not job:
        return {"status": "not_found"}
    return {
        "status": "completed",
        "summary": job["report"]["summary"],
        "cost": job["report"]["cost"],
    }
