"""Refactoring API — ingest repos, auto-fix vulnerabilities, generate PRs.

Endpoints:
  POST /refactor/ingest         — Scan and map a repository
  POST /refactor/execute        — Run automated refactoring on ingested project
  POST /refactor/pr             — Generate PR from refactoring results
  GET  /refactor/status         — Check refactoring job status
  GET  /refactor/showcase       — List available showcase tenants (public)
  GET  /refactor/showcase/{id}  — Get showcase report for a tenant (public)
  GET  /refactor/showcase/{id}/strangler/{app} — Get strangler plan for app (public)
"""

import json
import logging
from pathlib import Path
from fastapi import APIRouter, Request, HTTPException
from pydantic import BaseModel
from typing import Optional

logger = logging.getLogger(__name__)

# Showcase data directory — static JSON fixtures committed to the repo so
# the /showcase endpoints work in production without needing synth_output/
# (which is gitignored). Fixtures are generated by
# backend/scripts/showcase_run.py + strangler_planner locally, then
# sanitized and copied here.
_SHOWCASE_DATA_DIR = Path(__file__).resolve().parents[2] / "showcase_data"

router = APIRouter(prefix="/refactor", tags=["refactor-engine"])


class IngestRequest(BaseModel):
    path: str                          # Local path or Git URL
    name: str = ""                     # Project name

class RefactorRequest(BaseModel):
    project_path: str                  # Path to ingested project
    fix_types: list[str] | None = None # Filter: ["sql_injection", "hardcoded_secret"]
    use_llm: bool = True               # Use LLM for complex fixes
    dry_run: bool = False              # Don't modify files
    max_parallel: int = 5              # Concurrent file processing

class PRRequest(BaseModel):
    project_path: str
    base_branch: str = "main"


def _get_user_id(request: Request) -> str:
    user = getattr(request.state, "user", None)
    if not user:
        raise HTTPException(status_code=401, detail="Login required")
    return user.get("sub", user.get("user_id", ""))


# In-memory job storage (replace with Redis for production)
_jobs: dict[str, dict] = {}


@router.post("/ingest")
async def ingest_repo(body: IngestRequest, request: Request):
    """Ingest a repository: scan, detect languages, build dependency graph."""
    _get_user_id(request)

    from app.auth.rate_limit import check_rate_limit
    await check_rate_limit(request)

    from app.refactor.ingestion import RepoIngestionEngine

    engine = RepoIngestionEngine()
    try:
        graph = await engine.ingest(body.path, body.name)
        return graph.to_dict()
    except FileNotFoundError:
        logger.info("Ingestion: path not found %s", body.path)
        raise HTTPException(status_code=404, detail="Repository path not found")
    except Exception:
        logger.exception("Ingestion failed")
        raise HTTPException(status_code=500, detail="Ingestion failed")


@router.post("/execute")
async def execute_refactoring(body: RefactorRequest, request: Request):
    """Execute automated refactoring on a project.

    Processes vulnerability hotspots in DAG order with parallel execution.
    """
    _get_user_id(request)

    from app.auth.rate_limit import check_rate_limit
    await check_rate_limit(request)

    from app.refactor.ingestion import RepoIngestionEngine
    from app.refactor.engine import RefactoringEngine

    # First ingest
    ingestion = RepoIngestionEngine()
    try:
        graph = await ingestion.ingest(body.project_path)
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Ingestion failed: {type(exc).__name__}")

    # Then refactor
    engine = RefactoringEngine(
        project_root=body.project_path,
        use_llm=body.use_llm,
        dry_run=body.dry_run,
    )

    report = await engine.refactor_project(
        graph=graph,
        fix_types=body.fix_types,
        max_parallel=body.max_parallel,
    )

    # M-3 (2026-04-25): key job storage by (user_id, project_path)
    # so two users analyzing `/tmp/foo` can't overwrite or read each
    # other's job. Was: keyed by `body.project_path` only — global
    # collision across tenants.
    user_id = _get_user_id(request)
    _jobs[f"{user_id}:{body.project_path}"] = {
        "graph": graph.to_dict(),
        "report": report.to_dict(),
    }

    return report.to_dict()


@router.post("/pr")
async def generate_pr(body: PRRequest, request: Request):
    """Generate a PR-ready branch from refactoring results."""
    user_id = _get_user_id(request)

    # M-3 (2026-04-25): jobs are user-scoped — see /execute above.
    job = _jobs.get(f"{user_id}:{body.project_path}")
    if not job:
        raise HTTPException(status_code=404, detail="No refactoring results found. Run /refactor/execute first.")

    from app.refactor.pr_generator import PRGenerator
    from app.refactor.engine import RefactorReport

    generator = PRGenerator(body.project_path)

    # Reconstruct report
    report_data = job["report"]
    report = RefactorReport(project_name=report_data["project"])
    report.files_fixed = report_data["summary"]["fixed"]
    report.vulnerabilities_fixed = report_data["summary"]["vulnerabilities_fixed"]
    report.tests_passing = report_data["summary"]["tests_passing"]
    report.files_failed = report_data["summary"]["failed"]
    report.total_cost_usd = report_data["cost"]["usd"]
    report.duration_ms = report_data["duration_ms"]

    result = await generator.generate_pr(report, base_branch=body.base_branch)
    return result


class TestGenRequest(BaseModel):
    project_path: str
    languages: list[str] | None = None  # Filter: ["python", "csharp"]
    dry_run: bool = False


@router.post("/generate-tests")
async def generate_tests(body: TestGenRequest, request: Request):
    """Auto-generate test files for codebases with zero test coverage."""
    _get_user_id(request)

    from app.auth.rate_limit import check_rate_limit
    await check_rate_limit(request)

    from app.refactor.ingestion import RepoIngestionEngine
    from app.refactor.test_generator import TestGeneratorEngine

    ingestion = RepoIngestionEngine()
    try:
        graph = await ingestion.ingest(body.project_path)
    except Exception:
        raise HTTPException(status_code=400, detail="Ingestion failed")

    generator = TestGeneratorEngine(
        project_root=body.project_path,
        dry_run=body.dry_run,
    )
    report = await generator.generate_tests(graph, languages=body.languages)
    return report.to_dict()


class MultiRepoRequest(BaseModel):
    repos: list[dict]              # [{"path": str, "name": str}, ...]
    fix_types: list[str] | None = None
    use_llm: bool = True
    dry_run: bool = False
    generate_tests: bool = True
    max_repos_parallel: int = 3


@router.post("/multi-repo")
async def multi_repo_refactor(body: MultiRepoRequest, request: Request):
    """Process multiple repositories in parallel — enterprise pipeline.

    Ingests all repos, builds cross-repo dependency map,
    refactors in safe order, generates tests, and produces consolidated report.
    """
    _get_user_id(request)

    from app.auth.rate_limit import check_rate_limit
    await check_rate_limit(request)

    from app.refactor.multi_repo import MultiRepoOrchestrator

    orchestrator = MultiRepoOrchestrator(
        use_llm=body.use_llm,
        dry_run=body.dry_run,
        max_repos_parallel=body.max_repos_parallel,
    )

    report = await orchestrator.process(
        repos=body.repos,
        fix_types=body.fix_types,
        generate_tests=body.generate_tests,
    )

    return report.to_dict()


class CSharpAnalyzeRequest(BaseModel):
    project_path: str


@router.post("/analyze-csharp")
async def analyze_csharp(body: CSharpAnalyzeRequest, request: Request):
    """Deep C#/.NET analysis — classes, vulnerabilities, god classes, auth gaps."""
    _get_user_id(request)

    from app.refactor.csharp_analyzer import CSharpAnalyzer

    analyzer = CSharpAnalyzer(body.project_path)
    projects = await analyzer.analyze()
    return [p.to_dict() for p in projects]


@router.post("/fix-csharp")
async def fix_csharp(body: CSharpAnalyzeRequest, request: Request):
    """Auto-fix SQL injection and hardcoded credentials in C# files."""
    _get_user_id(request)

    from app.refactor.csharp_analyzer import CSharpAnalyzer
    from app.refactor.csharp_fixer import CSharpFixer

    # First analyze
    analyzer = CSharpAnalyzer(body.project_path)
    projects = await analyzer.analyze()

    # Then fix files with findings
    fixer = CSharpFixer(body.project_path, dry_run=True)
    results = []
    for proj in projects:
        for finding in proj.findings:
            if finding.category in ("sql_injection", "hardcoded_cred"):
                result = fixer.fix_file(finding.file_path)
                if result.fixes_applied > 0:
                    results.append({
                        "file": result.file_path,
                        "fixes": result.fixes_applied,
                        "diff": result.diff_summary,
                        "details": result.fixes,
                    })
    return {"files_fixed": len(results), "results": results}


@router.post("/generate-cicd")
async def generate_cicd(body: CSharpAnalyzeRequest, request: Request):
    """Generate GitHub Actions CI/CD pipelines for .NET and Python projects."""
    _get_user_id(request)

    from app.refactor.csharp_analyzer import CSharpAnalyzer
    from app.refactor.cicd_generator import CICDGenerator

    analyzer = CSharpAnalyzer(body.project_path)
    projects = await analyzer.analyze()

    generator = CICDGenerator(body.project_path, dry_run=True)
    results = []
    for proj in projects:
        result = generator.generate_for_project(proj)
        results.append({
            "project": proj.name,
            "pipelines": result["pipelines"],
            "test_files": len(result["test_files"]),
        })
    return {"projects": len(results), "results": results}


@router.post("/scan-rpa")
async def scan_rpa(body: CSharpAnalyzeRequest, request: Request):
    """Scan RPA code for fragile Playwright selectors and stability issues."""
    _get_user_id(request)

    from app.refactor.rpa_scanner import RPAScanner

    scanner = RPAScanner(body.project_path)
    report = await scanner.scan()
    return report.to_dict()


class TriageRequest(BaseModel):
    project_path: str
    issues: list[dict] = []        # Pre-loaded issues, or empty to scan from code
    apps: list[str] | None = None  # Filter to specific apps


@router.post("/triage")
async def triage_issues(body: TriageRequest, request: Request):
    """Prioritize issues into remediation batches (handles 166K+ issues)."""
    _get_user_id(request)

    from app.refactor.triage import IssuTriageEngine

    engine = IssuTriageEngine()

    # If no pre-loaded issues, generate from code analysis
    if not body.issues:
        from app.refactor.ingestion import RepoIngestionEngine
        from app.refactor.csharp_analyzer import CSharpAnalyzer

        ingestion = RepoIngestionEngine()
        graph = await ingestion.ingest(body.project_path)

        issues = []
        # Add ingestion hotspots as issues
        for h in graph.vulnerability_hotspots:
            issues.append({
                "title": f"Vulnerability in {h['file']}",
                "category": "code_quality",
                "severity": "high" if h["vulnerabilities"] > 2 else "medium",
                "file_path": h["file"],
                "app": "",
            })

        # Add C# findings
        analyzer = CSharpAnalyzer(body.project_path)
        projects = await analyzer.analyze()
        for p in projects:
            for f in p.findings:
                issues.append({
                    "title": f.title,
                    "category": f.category,
                    "severity": f.severity,
                    "cwe": f.cwe,
                    "file_path": f.file_path,
                    "line_number": f.line_number,
                    "app": p.name,
                })

        body.issues = issues

    report = engine.triage(body.issues, apps=body.apps)
    return report.to_dict()


class BatchRequest(BaseModel):
    project_path: str
    triage_report: dict = {}       # Pre-computed triage, or empty to auto-triage
    batch_filter: list[int] | None = None  # [1, 2] = only critical batches
    max_workers: int = 4
    dry_run: bool = True


@router.post("/batch-remediate")
async def batch_remediate(body: BatchRequest, request: Request):
    """Execute batch remediation pipeline — 500+ fixes/hour target."""
    _get_user_id(request)

    from app.auth.rate_limit import check_rate_limit
    await check_rate_limit(request)

    # Auto-triage if no pre-computed report
    if not body.triage_report:
        from app.refactor.triage import IssuTriageEngine
        from app.refactor.ingestion import RepoIngestionEngine
        from app.refactor.csharp_analyzer import CSharpAnalyzer

        ingestion = RepoIngestionEngine()
        graph = await ingestion.ingest(body.project_path)

        issues = []
        for h in graph.vulnerability_hotspots:
            issues.append({
                "title": f"Vulnerability in {h['file']}",
                "category": "code_quality",
                "severity": "high" if h["vulnerabilities"] > 2 else "medium",
                "file_path": h["file"],
            })

        analyzer = CSharpAnalyzer(body.project_path)
        for p in await analyzer.analyze():
            for f in p.findings:
                issues.append({
                    "title": f.title, "category": f.category,
                    "severity": f.severity, "file_path": f.file_path,
                    "line_number": f.line_number, "app": p.name,
                })

        engine = IssuTriageEngine()
        body.triage_report = engine.triage(issues).to_dict()

    from app.refactor.batch_pipeline import BatchRemediationPipeline

    pipeline = BatchRemediationPipeline(
        project_root=body.project_path,
        max_workers=body.max_workers,
        dry_run=body.dry_run,
    )

    report = await pipeline.execute(body.triage_report, batch_filter=body.batch_filter)
    return report.to_dict()


@router.post("/scan-db")
async def scan_database(body: CSharpAnalyzeRequest, request: Request):
    """Analyze database integrity — missing FK, PII columns, schema issues."""
    _get_user_id(request)

    from app.refactor.db_analyzer import DatabaseIntegrityAnalyzer

    analyzer = DatabaseIntegrityAnalyzer(body.project_path)
    report = await analyzer.analyze()
    return report.to_dict()


@router.post("/scan-pii")
async def scan_pii(body: CSharpAnalyzeRequest, request: Request):
    """Scan codebase for personal data exposure (25 PII types)."""
    _get_user_id(request)

    from app.refactor.pii_scanner import PIIScanner

    scanner = PIIScanner(body.project_path)
    report = await scanner.scan()
    return report.to_dict()


class MultiLangScanRequest(BaseModel):
    project_path: str
    languages: list[str] | None = None  # None = all registered languages


@router.post("/scan-multilang")
async def scan_multilang(body: MultiLangScanRequest, request: Request):
    """Multi-language vulnerability scan — Python, VB.NET, and more.

    Complements `/analyze-csharp` by covering the languages it does not
    handle. Runs regex-based SQL injection, hardcoded-credential,
    weak-crypto, command-injection, suppressed-exception and info-leak
    detectors for each registered language.
    """
    _get_user_id(request)

    from app.refactor.multi_lang_scanner import MultiLangScanner

    scanner = MultiLangScanner(body.project_path, languages=body.languages)
    report = scanner.scan()
    return report.to_dict()


class GenerateObservabilityRequest(BaseModel):
    out_dir: str
    service_name: str = "my-service"


@router.post("/generate-observability")
async def generate_observability_endpoint(
    body: GenerateObservabilityRequest, request: Request
):
    """Emit an observability bootstrap bundle.

    Produces SLO definitions (latency + availability), Prometheus
    scrape config and multi-window multi-burn-rate alerting rules,
    Grafana dashboards (golden signals + error budget), an OTel
    Collector config covering traces + metrics + logs, language-
    specific instrumentation guides (Python/FastAPI, .NET/ASP.NET
    Core), runbook templates, and a docker-compose for running the
    stack locally. 16 files per bundle, ready to commit to a repo.
    """
    _get_user_id(request)

    from pathlib import Path as _Path

    from app.refactor.observability_bootstrapper import generate_observability_bundle

    result = generate_observability_bundle(
        out_dir=_Path(body.out_dir),
        service_name=body.service_name,
    )
    return result.to_dict()


class GenerateGitflowRequest(BaseModel):
    out_dir: str


@router.post("/generate-gitflow")
async def generate_gitflow_endpoint(body: GenerateGitflowRequest, request: Request):
    """Emit a GitFlow governance bundle.

    Generates a drop-in package with CODEOWNERS, PR/issue templates,
    GitHub Actions workflows (PR title check, CODEOWNERS review gate,
    daily branch-protection audit) and docs for the dual-branch
    application + infrastructure flow. All values are placeholders
    that teams replace with real GitHub team slugs before using.
    """
    _get_user_id(request)

    from pathlib import Path as _Path

    from app.refactor.gitflow_generator import generate_gitflow_bundle

    result = generate_gitflow_bundle(_Path(body.out_dir))
    return result.to_dict()


class ComplianceMiddlewareRequest(BaseModel):
    out_dir: str
    target: str = "both"  # python / dotnet / both


@router.post("/generate-compliance-middleware")
async def generate_compliance_middleware_endpoint(
    body: ComplianceMiddlewareRequest, request: Request
):
    """Emit a drop-in compliance middleware package.

    Generates self-contained templates for Segregation of Duties,
    transactional audit logging, global exception handling, RBAC
    with scope enforcement, and PII masking — in Python (FastAPI),
    .NET (ASP.NET Core), or both. Use as a starting point for teams
    that need the five compliance controls at once.
    """
    _get_user_id(request)

    from pathlib import Path as _Path

    from app.refactor.compliance_enforcer import generate_compliance_middleware

    try:
        result = generate_compliance_middleware(
            out_dir=_Path(body.out_dir),
            target=body.target,
        )
    except ValueError:
        logger.warning("Compliance middleware: invalid request", exc_info=True)
        raise HTTPException(
            status_code=400,
            detail="Invalid compliance middleware request",
        )
    return result.to_dict()


class GenerateIacRequest(BaseModel):
    project_path: str
    out_dir: str
    cloud: str = "aws"
    app_name: str | None = None


@router.post("/generate-iac")
async def generate_iac_endpoint(body: GenerateIacRequest, request: Request):
    """Emit a full IaC bundle (Terraform + Helm + kustomize overlays).

    Ingests the target project to pick sensible defaults (e.g., include
    a managed SQL module when the codebase uses SQL), then renders an
    AWS baseline Terraform module, a Helm chart with templates, and
    dev/staging/prod kustomize overlays. All secrets are referenced,
    never inlined; all placeholders are obviously fake so a
    misconfigured apply fails loudly rather than using a dev default.
    """
    _get_user_id(request)

    from pathlib import Path as _Path

    from app.refactor.ingestion import RepoIngestionEngine
    from app.refactor.iac_generator import generate_iac

    graph = await RepoIngestionEngine().ingest(
        body.project_path, body.app_name or ""
    )
    result = generate_iac(
        graph,
        out_dir=_Path(body.out_dir),
        cloud=body.cloud,
        app_name=body.app_name,
    )
    return result.to_dict()


class CobolAnalyzeRequest(BaseModel):
    project_path: str


@router.post("/analyze-cobol")
async def analyze_cobol(body: CobolAnalyzeRequest, request: Request):
    """Scan a project tree for COBOL programs and JCL jobs.

    Returns a structured report with PROGRAM-IDs, file bindings,
    JCL steps, copybooks, plus findings for hardcoded credentials,
    hardcoded dataset paths, Y2K-style dates, missing error handlers
    and oversized PIC widths.
    """
    _get_user_id(request)

    from app.refactor.cobol_scanner import scan_cobol

    report = await scan_cobol(body.project_path)
    return report.to_dict()


class CobolWrapRequest(BaseModel):
    project_path: str
    out_dir: str


@router.post("/wrap-cobol")
async def wrap_cobol(body: CobolWrapRequest, request: Request):
    """Generate a FastAPI wrapper project for the COBOL code at project_path.

    Runs the scanner first, then renders one REST endpoint per
    PROGRAM-ID into `out_dir`. The wrapper does not modify the COBOL
    source — it shells out to the existing JCL via subprocess. This
    is the strangler-pattern "wrap, do not rewrite" realization for
    mainframe components.
    """
    _get_user_id(request)

    from pathlib import Path as _Path

    from app.refactor.cobol_scanner import scan_cobol
    from app.refactor.cobol_wrapper_generator import generate_wrapper

    report = await scan_cobol(body.project_path)
    if not report.programs:
        raise HTTPException(
            status_code=400,
            detail="No COBOL programs found at project_path",
        )
    result = generate_wrapper(report, _Path(body.out_dir))
    return result.to_dict()


class KnowledgeTransferRequest(BaseModel):
    project_path: str
    app_name: str = ""
    include_git_history: bool = True


@router.post("/knowledge-transfer")
async def knowledge_transfer_route(body: KnowledgeTransferRequest, request: Request):
    """Gap 12 — Post-modernization knowledge transfer agent.

    Walks an app, ingests its documentation bundle (from Gap 8 +
    pre-existing markdown) and a slice of git history, builds a
    structured Q&A index with citations, and returns the full report
    including an onboarding walkthrough.

    Use the companion ``/knowledge-query`` endpoint to ask individual
    questions against the index.
    """
    _get_user_id(request)

    from app.refactor.knowledge_transfer_agent import run_knowledge_transfer

    app_name = body.app_name or _Path(body.project_path).name or "unknown-app"
    report = run_knowledge_transfer(
        app_name=app_name,
        app_path=body.project_path,
        include_git_history=body.include_git_history,
    )
    return report.to_dict()


class KnowledgeQueryRequest(BaseModel):
    project_path: str
    app_name: str = ""
    query: str
    top_n: int = 5
    include_git_history: bool = True


@router.post("/knowledge-query")
async def knowledge_query_route(body: KnowledgeQueryRequest, request: Request):
    """Gap 12 — Query the knowledge transfer index.

    Builds the index (or refreshes it) and runs a natural-language
    query against it, returning the top-N matching entries with
    citations. Deterministic keyword ranking, no LLM calls.
    """
    _get_user_id(request)

    from app.refactor.knowledge_transfer_agent import (
        query_knowledge,
        run_knowledge_transfer,
    )

    app_name = body.app_name or _Path(body.project_path).name or "unknown-app"
    report = run_knowledge_transfer(
        app_name=app_name,
        app_path=body.project_path,
        include_git_history=body.include_git_history,
    )
    response = query_knowledge(report, body.query, top_n=body.top_n)
    return response.to_dict()


class GenerateDocsRequest(BaseModel):
    project_path: str
    app_name: str = ""
    write_to_disk: bool = False
    output_dir: str | None = None
    overwrite: bool = False


@router.post("/generate-docs")
async def generate_docs_route(body: GenerateDocsRequest, request: Request):
    """Gap 8 — AI-powered documentation generator.

    Walks a legacy codebase, infers the stack + entry points + HTTP
    endpoints + external integrations + top-level modules, and produces
    a canonical documentation bundle: README.md, ARCHITECTURE.md (with
    C4 Context/Container/Component Mermaid diagrams), ADR-0001-initial-
    architecture.md, RUNBOOK.md, API.md, and INTEGRATIONS.md.

    Purely additive. Never modifies source code. Existing doc files are
    NOT overwritten unless ``overwrite=True``.

    Response: DocGenerationReport.to_dict() — includes the full rendered
    content of every generated file under the ``files`` key, plus
    ``written_to_disk`` (absolute paths of files actually written) and
    ``warnings`` (any skipped writes).
    """
    _get_user_id(request)

    from app.refactor.docs_generator import generate_docs

    app_name = body.app_name or _Path(body.project_path).name or "unknown-app"
    report = generate_docs(
        app_name=app_name,
        app_path=body.project_path,
        write_to_disk=body.write_to_disk,
        output_dir=body.output_dir,
        overwrite=body.overwrite,
    )
    return report.to_dict()


class DataPipelinePlanRequest(BaseModel):
    project_path: str
    app_name: str = ""
    format: str = "json"  # "json" or "markdown"


@router.post("/plan-data-pipelines")
async def plan_data_pipelines(body: DataPipelinePlanRequest, request: Request):
    """Gap 6 — Data pipeline modernization planner.

    Walks a legacy codebase, detects flat-file batch ingestion, cron
    schedulers, manual triggers, FTP transfers, DB bulk inserts, and
    absence of streaming infrastructure. Produces a phased modernization
    plan recommending AWS-native replacements (S3 + Lambda, EventBridge
    Scheduler, Transfer Family, Kinesis / MSK, DMS) with rationale,
    effort, risk, and rollback strategy per step.

    Detection-only — this route does not modify code or provision
    infrastructure. Downstream consumers of the plan are the IaC
    generator (Gap 4) for scaffolding and the compliance enforcer
    (Gap 7) for wrapping the new pipelines with encryption.

    Response format:
      - "json" (default): DataPipelinePlan.to_dict()
      - "markdown": {"markdown": "<rendered plan>"}
    """
    _get_user_id(request)

    from app.refactor.data_pipeline_planner import (
        plan_data_pipelines as _plan,
        render_markdown,
    )

    app_name = body.app_name or _Path(body.project_path).name or "unknown-app"
    plan = _plan(app_name=app_name, app_path=body.project_path)

    if body.format.lower() == "markdown":
        return {"markdown": render_markdown(plan)}
    return plan.to_dict()


class StranglerPlanRequest(BaseModel):
    project_path: str
    name: str = ""
    format: str = "json"  # "json" or "markdown"


@router.post("/strangler-plan")
async def strangler_plan(body: StranglerPlanRequest, request: Request):
    """Produce a phased strangler-pattern migration plan for a legacy app.

    Ingests the target project, classifies modules by architectural role
    (controller / repository / service / shared / mainframe), and emits
    an ordered decomposition plan with per-phase risk, effort estimate,
    rollback strategy and stakeholder narrative. Mainframe components
    are always wrap-only, never rewritten.

    Response format:
      - "json" (default): StranglerPlan.to_dict()
      - "markdown": {"markdown": "<rendered plan>"}
    """
    _get_user_id(request)

    from app.refactor.strangler_planner import build_plan, render_markdown

    plan = await build_plan(body.project_path, body.name)
    if body.format.lower() == "markdown":
        return {"markdown": render_markdown(plan)}
    return plan.to_dict()


# ── Showcase endpoints (public — no auth required) ───────────────────────
#
# These serve showcase pipeline output with a two-layer read strategy:
#   1. DB first: the latest row from showcase_runs (populated by the
#      persist_showcase script or a live pipeline run)
#   2. Static fallback: backend/showcase_data/<tenant>/ JSON fixtures
#      committed to the repo, used when the DB has no row for that
#      tenant yet.
#
# The switch is transparent to the frontend — the same endpoint shape
# is returned in both cases. This keeps /showcase working in fresh
# environments (no DB data yet) and upgrades cleanly once real runs
# land in the database.


async def _latest_db_run(tenant_slug: str):
    """Return the latest persisted run for a tenant, or None on any DB error."""
    try:
        from app.showcase import storage
        return await storage.latest_run(tenant_slug)
    except Exception as exc:  # pragma: no cover — defensive
        logger.warning("showcase DB read failed for %s: %s", tenant_slug, exc)
        return None


def _static_report(tenant_id: str) -> dict | None:
    """Load the static showcase_report.json for a tenant if present."""
    report_path = _SHOWCASE_DATA_DIR / tenant_id / "showcase_report.json"
    if not report_path.exists():
        return None
    try:
        return json.loads(report_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        logger.exception("Corrupt showcase report for %s", tenant_id)
        return None


def _static_compliance(tenant_id: str) -> dict | None:
    """Load the static compliance.json for a tenant if present."""
    path = _SHOWCASE_DATA_DIR / tenant_id / "compliance.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        logger.exception("Corrupt compliance profile for %s", tenant_id)
        return None


def _static_strangler_plan(tenant_id: str, app_codename: str) -> dict | None:
    """Load the static strangler_plans/<app>.json for a tenant if present."""
    path = (
        _SHOWCASE_DATA_DIR / tenant_id / "strangler_plans" / f"{app_codename}.json"
    )
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        logger.exception(
            "Corrupt strangler plan for %s/%s", tenant_id, app_codename
        )
        return None


@router.get("/showcase")
async def list_showcase_tenants():
    """List the showcase tenants visible to the /showcase frontend.

    Combines persisted tenants (from showcase_runs) with static fixture
    tenants (from backend/showcase_data/). A tenant that exists in both
    places is listed once, using DB data, with ``source = 'db'``.
    """
    tenants: dict[str, dict] = {}

    # 1. Persisted tenants
    try:
        from app.showcase import storage
        for summary in await storage.list_tenants():
            slug = summary["tenant_slug"]
            run = await storage.latest_run(slug)
            if not run or not run.get("report"):
                continue
            totals = run["report"].get("totals", {})
            tenants[slug] = {
                "tenant_id": slug,
                "apps": totals.get("apps", 0),
                "files": totals.get("files", 0),
                "lines_of_code": totals.get("lines_of_code", 0),
                "findings": totals.get("findings", 0),
                "risk_score": totals.get("risk_score", 0),
                "source": "db",
                "latest_run_at": summary.get("latest_generated_at"),
                "run_count": summary.get("run_count", 1),
            }
    except Exception as exc:  # pragma: no cover — defensive
        logger.warning("showcase list from DB failed: %s", exc)

    # 2. Static fallback for anything not already listed
    if _SHOWCASE_DATA_DIR.exists():
        for tenant_dir in sorted(_SHOWCASE_DATA_DIR.iterdir()):
            if not tenant_dir.is_dir():
                continue
            slug = tenant_dir.name
            if slug in tenants:
                continue
            data = _static_report(slug)
            if data is None:
                continue
            totals = data.get("totals", {})
            tenants[slug] = {
                "tenant_id": slug,
                "apps": totals.get("apps", 0),
                "files": totals.get("files", 0),
                "lines_of_code": totals.get("lines_of_code", 0),
                "findings": totals.get("findings", 0),
                "risk_score": totals.get("risk_score", 0),
                "source": "static",
            }

    return {"tenants": sorted(tenants.values(), key=lambda t: t["tenant_id"])}


@router.get("/showcase/{tenant_id}")
async def get_showcase_report(tenant_id: str):
    """Return the full showcase report for one tenant.

    Prefers the latest persisted run from showcase_runs; falls back to
    the static fixture under backend/showcase_data when the DB has no
    row for this tenant.
    """
    if "/" in tenant_id or ".." in tenant_id or "\\" in tenant_id:
        raise HTTPException(status_code=400, detail="Invalid tenant id")

    run = await _latest_db_run(tenant_id)
    if run and run.get("report"):
        return run["report"]

    static = _static_report(tenant_id)
    if static is None:
        raise HTTPException(status_code=404, detail="Tenant not found")
    return static


def _static_commercial_risk(tenant_id: str) -> dict | None:
    """Load the static commercial_risk.json for a tenant if present."""
    path = _SHOWCASE_DATA_DIR / tenant_id / "commercial_risk.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        logger.exception("Corrupt commercial_risk profile for %s", tenant_id)
        return None


def _static_governance(tenant_id: str) -> dict | None:
    """Load the static governance.json for a tenant if present."""
    path = _SHOWCASE_DATA_DIR / tenant_id / "governance.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        logger.exception("Corrupt governance profile for %s", tenant_id)
        return None


@router.get("/showcase/{tenant_id}/report-out")
async def get_report_out(tenant_id: str):
    """Return the rendered Report Out markdown for one tenant.

    Assembles a single-document stakeholder deliverable from the
    tenant's showcase report, strangler plans, compliance, commercial
    risk and governance data. Prefers DB-persisted payloads when
    available, falling back to the static fixtures in
    backend/showcase_data/.
    """
    if "/" in tenant_id or ".." in tenant_id or "\\" in tenant_id:
        raise HTTPException(status_code=400, detail="Invalid tenant id")

    from app.showcase import report_out as _ro

    report = None
    compliance = None
    commercial_risk = None
    governance = None
    strangler_plans: dict[str, dict] = {}

    run = await _latest_db_run(tenant_id)
    if run:
        rep = run.get("report") or {}
        if rep:
            report = rep
            # Governance and commercial risk live inside the persisted
            # report payload when present.
            if isinstance(rep.get("governance"), dict):
                governance = rep["governance"]
            if isinstance(rep.get("commercial_risk"), dict):
                commercial_risk = rep["commercial_risk"]
        if run.get("compliance"):
            compliance = run["compliance"]
        plans = run.get("strangler_plans") or {}
        if isinstance(plans, dict):
            strangler_plans = plans

    if report is None:
        report = _static_report(tenant_id)
    if compliance is None:
        compliance = _static_compliance(tenant_id)
    if commercial_risk is None:
        commercial_risk = _static_commercial_risk(tenant_id)
    if governance is None:
        governance = _static_governance(tenant_id)
    if not strangler_plans:
        plans_dir = _SHOWCASE_DATA_DIR / tenant_id / "strangler_plans"
        if plans_dir.is_dir():
            for plan_file in sorted(plans_dir.glob("*.json")):
                try:
                    strangler_plans[plan_file.stem] = json.loads(
                        plan_file.read_text(encoding="utf-8")
                    )
                except json.JSONDecodeError:
                    logger.warning(
                        "Corrupt strangler plan file %s", plan_file.name
                    )

    if report is None:
        raise HTTPException(status_code=404, detail="Tenant not found")

    markdown = _ro.render(
        tenant_id=tenant_id,
        report=report,
        compliance=compliance,
        commercial_risk=commercial_risk,
        governance=governance,
        strangler_plans=strangler_plans,
    )
    return {"tenant_id": tenant_id, "markdown": markdown}


@router.get("/showcase/{tenant_id}/governance")
async def get_governance_profile(tenant_id: str):
    """Return the governance metadata for one tenant.

    Payload describes steering committee cadence, delivery teams,
    code access gate and the post-launch tech lead slot. All names
    are generic role labels, no real people or firms. DB-first
    strategy with static fallback, like the other showcase endpoints.
    """
    if "/" in tenant_id or ".." in tenant_id or "\\" in tenant_id:
        raise HTTPException(status_code=400, detail="Invalid tenant id")

    run = await _latest_db_run(tenant_id)
    if run:
        report = run.get("report") or {}
        if "governance" in report and report["governance"]:
            return report["governance"]

    static = _static_governance(tenant_id)
    if static is None:
        raise HTTPException(
            status_code=404, detail="Governance profile not found"
        )
    return static


@router.get("/showcase/{tenant_id}/commercial-risk")
async def get_commercial_risk_profile(tenant_id: str):
    """Return the commercial risk metadata for one tenant.

    Mirrors the compliance endpoint shape: tries the latest persisted
    run first, then falls back to the static commercial_risk.json
    fixture. Payload includes vendor concentration, contract coverage
    gaps and penalty exposure, all with generic codenames.
    """
    if "/" in tenant_id or ".." in tenant_id or "\\" in tenant_id:
        raise HTTPException(status_code=400, detail="Invalid tenant id")

    run = await _latest_db_run(tenant_id)
    if run:
        report = run.get("report") or {}
        if "commercial_risk" in report and report["commercial_risk"]:
            return report["commercial_risk"]

    static = _static_commercial_risk(tenant_id)
    if static is None:
        raise HTTPException(
            status_code=404, detail="Commercial risk profile not found"
        )
    return static


@router.get("/showcase/{tenant_id}/ecosystem")
async def get_ecosystem_posture(tenant_id: str):
    """Return ecosystem health + security posture for one tenant.

    Combines P-021 (EcosystemMetrics: total LOC, issues, risk exposure,
    per-app density, priority hints) with P-009/P-010/P-011 (exposure,
    edge security, secret management) + P-020 (legal risk) into a single
    payload consumed by the frontend ``TenantShowcase`` ecosystem card.

    Only the canonical ``tenant-alpha`` fixture is wired today — other
    tenant ids return 404 until their fixtures exist.
    """
    if "/" in tenant_id or ".." in tenant_id or "\\" in tenant_id:
        raise HTTPException(status_code=400, detail="Invalid tenant id")

    try:
        from app.synth.ecosystem_metrics import load_ecosystem_metrics
        from app.synth.profile import load_profile
    except ImportError as exc:
        logger.warning("Ecosystem posture endpoint: import failed: %s", exc)
        raise HTTPException(status_code=503, detail="Ecosystem data unavailable")

    metrics = load_ecosystem_metrics()
    if not metrics.is_loaded() or metrics.tenant_id != tenant_id:
        raise HTTPException(
            status_code=404, detail="Ecosystem posture not found for this tenant"
        )

    # Load the tenant profile to get security posture (edge/secret/legal)
    from pathlib import Path
    fixture_path = (
        Path(__file__).parent.parent
        / "synth"
        / "fixtures"
        / f"{tenant_id.replace('-', '_')}.yaml"
    )
    profile = None
    if fixture_path.exists():
        try:
            profile = load_profile(fixture_path)
        except Exception as exc:  # pragma: no cover — defensive
            logger.warning("Failed to load profile fixture %s: %s", fixture_path, exc)

    payload: dict = {
        "tenant_id": metrics.tenant_id,
        "version": metrics.version,
        "ecosystem": {
            "total_loc": metrics.total_loc,
            "total_apps": metrics.total_apps,
            "total_components": metrics.total_components,
            "total_issues": metrics.total_issues,
            "satellite_issues": metrics.satellite_issues,
            "core_cobol_issues": metrics.core_cobol_issues,
            "critical_issues": metrics.critical_issues,
            "critical_density_pct": metrics.critical_density_pct,
            "apps_without_tests": metrics.apps_without_tests,
            "apps_without_cicd": metrics.apps_without_cicd,
            "sql_concat_queries": metrics.sql_concat_queries,
            "tables_without_fk_pct": metrics.tables_without_fk_pct,
            "pii_items": metrics.pii_items,
            "pii_inputs": metrics.pii_inputs,
            "db_growth_monthly_pct": metrics.db_growth_monthly_pct,
        },
        "risk_exposure_usd": {
            "reputational": metrics.risk_reputational_usd,
            "pii": metrics.risk_pii_usd,
            "integrity": metrics.risk_integrity_usd,
            "total": metrics.risk_total_usd,
            "basis": metrics.risk_basis,
        },
        "commercial": {
            "facturacion_usd": metrics.commercial.facturacion_usd,
            "contract_coverage_pct": metrics.commercial.contract_coverage_pct,
            "uncovered_spend_usd": metrics.commercial.uncovered_spend_usd,
            "invoices_total": metrics.commercial.invoices_total,
            "contracts_total": metrics.commercial.contracts_total,
            "paraguas_contract_name": metrics.commercial.paraguas_contract_name,
            "paraguas_contract_signed_year": metrics.commercial.paraguas_contract_signed_year,
            "client_revenue_share_of_vendor_pct": metrics.commercial.client_revenue_share_of_vendor_pct,
        },
        "legal": {
            "nda_signed_date": metrics.legal.nda_signed_date,
            "nda_status": metrics.legal.nda_status,
            "renewal_required_before_transfer": metrics.legal.renewal_required_before_transfer,
            "nda_notes": metrics.legal.nda_notes,
        },
        "per_app": [
            {
                "app": a.app, "label": a.label,
                "total_issues": a.total_issues,
                "critical_issues": a.critical_issues,
                "high_issues": a.high_issues,
                "blocker_issues": a.blocker_issues,
                "critical_density_pct": a.critical_density_pct,
                "hosting": a.hosting,
                "notes": a.notes,
            }
            for a in metrics.per_app
        ],
        "priority_hints": [
            {"app": p.app, "priority_score": p.priority_score, "rationale": p.rationale}
            for p in metrics.ranked_by_priority()
        ],
    }

    # Security posture from the tenant profile (edge security, secret mgmt)
    if profile is not None:
        ir = profile.infrastructure_risk
        if ir is not None and ir.edge_security is not None:
            payload["edge_security"] = {
                "waf_present": ir.edge_security.waf_present,
                "waf_provider": ir.edge_security.waf_provider,
                "geo_blocking": ir.edge_security.geo_blocking,
                "pattern_rules": ir.edge_security.pattern_rules,
                "scan_cadence": ir.edge_security.scan_cadence,
                "remediation_channel": ir.edge_security.remediation_channel,
            }
        sm = profile.secret_management
        if sm is not None:
            payload["secret_management"] = {
                "product": sm.product,
                "internal_alias": sm.internal_alias,
                "scope": sm.scope,
                "rotation_policy": sm.rotation_policy,
                "hash_based_injection": sm.hash_based_injection,
                "on_premise": sm.on_premise,
                "rotates_users": sm.rotates_users,
                "rotates_db_creds": sm.rotates_db_creds,
            }

    return payload


@router.get("/showcase/{tenant_id}/compliance")
async def get_compliance_profile(tenant_id: str):
    """Return the compliance countdown data for one tenant.

    Structured as a ComplianceProfile.to_dict() payload: hard_deadline,
    certifications, phases, audit_cadence and narrative. Prefers the
    persisted run; falls back to the static compliance.json fixture.
    """
    if "/" in tenant_id or ".." in tenant_id or "\\" in tenant_id:
        raise HTTPException(status_code=400, detail="Invalid tenant id")

    run = await _latest_db_run(tenant_id)
    if run and run.get("compliance"):
        return run["compliance"]

    static = _static_compliance(tenant_id)
    if static is None:
        raise HTTPException(status_code=404, detail="Compliance profile not found")
    return static


@router.get("/showcase/{tenant_id}/strangler/{app_codename}")
async def get_strangler_plan(tenant_id: str, app_codename: str):
    """Return the pre-computed strangler migration plan for a single app.

    DB-first: if the tenant has a persisted run whose strangler_plans
    blob contains this app_codename, that plan is returned. Otherwise
    the static fixture at
    ``backend/showcase_data/<tenant>/strangler_plans/<app>.json`` is
    used as a fallback.
    """
    for component in (tenant_id, app_codename):
        if "/" in component or ".." in component or "\\" in component:
            raise HTTPException(status_code=400, detail="Invalid path component")

    run = await _latest_db_run(tenant_id)
    if run:
        plans = run.get("strangler_plans") or {}
        if app_codename in plans and plans[app_codename]:
            return plans[app_codename]

    static = _static_strangler_plan(tenant_id, app_codename)
    if static is None:
        raise HTTPException(status_code=404, detail="Strangler plan not found")
    return static


@router.get("/status/{project_path:path}")
async def get_status(project_path: str, request: Request):
    """Check status of a refactoring job."""
    job = _jobs.get(project_path)
    if not job:
        return {"status": "not_found"}
    return {
        "status": "completed",
        "summary": job["report"]["summary"],
        "cost": job["report"]["cost"],
    }
