"""Cyclomatic complexity injection (Batch 3 follow-up).

Real enterprise legacy codebases consistently have a handful of
"god methods" with cyclomatic complexity in the 100+ range — one
master function that switched every business rule over decades of
hot-fixes. This module renders a deterministic C# class containing
one such method so the refactor engine's god-class detector trips
on the synthetic tenant at the same scale as the real profile.

The scoring model matches ``backend/app/refactor/csharp_analyzer.py``:
each ``if / else / switch / case / for / foreach / while / do /
catch / && / ||`` token adds 1 to the class-level complexity score.
We target a specific cyclomatic number by emitting exactly that many
``else if`` branches inside a single method body, plus a small tail
of logical operators for realism.

Usage:

    from app.synth.complexity import render_god_class
    code = render_god_class(
        class_name="LegacyRuleRouter",
        namespace="App01.LegacyCore",
        target_cc=150,
        rng=random.Random(42),
    )
"""
from __future__ import annotations

import random


HEADER_TEMPLATE = """// ---------------------------------------------------------------------------
// {class_name} - god class generated by NexusForge synth
//
// Demonstrates a legacy business-rule dispatcher with cyclomatic
// complexity around {target_cc}. Each branch maps an input value to a
// hand-written side-effect, which is how real enterprise legacy code
// accumulates - every new business rule adds another chained branch
// instead of a strategy table.
//
// The refactor engine's god-class detector (complexity > 20) should
// flag this class on the first scan.
// ---------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace {namespace}
{{
    public class {class_name}
    {{
        private readonly Dictionary<string, int> _counters = new Dictionary<string, int>();

"""


FOOTER = """        }
    }
}
"""


def _branch_body(index: int, table: str) -> str:
    """One branch body — modest work, no complexity-adding keywords.

    Carefully avoids ``if / else / switch / case / for / foreach /
    while / do / catch / && / ||`` so the only CC contribution from
    this branch comes from the surrounding ``else if`` token itself.
    """
    return (
        f"                var key{index:03d} = \"rule_\" + ruleCode;\n"
        f"                _counters[key{index:03d}] = 1 + "
        f"(_counters.TryGetValue(key{index:03d}, out var v{index:03d}) "
        f"? v{index:03d} : 0);\n"
        f"                var result{index:03d} = ProcessRule{index:03d}"
        f"(payload, ruleCode);\n"
        f"                Logger.Info(\"handled \" + key{index:03d});\n"
    )


def render_god_class(
    class_name: str,
    namespace: str,
    target_cc: int,
    rng: random.Random,
) -> str:
    """Produce a single C# file containing one method with target CC.

    Scoring model (matches csharp_analyzer.py):
      - 1 leading ``if``                                     (+1)
      - each ``else if`` chain link                          (+2, because
        the analyzer counts ``else`` and ``if`` separately)
      - each ``&&`` or ``||`` in a condition                 (+1)
      - 1 trailing ``else`` catch-all                        (+1)

    So to hit exactly ``target_cc`` we pick:

        branches = max(0, (target_cc - 2) // 2)       # leading if + final else
        leftover = target_cc - 2 - (branches * 2)     # fill with && ops

    The method is ``public int Dispatch(string ruleCode, dynamic payload)``.
    """
    target_cc = max(3, int(target_cc))  # need at least if + else + body
    parts: list[str] = [
        HEADER_TEMPLATE.format(
            class_name=class_name,
            namespace=namespace,
            target_cc=target_cc,
        )
    ]

    # Budget: leading `if` (+1) + trailing `else` (+1) + N `else if` (+2 each)
    # + M logical operators (+1 each).
    remaining = target_cc - 2  # leading if + trailing else
    else_if_count = max(0, remaining // 2)
    logical_ops = remaining - (else_if_count * 2)

    # Main dispatcher method header
    parts.append(
        "        public int Dispatch(string ruleCode, dynamic payload)\n"
        "        {\n"
        "            var hits = 0;\n"
    )

    # Leading if
    parts.append(
        f"            if (ruleCode == \"R_000\")\n"
        f"            {{\n"
        f"{_branch_body(0, 'rule')}"
        f"                hits++;\n"
        f"            }}\n"
    )

    # `else if` chain, distributing logical ops randomly across ~1/3 of them
    ops_inserted = 0
    for i in range(1, else_if_count + 1):
        tail = ""
        if ops_inserted < logical_ops and (i % 3 == 0 or rng.random() < 0.2):
            # Choose && or || deterministically-by-RNG
            if rng.random() < 0.7:
                tail = " && payload != null"
            else:
                tail = " || ruleCode == \"R_FALLBACK\""
            ops_inserted += 1
        parts.append(
            f"            else if (ruleCode == \"R_{i:03d}\"{tail})\n"
            f"            {{\n"
            f"{_branch_body(i, 'rule')}"
            f"                hits++;\n"
            f"            }}\n"
        )

    # If we still have unplaced logical ops, append them to a trailing
    # predicate inside the last else-if so the count lands on target.
    # (This handles odd budgets where ops_inserted < logical_ops.)
    while ops_inserted < logical_ops:
        parts.append(
            f"            else if (ruleCode == \"R_EXTRA_{ops_inserted:03d}\" "
            f"|| payload == null)\n"
            f"            {{\n"
            f"                hits++;\n"
            f"            }}\n"
        )
        ops_inserted += 1
        # each extra line adds 2 (else + if) + 1 (||) = 3. Adjust
        # below after the loop if we overshoot.

    parts.append(
        "            else\n"
        "            {\n"
        "                Logger.Warn(\"unhandled rule: \" + ruleCode);\n"
        "            }\n"
        "            return hits;\n"
        "        }\n\n"
    )

    # Stub helper methods referenced by the dispatcher branches. We keep
    # them single-statement so they do not add noise to the complexity
    # score of the file.
    parts.append(
        "        private int ProcessRule000(dynamic payload, string ruleCode) "
        "{ return 0; }\n"
    )
    # Emit a small handful of extra stubs — no need to create one per
    # branch because the dispatcher's `result{index}` is never read.
    for i in range(1, min(20, target_cc)):
        parts.append(
            f"        private int ProcessRule{i:03d}(dynamic payload, string ruleCode) "
            f"{{ return {i}; }}\n"
        )

    parts.append(FOOTER)
    return "".join(parts)


def count_complexity_signal(source: str) -> int:
    """Approximate the complexity the refactor engine will score.

    Mirrors the regex in
    ``backend/app/refactor/csharp_analyzer.py`` so we can assert that
    the generated output actually hits the intended target.
    """
    import re

    return len(
        re.findall(
            r"\b(?:if|else|switch|case|for|foreach|while|do|catch|&&|\|\|)\b",
            source,
        )
    )
