"""Profile data classes for synthetic tenant generation.

A TenantProfile holds the overall parameters for a tenant showcase. Each
AppRecipe describes one synthetic application inside that tenant.

Profiles are loaded from YAML fixtures under ``fixtures/``. They are
deterministic: the same profile + seed always produces the same output.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

import yaml


@dataclass
class VulnerabilityDensity:
    """Per-app vulnerability injection density.

    Values are absolute counts. The generator inserts exactly this many
    instances of each pattern into the generated code so the refactor
    engine's detectors find predictable numbers.
    """

    sql_injection: int = 0
    hardcoded_creds: int = 0
    weak_crypto: int = 0
    command_injection: int = 0
    missing_fk: int = 0
    pii_leak: int = 0
    suppressed_exceptions: int = 0

    def total(self) -> int:
        return (
            self.sql_injection
            + self.hardcoded_creds
            + self.weak_crypto
            + self.command_injection
            + self.missing_fk
            + self.pii_leak
            + self.suppressed_exceptions
        )


@dataclass
class DatabaseSpec:
    """Describes a database this app talks to."""

    engine: str  # sqlserver, mysql, db2, oracle, sqlite, redis
    tables: int = 20
    pii_columns: int = 5


@dataclass
class SubProject:
    """One sub-project inside an app.

    Real enterprise legacy apps are usually bundles of 3-4 sub-projects
    with different stacks (e.g., a Java backend + Python RPA robot +
    TypeScript frontend). The synth generator treats each sub-project
    as a distinct directory with its own language and vulnerability
    share.
    """

    name: str  # e.g., "backend", "rpa-robot", "frontend"
    language: str  # csharp, python, vbnet, java, php, typescript, cobol
    loc_share: float = 1.0  # fraction of parent app's LOC budget (sum across sub-projects should be ~1.0)
    vuln_share: float = 1.0  # fraction of parent app's vulnerability budget
    modules: int = 6  # modules to generate inside this sub-project
    has_rpa: bool = False  # if True, use the RPA-flavoured templates


@dataclass
class RefactorDecision:
    """Pre-assigned migration decision for an app.

    Emitted by the Plan Componer Deuda pattern: classify each app as
    REFACTOR / RETIRE / RETAIN / TBD and the strangler planner should
    honor the classification instead of making its own call.
    """

    action: str = "refactor"  # refactor, retire, retain, tbd
    phase: str = "Q3"  # Q1..Q4, IMMEDIATE, TBD
    rationale: str = ""
    validation_checklist: list[str] = field(default_factory=list)
    blockers: list[str] = field(default_factory=list)

    def to_markdown(self, app_codename: str, app_label: str) -> str:
        checklist = "\n".join(f"- [ ] {item}" for item in self.validation_checklist) or "- (none)"
        blockers = "\n".join(f"- {item}" for item in self.blockers) or "- (none)"
        return (
            f"# Refactor Decision — `{app_codename}`\n\n"
            f"**App:** {app_label}\n"
            f"**Action:** `{self.action.upper()}`\n"
            f"**Phase:** {self.phase}\n\n"
            f"## Rationale\n\n{self.rationale or '(no rationale provided)'}\n\n"
            f"## Validation checklist\n\n{checklist}\n\n"
            f"## Blockers\n\n{blockers}\n\n"
            f"_Auto-generated by synth. The strangler planner reads this file "
            f"and honors the action / phase when present._\n"
        )


@dataclass
class AppRecipe:
    """One synthetic application inside a tenant."""

    codename: str  # e.g., "app-01"
    label: str  # user-facing display, e.g., "Transaction Reconciliation Service"
    loc_target: int  # approximate lines of code
    primary_language: str  # csharp, python, vbnet, java, php, typescript, cobol, cpp
    additional_languages: list[str] = field(default_factory=list)
    databases: list[DatabaseSpec] = field(default_factory=list)
    vulnerabilities: VulnerabilityDensity = field(default_factory=VulnerabilityDensity)
    has_cobol_layer: bool = False
    is_shared_nexus: bool = False  # if True, other apps will import from this
    has_rpa: bool = False  # if True, include Playwright/Selenium fragile selectors
    modules: int = 10  # number of sub-modules to generate (single-project mode)
    sub_projects: list[SubProject] = field(default_factory=list)
    db_inactive_since: str = ""  # ISO date — if set, triggers retirement-path logic
    decision: RefactorDecision | None = None
    inject_legacy_db_schema: bool = False  # if True, generate a SQL dump fixture with 0-FK legacy schema

    @property
    def all_languages(self) -> list[str]:
        seen = [self.primary_language]
        for lang in self.additional_languages:
            if lang not in seen:
                seen.append(lang)
        if self.has_cobol_layer and "cobol" not in seen:
            seen.append("cobol")
        for sub in self.sub_projects:
            if sub.language not in seen:
                seen.append(sub.language)
        return seen

    @property
    def is_multi_project(self) -> bool:
        return bool(self.sub_projects)


@dataclass
class ComplianceCertification:
    """One regulatory certification or audit the tenant must achieve."""

    name: str  # e.g., "SOC 2 Type II"
    framework: str  # e.g., "AICPA Trust Services Criteria"
    due_date: str  # ISO date, e.g., "2026-09-30"
    status: str = "in_progress"  # in_progress / at_risk / blocked / complete
    owner: str = "compliance"  # team that owns this certification
    description: str = ""


@dataclass
class ModernizationPhase:
    """One phase in the modernization roadmap with start/end dates."""

    name: str  # e.g., "Discovery", "Execution", "Testing + UAT"
    start_date: str  # ISO date
    end_date: str  # ISO date
    milestones: list[str] = field(default_factory=list)


@dataclass
class ComplianceProfile:
    """Tenant-wide compliance and deadline metadata.

    Loaded from an optional ``compliance`` block in the tenant YAML
    fixture. Used by the /showcase frontend to render a countdown to
    the hard deadline and a readiness summary for each certification.
    """

    hard_deadline: str = ""  # ISO date — the single go-live commitment
    certifications: list[ComplianceCertification] = field(default_factory=list)
    phases: list[ModernizationPhase] = field(default_factory=list)
    audit_cadence: str = ""  # e.g., "Monthly steering committee, day 14"
    narrative: str = ""  # short stakeholder-facing summary

    def to_dict(self) -> dict:
        return {
            "hard_deadline": self.hard_deadline,
            "certifications": [asdict(c) for c in self.certifications],
            "phases": [asdict(p) for p in self.phases],
            "audit_cadence": self.audit_cadence,
            "narrative": self.narrative,
        }


@dataclass
class VendorDependency:
    """One external vendor the tenant depends on."""

    name: str  # codename only, e.g., "legacy-platform-vendor"
    category: str  # legacy-platform / consulting / cloud / saas / audit
    revenue_share_pct: float = 0.0  # how much of vendor's revenue comes from this tenant
    spend_2y_usd: float = 0.0  # 2-year spend with this vendor in USD
    contract_coverage_pct: float = 100.0  # % of spend under a written contract
    lock_in_level: str = "medium"  # low / medium / high
    notes: str = ""


@dataclass
class PenaltyExposure:
    """Upper-bound penalty scenarios."""

    category: str  # reputational / privacy / integrity / regulatory
    cap_usd: float  # worst-case dollar cap
    driver: str = ""  # short sentence describing the trigger


@dataclass
class CommercialRiskProfile:
    """Tenant-wide commercial risk metadata.

    Captures the non-technical factors that shape phase ordering:
    vendor concentration, contract gaps and penalty exposure. The
    strangler planner reads this profile to bring forward phases whose
    apps carry high commercial risk (e.g., hit the apps whose vendor
    contract is about to expire first).
    """

    vendors: list[VendorDependency] = field(default_factory=list)
    penalty_exposure: list[PenaltyExposure] = field(default_factory=list)
    contract_gap_pct: float = 0.0  # tenant-wide % of spend without contract coverage
    total_exposure_usd: float = 0.0  # sum of penalty caps
    narrative: str = ""

    def to_dict(self) -> dict:
        return {
            "vendors": [asdict(v) for v in self.vendors],
            "penalty_exposure": [asdict(p) for p in self.penalty_exposure],
            "contract_gap_pct": self.contract_gap_pct,
            "total_exposure_usd": self.total_exposure_usd,
            "narrative": self.narrative,
        }


@dataclass
class TenantProfile:
    """Top-level tenant configuration."""

    tenant_id: str  # slug, e.g., "tenant-alpha"
    display_name: str  # e.g., "Alpha Corp"
    seed: int = 42
    apps: list[AppRecipe] = field(default_factory=list)
    description: str = ""
    compliance: ComplianceProfile | None = None
    commercial_risk: CommercialRiskProfile | None = None

    def app_by_codename(self, codename: str) -> AppRecipe | None:
        for app in self.apps:
            if app.codename == codename:
                return app
        return None

    def total_loc(self) -> int:
        return sum(a.loc_target for a in self.apps)

    def total_vulnerabilities(self) -> int:
        return sum(a.vulnerabilities.total() for a in self.apps)


def load_profile(path: str | Path) -> TenantProfile:
    """Load a TenantProfile from a YAML fixture file."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Tenant profile fixture not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        raw: dict[str, Any] = yaml.safe_load(f)

    apps: list[AppRecipe] = []
    for raw_app in raw.get("apps", []):
        dbs = [
            DatabaseSpec(
                engine=d["engine"],
                tables=d.get("tables", 20),
                pii_columns=d.get("pii_columns", 5),
            )
            for d in raw_app.get("databases", [])
        ]
        vuln_raw = raw_app.get("vulnerabilities", {})
        vulns = VulnerabilityDensity(
            sql_injection=vuln_raw.get("sql_injection", 0),
            hardcoded_creds=vuln_raw.get("hardcoded_creds", 0),
            weak_crypto=vuln_raw.get("weak_crypto", 0),
            command_injection=vuln_raw.get("command_injection", 0),
            missing_fk=vuln_raw.get("missing_fk", 0),
            pii_leak=vuln_raw.get("pii_leak", 0),
            suppressed_exceptions=vuln_raw.get("suppressed_exceptions", 0),
        )
        sub_projects = [
            SubProject(
                name=sp["name"],
                language=sp["language"],
                loc_share=sp.get("loc_share", 1.0),
                vuln_share=sp.get("vuln_share", 1.0),
                modules=sp.get("modules", 6),
                has_rpa=sp.get("has_rpa", False),
            )
            for sp in raw_app.get("sub_projects", [])
        ]
        decision_raw = raw_app.get("decision")
        decision = None
        if decision_raw:
            decision = RefactorDecision(
                action=decision_raw.get("action", "refactor"),
                phase=decision_raw.get("phase", "Q3"),
                rationale=decision_raw.get("rationale", ""),
                validation_checklist=decision_raw.get("validation_checklist", []),
                blockers=decision_raw.get("blockers", []),
            )
        apps.append(
            AppRecipe(
                codename=raw_app["codename"],
                label=raw_app["label"],
                loc_target=raw_app.get("loc_target", 50_000),
                primary_language=raw_app["primary_language"],
                additional_languages=raw_app.get("additional_languages", []),
                databases=dbs,
                vulnerabilities=vulns,
                has_cobol_layer=raw_app.get("has_cobol_layer", False),
                is_shared_nexus=raw_app.get("is_shared_nexus", False),
                has_rpa=raw_app.get("has_rpa", False),
                modules=raw_app.get("modules", 10),
                sub_projects=sub_projects,
                db_inactive_since=raw_app.get("db_inactive_since", ""),
                decision=decision,
                inject_legacy_db_schema=raw_app.get("inject_legacy_db_schema", False),
            )
        )

    compliance = None
    raw_compliance = raw.get("compliance")
    if raw_compliance:
        compliance = ComplianceProfile(
            hard_deadline=raw_compliance.get("hard_deadline", ""),
            audit_cadence=raw_compliance.get("audit_cadence", ""),
            narrative=raw_compliance.get("narrative", ""),
            certifications=[
                ComplianceCertification(
                    name=c["name"],
                    framework=c.get("framework", ""),
                    due_date=c.get("due_date", ""),
                    status=c.get("status", "in_progress"),
                    owner=c.get("owner", "compliance"),
                    description=c.get("description", ""),
                )
                for c in raw_compliance.get("certifications", [])
            ],
            phases=[
                ModernizationPhase(
                    name=p["name"],
                    start_date=p.get("start_date", ""),
                    end_date=p.get("end_date", ""),
                    milestones=p.get("milestones", []),
                )
                for p in raw_compliance.get("phases", [])
            ],
        )

    commercial_risk = None
    raw_cr = raw.get("commercial_risk")
    if raw_cr:
        commercial_risk = CommercialRiskProfile(
            contract_gap_pct=raw_cr.get("contract_gap_pct", 0.0),
            total_exposure_usd=raw_cr.get("total_exposure_usd", 0.0),
            narrative=raw_cr.get("narrative", ""),
            vendors=[
                VendorDependency(
                    name=v["name"],
                    category=v.get("category", "saas"),
                    revenue_share_pct=v.get("revenue_share_pct", 0.0),
                    spend_2y_usd=v.get("spend_2y_usd", 0.0),
                    contract_coverage_pct=v.get("contract_coverage_pct", 100.0),
                    lock_in_level=v.get("lock_in_level", "medium"),
                    notes=v.get("notes", ""),
                )
                for v in raw_cr.get("vendors", [])
            ],
            penalty_exposure=[
                PenaltyExposure(
                    category=p["category"],
                    cap_usd=p.get("cap_usd", 0.0),
                    driver=p.get("driver", ""),
                )
                for p in raw_cr.get("penalty_exposure", [])
            ],
        )

    return TenantProfile(
        tenant_id=raw["tenant_id"],
        display_name=raw["display_name"],
        seed=raw.get("seed", 42),
        description=raw.get("description", ""),
        apps=apps,
        compliance=compliance,
        commercial_risk=commercial_risk,
    )
