"""Report Out simulator — single-document stakeholder deliverable.

Real enterprise assessment programs produce a multi-slide "Report Out"
deck summarizing the full modernization picture: totals, per-app
breakdown, proposed actions, commercial risk, governance and
compliance status. This module assembles the equivalent for a
NexusForge tenant as a single Markdown document so it can be pasted
into a ticket, emailed to a sponsor or embedded in the /showcase
dashboard.

All inputs are JSON payloads from the existing showcase data layer:
showcase report, strangler plans, compliance, commercial risk and
governance. The output is a deterministic, sanitized Markdown string
— no real client data, only the structural facts carried in the
tenant profile.

Usage (programmatic):

    from app.showcase import report_out
    md = report_out.render_from_fixtures(
        tenant_id="tenant-alpha",
        data_dir=Path("backend/showcase_data"),
    )

Usage (CLI):

    python -m app.showcase.report_out --tenant tenant-alpha
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


def _load_json(path: Path) -> dict | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def render_from_fixtures(
    tenant_id: str,
    data_dir: Path,
) -> str:
    """Assemble a Report Out markdown document from static fixtures.

    Reads the following files under ``<data_dir>/<tenant_id>/``:
    - showcase_report.json  (required)
    - compliance.json       (optional)
    - commercial_risk.json  (optional)
    - governance.json       (optional)
    - strangler_plans/*.json (optional, one per app)

    Raises FileNotFoundError if the required showcase_report.json is
    missing.
    """
    tenant_dir = data_dir / tenant_id
    report_path = tenant_dir / "showcase_report.json"
    if not report_path.exists():
        raise FileNotFoundError(
            f"Showcase report not found at {report_path}. "
            f"Run the synth generator and showcase_run.py first."
        )
    report = json.loads(report_path.read_text(encoding="utf-8"))
    compliance = _load_json(tenant_dir / "compliance.json")
    commercial_risk = _load_json(tenant_dir / "commercial_risk.json")
    governance = _load_json(tenant_dir / "governance.json")

    strangler_plans: dict[str, dict] = {}
    plans_dir = tenant_dir / "strangler_plans"
    if plans_dir.is_dir():
        for plan_file in sorted(plans_dir.glob("*.json")):
            strangler_plans[plan_file.stem] = json.loads(
                plan_file.read_text(encoding="utf-8")
            )

    return render(
        tenant_id=tenant_id,
        report=report,
        compliance=compliance,
        commercial_risk=commercial_risk,
        governance=governance,
        strangler_plans=strangler_plans,
    )


def render(
    tenant_id: str,
    report: dict,
    compliance: dict | None = None,
    commercial_risk: dict | None = None,
    governance: dict | None = None,
    strangler_plans: dict[str, dict] | None = None,
) -> str:
    """Render the Report Out markdown from already-loaded payloads.

    This is the pure-function entry point — callers can pass data from
    any source (static fixtures, DB rows, live pipeline output).
    """
    strangler_plans = strangler_plans or {}
    parts: list[str] = []
    parts.append(_section_header(tenant_id, report))
    parts.append(_section_executive_summary(report, compliance, commercial_risk))
    parts.append(_section_app_breakdown(report, strangler_plans))
    parts.append(_section_strangler_summary(strangler_plans))
    if commercial_risk:
        parts.append(_section_commercial_risk(commercial_risk))
    if governance:
        parts.append(_section_governance(governance))
    if compliance:
        parts.append(_section_compliance(compliance))
    parts.append(_section_next_30_days(compliance, strangler_plans))
    parts.append(_section_footer())
    return "\n\n".join(parts).strip() + "\n"


# ── Section renderers ──────────────────────────────────────────────────────


def _section_header(tenant_id: str, report: dict) -> str:
    totals = report.get("totals", {})
    generated_at = report.get("generated_at", "")
    lines = [
        f"# Report Out — `{tenant_id}`",
        "",
        f"_Auto-generated by NexusForge synth. Not real client data._",
        "",
        f"- **Generated:** {generated_at}",
        f"- **Apps in scope:** {totals.get('apps', 0)}",
        f"- **Files:** {totals.get('files', 0):,}",
        f"- **Lines of code:** {totals.get('lines_of_code', 0):,}",
        f"- **Findings:** **{totals.get('findings', 0):,}**",
        f"- **Weighted risk score:** {totals.get('risk_score', 0):,}",
        f"- **Pipeline duration:** {report.get('duration_ms', 0)} ms",
    ]
    return "\n".join(lines)


def _section_executive_summary(
    report: dict,
    compliance: dict | None,
    commercial_risk: dict | None,
) -> str:
    totals = report.get("totals", {})
    by_sev = totals.get("findings_by_severity", {}) or {}
    critical = by_sev.get("critical", 0)
    high = by_sev.get("high", 0)

    pieces: list[str] = ["## 1. Executive summary", ""]
    pieces.append(
        f"NexusForge ingested **{totals.get('files', 0):,} files** across "
        f"**{totals.get('apps', 0)} applications** "
        f"(**{totals.get('lines_of_code', 0):,} lines of code**), detected "
        f"**{totals.get('findings', 0):,} total findings** "
        f"(**{critical:,} critical**, **{high:,} high**), and produced a "
        f"phased migration plan in under "
        f"{max(1, report.get('duration_ms', 0) / 1000):.1f} seconds. Manual "
        f"discovery at the same scale typically runs for months."
    )
    if compliance and compliance.get("hard_deadline"):
        pieces.append("")
        pieces.append(
            f"**Hard deadline:** {compliance.get('hard_deadline')} — "
            f"{len(compliance.get('certifications', []))} certifications in "
            f"scope."
        )
    if commercial_risk:
        pieces.append("")
        exposure = commercial_risk.get("total_exposure_usd", 0)
        gap = commercial_risk.get("contract_gap_pct", 0)
        pieces.append(
            f"**Commercial exposure:** worst-case ${exposure:,.0f} USD "
            f"across {len(commercial_risk.get('penalty_exposure', []))} "
            f"penalty categories; {gap:.0f}% of vendor spend currently "
            f"outside written contract coverage."
        )
    return "\n".join(pieces)


def _section_app_breakdown(
    report: dict,
    strangler_plans: dict[str, dict],
) -> str:
    apps = report.get("apps", []) or []
    lines = [
        "## 2. Per-app breakdown",
        "",
        "| App | Label | Files | LOC | Findings | Critical | Risk | Decision | Effort |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for app in apps:
        codename = app.get("codename", "?")
        label = app.get("label", codename)
        files = app.get("total_files", 0)
        loc = app.get("total_lines", 0)
        findings = (app.get("findings") or {}).get("total", 0)
        critical = (app.get("findings") or {}).get("by_severity", {}).get("critical", 0)
        risk = app.get("risk_score", 0)
        decision = (app.get("decision") or {}).get("action", "—").upper()
        phase = (app.get("decision") or {}).get("phase", "")
        decision_cell = f"{decision}{f' / {phase}' if phase else ''}" if decision != "—" else "—"
        plan = strangler_plans.get(codename, {})
        effort = plan.get("total_effort_days", app.get("total_effort_days", 0))
        lines.append(
            f"| `{codename}` | {label} | {files} | {loc:,} | {findings:,} "
            f"| {critical:,} | {risk:,} | {decision_cell} | {effort}d |"
        )

    # Pull out any apps with a db_inactive_since marker
    inactive = [a for a in apps if a.get("db_inactive_since")]
    if inactive:
        lines.append("")
        lines.append("**Retirement candidates (inactive databases):**")
        lines.append("")
        for a in inactive:
            lines.append(
                f"- `{a.get('codename')}` — database inactive since "
                f"{a.get('db_inactive_since')}. Requires dual validation "
                f"(technical exploit reachability + business ownership "
                f"confirmation) before decommission."
            )
    return "\n".join(lines)


def _section_strangler_summary(strangler_plans: dict[str, dict]) -> str:
    if not strangler_plans:
        return "## 3. Strangler migration plan\n\n_No plans available._"
    lines = [
        "## 3. Strangler migration plan",
        "",
        "| App | Phases | Modules | Effort (days) | Narrative |",
        "|---|---|---|---|---|",
    ]
    total_effort = 0
    total_phases = 0
    for codename in sorted(strangler_plans.keys()):
        plan = strangler_plans[codename]
        phases = plan.get("phases", [])
        effort = plan.get("total_effort_days", 0)
        modules = plan.get("total_modules", 0)
        narrative = plan.get("narrative", "").split(".")[0] + "."
        narrative = narrative.replace("|", "\\|")[:150]
        lines.append(
            f"| `{codename}` | {len(phases)} | {modules} | {effort} | {narrative} |"
        )
        total_effort += effort
        total_phases += len(phases)
    lines.append(f"| **total** | **{total_phases}** | — | **{total_effort}** | — |")
    if total_effort > 0:
        weeks_solo = max(1, total_effort // 5)
        weeks_team4 = max(1, total_effort // 20)
        lines.append("")
        lines.append(
            f"Total estimated effort: **{total_effort} engineer-days** "
            f"(~{weeks_solo} weeks for a single engineer, ~{weeks_team4} "
            f"weeks for a 4-engineer team working in parallel)."
        )
    return "\n".join(lines)


def _section_commercial_risk(commercial_risk: dict) -> str:
    lines = [
        "## 4. Commercial risk",
        "",
        commercial_risk.get("narrative", "").strip(),
        "",
    ]
    vendors = commercial_risk.get("vendors", [])
    if vendors:
        lines.append("### Vendor dependencies")
        lines.append("")
        lines.append("| Vendor | Category | Lock-in | Revenue share | 2y spend | Contract coverage |")
        lines.append("|---|---|---|---|---|---|")
        for v in vendors:
            lines.append(
                f"| `{v.get('name', '?')}` | {v.get('category', '')} "
                f"| {v.get('lock_in_level', '')} "
                f"| {v.get('revenue_share_pct', 0):.1f}% "
                f"| ${v.get('spend_2y_usd', 0):,.0f} "
                f"| {v.get('contract_coverage_pct', 0):.0f}% |"
            )
    penalties = commercial_risk.get("penalty_exposure", [])
    if penalties:
        lines.append("")
        lines.append("### Penalty exposure")
        lines.append("")
        for p in penalties:
            lines.append(
                f"- **{p.get('category', '?').title()}**: up to "
                f"${p.get('cap_usd', 0):,.0f} — {p.get('driver', '')}"
            )
    lines.append("")
    lines.append(
        f"**Tenant-wide contract gap:** "
        f"{commercial_risk.get('contract_gap_pct', 0):.0f}% of vendor spend "
        f"without written contract coverage. **Total exposure (sum of "
        f"penalty caps):** ${commercial_risk.get('total_exposure_usd', 0):,.0f}."
    )
    return "\n".join(lines)


def _section_governance(governance: dict) -> str:
    lines = [
        "## 5. Governance",
        "",
        governance.get("narrative", "").strip(),
        "",
    ]
    steering = governance.get("steering")
    if steering:
        lines.append("### Steering committee")
        lines.append("")
        lines.append(f"- **Cadence:** {steering.get('cadence', '')}")
        lines.append(f"- **Chair:** {steering.get('owner_role', '')}")
        lines.append(f"- **First formal review:** {steering.get('first_formal_review', '')}")
        attendees = steering.get("attendees", [])
        if attendees:
            lines.append(f"- **Attendees:** {', '.join(attendees)}")
    teams = governance.get("teams", [])
    if teams:
        lines.append("")
        lines.append("### Delivery teams")
        lines.append("")
        lines.append("| Team | Role | Headcount | Status | App scope |")
        lines.append("|---|---|---|---|---|")
        for t in teams:
            scope = ", ".join(f"`{a}`" for a in t.get("app_scope", [])) or "_(out of scope apps)_"
            lines.append(
                f"| `{t.get('name', '?')}` | {t.get('role', '')} "
                f"| {t.get('headcount', 0)} | {t.get('status', '')} | {scope} |"
            )
    code_access = governance.get("code_access")
    if code_access:
        lines.append("")
        lines.append("### Code access gate")
        lines.append("")
        bottleneck = " **(known delivery bottleneck)**" if code_access.get("bottleneck") else ""
        lines.append(
            f"- **Model:** `{code_access.get('model', '')}`{bottleneck}"
        )
        lines.append(f"- **Owner:** {code_access.get('owner_role', '')}")
        if code_access.get("notes"):
            lines.append(f"- **Notes:** {code_access.get('notes').strip()}")
    tech_lead = governance.get("tech_lead")
    if tech_lead:
        lines.append("")
        lines.append("### Post-launch tech lead")
        lines.append("")
        lines.append(f"- **Status:** `{tech_lead.get('status', '')}`")
        if tech_lead.get("target_start_date"):
            lines.append(f"- **Target start date:** {tech_lead.get('target_start_date')}")
        if tech_lead.get("scope"):
            lines.append(f"- **Scope:** {tech_lead.get('scope').strip()}")
    return "\n".join(lines)


def _section_compliance(compliance: dict) -> str:
    lines = [
        "## 6. Compliance countdown",
        "",
        compliance.get("narrative", "").strip(),
        "",
        f"**Hard deadline:** {compliance.get('hard_deadline', '')}",
        f"**Audit cadence:** {compliance.get('audit_cadence', '')}",
        "",
    ]
    certs = compliance.get("certifications", [])
    if certs:
        lines.append("### Certifications in scope")
        lines.append("")
        lines.append("| Name | Framework | Due | Status | Owner |")
        lines.append("|---|---|---|---|---|")
        for c in certs:
            lines.append(
                f"| {c.get('name', '?')} | {c.get('framework', '')} "
                f"| {c.get('due_date', '')} | `{c.get('status', '')}` "
                f"| {c.get('owner', '')} |"
            )
    phases = compliance.get("phases", [])
    if phases:
        lines.append("")
        lines.append("### Program phases")
        lines.append("")
        for p in phases:
            lines.append(
                f"- **{p.get('name', '')}** "
                f"({p.get('start_date', '')} → {p.get('end_date', '')})"
            )
            for m in p.get("milestones", []):
                lines.append(f"  - {m}")
    return "\n".join(lines)


def _section_next_30_days(
    compliance: dict | None,
    strangler_plans: dict[str, dict],
) -> str:
    """Best-effort "next 30 days" actionable list.

    Picks the earliest currently-open phase from compliance (if any)
    and the first phase of each strangler plan that has an effort
    estimate > 0. Deterministic — no date-based cutoffs.
    """
    lines = ["## 7. Next 30 days — actionable milestones", ""]
    added_anything = False

    if compliance:
        phases = compliance.get("phases", []) or []
        if phases:
            lines.append(f"### Compliance milestones (next phase)")
            lines.append("")
            next_phase = phases[0]
            lines.append(
                f"- **{next_phase.get('name', '')}** "
                f"({next_phase.get('start_date', '')} → "
                f"{next_phase.get('end_date', '')})"
            )
            for m in next_phase.get("milestones", []):
                lines.append(f"  - [ ] {m}")
            added_anything = True

    if strangler_plans:
        lines.append("")
        lines.append("### Strangler phase-1 entry points")
        lines.append("")
        for codename in sorted(strangler_plans.keys()):
            plan = strangler_plans[codename]
            phases = plan.get("phases", [])
            if not phases:
                continue
            first = phases[0]
            lines.append(
                f"- `{codename}`: **{first.get('title', '')}** "
                f"(risk {first.get('risk', '')}, "
                f"~{first.get('effort_days', 0)} days)"
            )
            added_anything = True

    if not added_anything:
        lines.append("_No actionable milestones available from the current fixtures._")

    return "\n".join(lines)


def _section_footer() -> str:
    return (
        "---\n\n"
        "_This Report Out was assembled automatically from the NexusForge "
        "showcase fixtures. All names are generic codenames; no real "
        "client data is included. For the live version, fetch "
        "`/api/refactor/showcase/<tenant>/report-out`._"
    )


# ── CLI ────────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--tenant",
        default="tenant-alpha",
        help="Tenant slug (matches directory under showcase_data/)",
    )
    parser.add_argument(
        "--data-dir",
        default="backend/showcase_data",
        help="Root directory containing showcase fixtures",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Optional file path to write the markdown to. Default: stdout.",
    )
    args = parser.parse_args()

    try:
        md = render_from_fixtures(
            tenant_id=args.tenant,
            data_dir=Path(args.data_dir).expanduser().resolve(),
        )
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.output:
        out_path = Path(args.output).expanduser().resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(md, encoding="utf-8")
        print(f"Report Out written to {out_path}")
    else:
        print(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
