"""Auto-register all agents on import."""

from app.agents import (  # noqa: F401
    classifier,
    extractor,
    summarizer,
    analyzer,
    enricher,
    validator,
    reporter,
    repair,
    normalizer,
    researcher,
    translator,
    compliance,
    monitor,
    router,
    critic,
    planner,
    knowledge,
    scraper,
    ocr,
    sentiment,
    scheduler,
    webhook,
    judge,
)
