export const NEXUSFORGE_KB = {
  overview: {
    question_patterns: ['what is nexusforge', 'about', 'overview', 'que es', 'descripcion', 'introduce', 'tell me about nexusforge'],
    answer_en: 'NexusForge AI is an enterprise agent orchestration platform with 22 specialized AI agents, 6 swarm topologies, 3-tier memory system, self-healing capabilities, RAG pipeline, and real-time monitoring.\n\nIt enables organizations to build complex AI workflows by combining agents into swarms, with automatic error recovery and observability built-in.',
    answer_es: 'NexusForge AI es una plataforma de orquestación de agentes empresarial con 22 agentes IA especializados, 6 topologías de enjambre, sistema de memoria de 3 niveles, auto-reparación, pipeline RAG y monitoreo en tiempo real.\n\nPermite a las organizaciones construir flujos de trabajo complejos combinando agentes en enjambres, con recuperación automática de errores y observabilidad integrada.'
  },
  agents: {
    question_patterns: ['agents', 'agentes', 'how many agents', 'cuantos agentes', 'agent types', 'tipos de agentes', 'show agents', 'list agents'],
    answer_en: 'NexusForge has **22 specialized agents**:\n\n**Data Processing:** Classifier, Extractor, Normalizer, Validator\n**Analysis:** Analyzer, Summarizer, Sentiment, Researcher\n**Intelligence:** Planner, Router, Critic, Knowledge\n**Operations:** Monitor, Repair, Scheduler, Webhook\n**Content:** Reporter, Translator, OCR, Scraper\n**Quality:** Enricher, Compliance\n\nEach agent uses the multi-provider LLM router (Groq → Claude) with circuit breaker and has demo fallback mode.',
    answer_es: 'NexusForge tiene **22 agentes especializados**:\n\n**Procesamiento de Datos:** Clasificador, Extractor, Normalizador, Validador\n**Análisis:** Analizador, Resumidor, Sentimiento, Investigador\n**Inteligencia:** Planificador, Router, Crítico, Conocimiento\n**Operaciones:** Monitor, Reparación, Programador, Webhook\n**Contenido:** Reportero, Traductor, OCR, Scraper\n**Calidad:** Enriquecedor, Cumplimiento\n\nCada agente usa el router LLM multi-proveedor (Groq → Claude) con circuit breaker y modo demo de respaldo.'
  },
  swarms: {
    question_patterns: ['swarm', 'topology', 'topologies', 'enjambre', 'topologia', 'explain swarms'],
    answer_en: 'NexusForge supports **6 swarm topologies**:\n\n1. **Sequential:** A→B→C chain processing\n2. **Parallel:** Fan-out/fan-in concurrent execution\n3. **Hierarchical:** Planner→Workers→Synthesize\n4. **Debate:** Agent + Critic iterate until quality threshold\n5. **Consensus:** N agents vote, Judge picks best result\n6. **Adaptive:** Router selects best topology dynamically based on task complexity\n\nEach topology supports checkpointing, retry policies, and real-time status updates via WebSocket.',
    answer_es: 'NexusForge soporta **6 topologías de enjambre**:\n\n1. **Secuencial:** Cadena A→B→C\n2. **Paralelo:** Fan-out/fan-in ejecución concurrente\n3. **Jerárquico:** Planificador→Trabajadores→Síntesis\n4. **Debate:** Agente + Crítico iteran hasta umbral de calidad\n5. **Consenso:** N agentes votan, Juez elige el mejor resultado\n6. **Adaptivo:** Router selecciona la mejor topología dinámicamente\n\nCada topología soporta checkpointing, políticas de reintento y actualizaciones en tiempo real via WebSocket.'
  },
  memory: {
    question_patterns: ['memory', 'memoria', 'remember', 'context', 'tier', 'how do agents learn', 'semantic memory'],
    answer_en: '**3-tier memory system:**\n\n• **Working Memory** (in-process): Current task context, last 20 messages\n• **Episodic Memory** (Redis, 30-day TTL): Task summaries, success/failure patterns\n• **Semantic Memory** (pgvector, permanent): Embedded knowledge vectors, cross-agent sharing\n\nAgents learn from past executions through episodic memory, and share knowledge through semantic memory vectors indexed in pgvector.',
    answer_es: '**Sistema de memoria de 3 niveles:**\n\n• **Memoria de Trabajo** (en proceso): Contexto de tarea actual, últimos 20 mensajes\n• **Memoria Episódica** (Redis, TTL 30 días): Resúmenes de tareas, patrones de éxito/fallo\n• **Memoria Semántica** (pgvector, permanente): Vectores de conocimiento, compartidos entre agentes'
  },
  healing: {
    question_patterns: ['heal', 'self-healing', 'repair', 'recovery', 'auto-reparacion', 'error handling', 'how does self-healing work'],
    answer_en: '**Self-healing engine** with 5 strategies:\n\n1. **Retry:** Same step, different config (exponential backoff)\n2. **Skip:** Default output, continue pipeline\n3. **Repair:** RepairAgent diagnoses and fixes the step\n4. **Escalate:** Human review queue for manual intervention\n5. **Fallback:** Use cached result from previous successful run\n\nThe **FailureDetector** classifies errors (network, timeout, data_quality, LLM, schema) and selects the optimal recovery strategy automatically.',
    answer_es: '**Motor de auto-reparación** con 5 estrategias:\n\n1. **Reintento:** Mismo paso, configuración diferente (backoff exponencial)\n2. **Omitir:** Salida por defecto, continuar pipeline\n3. **Reparar:** RepairAgent diagnostica y corrige el paso\n4. **Escalar:** Cola de revisión humana\n5. **Respaldo:** Usar resultado en caché de ejecución exitosa anterior\n\nEl **FailureDetector** clasifica errores y selecciona la estrategia óptima automáticamente.'
  },
  architecture: {
    question_patterns: ['architecture', 'tech stack', 'tecnologia', 'stack', 'how built', 'what technology', 'que tecnologias'],
    answer_en: '**NexusForge Architecture:**\n\n• **Backend:** Python FastAPI + asyncio\n• **Frontend:** React 18 + Vite\n• **Database:** PostgreSQL + pgvector\n• **Cache/Queue:** Redis (Streams + pub/sub)\n• **LLM:** Groq (primary) + Claude (fallback) with circuit breaker\n• **Embeddings:** Voyage AI (512d vectors)\n• **Infrastructure:** Docker Compose, Terraform (AWS), Kubernetes\n• **Observability:** Prometheus + Grafana + Loki + AlertManager\n• **Tests:** 231 pytest tests\n• **SDK:** @nexusforge/sdk (TypeScript)\n• **CLI:** nxf (13 commands)',
    answer_es: '**Arquitectura de NexusForge:**\n\n• **Backend:** Python FastAPI + asyncio\n• **Frontend:** React 18 + Vite\n• **Base de datos:** PostgreSQL + pgvector\n• **Cache/Cola:** Redis (Streams + pub/sub)\n• **LLM:** Groq (primario) + Claude (respaldo) con circuit breaker\n• **Embeddings:** Voyage AI (vectores 512d)\n• **Infraestructura:** Docker Compose, Terraform (AWS), Kubernetes\n• **Observabilidad:** Prometheus + Grafana + Loki + AlertManager\n• **Tests:** 231 tests con pytest\n• **SDK:** @nexusforge/sdk (TypeScript)\n• **CLI:** nxf (13 comandos)'
  },
  dag: {
    question_patterns: ['dag', 'workflow engine', 'pipeline engine', 'execution engine', 'kahn'],
    answer_en: 'The **DAG engine** uses Kahn\'s algorithm for topological sorting. It supports:\n\n• Parallel step execution (asyncio.gather)\n• Step-level checkpointing for crash recovery\n• Retry with exponential backoff + jitter\n• Dead letter queue for failed steps\n• Real-time status via Redis pub/sub → WebSocket\n\nWorkflows are defined as directed acyclic graphs where each node is an agent step with configurable inputs and outputs.',
    answer_es: 'El **motor DAG** usa el algoritmo de Kahn para ordenamiento topológico. Soporta:\n\n• Ejecución paralela de pasos (asyncio.gather)\n• Checkpointing por paso para recuperación de fallos\n• Reintento con backoff exponencial + jitter\n• Cola de mensajes muertos para pasos fallidos\n• Estado en tiempo real via Redis pub/sub → WebSocket'
  },
  rag: {
    question_patterns: ['rag', 'search', 'vector', 'embedding', 'busqueda', 'documento', 'document search', 'what is rag'],
    answer_en: '**RAG pipeline** (Retrieval-Augmented Generation):\n\n1. **Upload:** Document → chunk (500 chars, 50 overlap)\n2. **Embed:** Voyage AI voyage-3-lite (512d vectors)\n3. **Store:** pgvector in PostgreSQL\n4. **Search:** Cosine similarity via match_chunks RPC\n5. **Retrieve:** Top-K results with context building\n\nSupports semantic search across all indexed documents, enabling agents to ground their responses in your organization\'s knowledge base.',
    answer_es: '**Pipeline RAG** (Generación Aumentada por Recuperación):\n\n1. **Subir:** Documento → fragmentos (500 chars, 50 solapamiento)\n2. **Embeber:** Voyage AI voyage-3-lite (vectores 512d)\n3. **Almacenar:** pgvector en PostgreSQL\n4. **Buscar:** Similitud coseno via match_chunks RPC\n5. **Recuperar:** Top-K resultados con construcción de contexto'
  },
  plugins: {
    question_patterns: ['plugin', 'extension', 'marketplace', 'extensiones'],
    answer_en: '**Plugin system** with NexusPlugin interface:\n\n• Dynamic loading via importlib\n• Plugins register agents + connectors\n• 2 example plugins: **gov-data-mx** (Mexico government data), **gov-data-us** (US government data)\n• Plugin manifest with version, description, author\n\nPlugins can extend NexusForge with custom agents, data connectors, and processing pipelines.',
    answer_es: '**Sistema de plugins** con interfaz NexusPlugin:\n\n• Carga dinámica via importlib\n• Los plugins registran agentes + conectores\n• 2 plugins de ejemplo: **gov-data-mx** (datos gobierno México), **gov-data-us** (datos gobierno EEUU)\n• Manifiesto de plugin con versión, descripción, autor'
  },
  cost: {
    question_patterns: ['cost', 'price', 'token', 'costo', 'precio', 'how much', 'pricing'],
    answer_en: '**Cost tracking** per request:\n\n• **Groq (Llama 3.3 70B):** $0.59/M input, $0.79/M output\n• **Claude Sonnet:** $3/M input, $15/M output\n\nThe router tries **Groq first** (40x cheaper), falls back to Claude only when needed. Circuit breaker prevents cascading failures and unnecessary spend.',
    answer_es: '**Seguimiento de costos** por solicitud:\n\n• **Groq (Llama 3.3 70B):** $0.59/M entrada, $0.79/M salida\n• **Claude Sonnet:** $3/M entrada, $15/M salida\n\nEl router intenta **Groq primero** (40x más barato), y usa Claude solo cuando es necesario.'
  },
  cli: {
    question_patterns: ['cli', 'command line', 'terminal', 'nxf', 'commands', 'comandos'],
    answer_en: '**NexusForge CLI** (`nxf`) — 13 commands:\n\n• `nxf init` — Initialize a new project\n• `nxf agent list` — List all agents\n• `nxf agent run <name>` — Run a specific agent\n• `nxf workflow create` — Create a workflow\n• `nxf workflow run <id>` — Execute a workflow\n• `nxf workflow status <id>` — Check execution status\n• `nxf swarm launch` — Launch a swarm topology\n• `nxf doc upload <file>` — Upload document to RAG\n• `nxf doc search <query>` — Semantic search\n• `nxf plugin install <name>` — Install a plugin\n• `nxf config set <key> <val>` — Update configuration\n• `nxf logs <run_id>` — View execution logs\n• `nxf health` — System health check',
    answer_es: '**CLI de NexusForge** (`nxf`) — 13 comandos:\n\n• `nxf init` — Inicializar un nuevo proyecto\n• `nxf agent list` — Listar todos los agentes\n• `nxf agent run <nombre>` — Ejecutar un agente específico\n• `nxf workflow create` — Crear un workflow\n• `nxf workflow run <id>` — Ejecutar un workflow\n• `nxf workflow status <id>` — Ver estado de ejecución\n• `nxf swarm launch` — Lanzar una topología de enjambre\n• `nxf doc upload <archivo>` — Subir documento al RAG\n• `nxf doc search <consulta>` — Búsqueda semántica\n• `nxf plugin install <nombre>` — Instalar un plugin\n• `nxf config set <clave> <valor>` — Actualizar configuración\n• `nxf logs <run_id>` — Ver logs de ejecución\n• `nxf health` — Verificación de salud del sistema'
  },
  sdk: {
    question_patterns: ['sdk', 'typescript sdk', 'javascript sdk', 'client library', 'npm package', 'libreria'],
    answer_en: '**@nexusforge/sdk** — TypeScript SDK:\n\n• Full type-safe client for all API endpoints\n• Agent execution with streaming support\n• Workflow builder with fluent API\n• WebSocket integration for real-time updates\n• Automatic retry and error handling\n• Works in Node.js and browser environments\n\nInstall: `npm install @nexusforge/sdk`',
    answer_es: '**@nexusforge/sdk** — SDK de TypeScript:\n\n• Cliente type-safe para todos los endpoints\n• Ejecución de agentes con soporte de streaming\n• Constructor de workflows con API fluida\n• Integración WebSocket para actualizaciones en tiempo real\n• Reintento automático y manejo de errores\n• Funciona en Node.js y navegador\n\nInstalar: `npm install @nexusforge/sdk`'
  },
  testing: {
    question_patterns: ['test', 'testing', 'pytest', 'pruebas', 'quality', 'coverage'],
    answer_en: '**Testing strategy:**\n\n• **231 pytest tests** covering all modules\n• **Unit tests:** Agent logic, DAG engine, memory tiers\n• **Integration tests:** API endpoints, WebSocket, Redis pub/sub\n• **E2E tests:** Full workflow execution, swarm topologies\n• **Fixtures:** Mock LLM responses for deterministic testing\n• **CI/CD:** GitHub Actions runs full suite on every PR\n\nRun tests: `pytest --cov=nexusforge tests/`',
    answer_es: '**Estrategia de testing:**\n\n• **231 tests con pytest** cubriendo todos los módulos\n• **Tests unitarios:** Lógica de agentes, motor DAG, niveles de memoria\n• **Tests de integración:** Endpoints API, WebSocket, Redis pub/sub\n• **Tests E2E:** Ejecución completa de workflows, topologías de enjambre\n• **Fixtures:** Respuestas LLM simuladas para testing determinista\n• **CI/CD:** GitHub Actions ejecuta toda la suite en cada PR'
  },
  deployment: {
    question_patterns: ['deploy', 'deployment', 'docker', 'kubernetes', 'k8s', 'aws', 'cloud', 'despliegue', 'produccion'],
    answer_en: '**Deployment options:**\n\n• **Docker Compose:** Single-command local deployment\n  `docker compose up -d`\n• **Kubernetes:** Helm chart with auto-scaling\n  - HPA for API pods (CPU/memory based)\n  - Separate worker pool for agent execution\n• **Terraform (AWS):** Full IaC provisioning\n  - EKS cluster + RDS (PostgreSQL) + ElastiCache (Redis)\n  - ALB + Route53 + ACM for HTTPS\n• **Monitoring:** Prometheus + Grafana dashboards pre-configured\n\nAll environments use the same Docker images for consistency.',
    answer_es: '**Opciones de despliegue:**\n\n• **Docker Compose:** Despliegue local con un solo comando\n• **Kubernetes:** Chart Helm con auto-escalado\n• **Terraform (AWS):** Provisión completa de infraestructura\n  - EKS + RDS (PostgreSQL) + ElastiCache (Redis)\n• **Monitoreo:** Dashboards Prometheus + Grafana pre-configurados'
  },
  security: {
    question_patterns: ['security', 'seguridad', 'auth', 'authentication', 'authorization', 'jwt', 'rbac', 'permissions'],
    answer_en: '**Security features:**\n\n• **Authentication:** JWT tokens with refresh rotation\n• **Authorization:** Role-based access control (RBAC)\n  - Admin, Operator, Viewer roles\n  - Per-workflow and per-agent permissions\n• **API Security:** Rate limiting, CORS, input validation\n• **Data:** Encryption at rest (AES-256), in transit (TLS 1.3)\n• **Secrets:** Environment variables + Kubernetes Secrets\n• **Audit:** Full audit log of all agent executions and admin actions\n• **LLM Safety:** Prompt injection detection, output sanitization',
    answer_es: '**Características de seguridad:**\n\n• **Autenticación:** Tokens JWT con rotación de refresh\n• **Autorización:** Control de acceso basado en roles (RBAC)\n• **Seguridad API:** Rate limiting, CORS, validación de entrada\n• **Datos:** Cifrado en reposo (AES-256), en tránsito (TLS 1.3)\n• **Secretos:** Variables de entorno + Kubernetes Secrets\n• **Auditoría:** Log completo de todas las ejecuciones'
  },
  comparison: {
    question_patterns: ['compare', 'comparison', 'vs', 'langchain', 'crewai', 'n8n', 'autogen', 'alternative', 'diferencia', 'comparar'],
    answer_en: '**NexusForge vs alternatives:**\n\n**vs LangChain:** NexusForge is a full platform (not just a library). Includes orchestration, memory, healing, monitoring, and UI out of the box.\n\n**vs CrewAI:** NexusForge offers 6 swarm topologies (CrewAI has 2), 3-tier memory (vs single), self-healing, and enterprise features.\n\n**vs n8n/Zapier:** NexusForge is AI-native. Agents reason and adapt, not just route data. Supports complex multi-agent collaboration.\n\n**vs AutoGen:** NexusForge adds production infrastructure: monitoring, cost tracking, plugin system, and Kubernetes-ready deployment.\n\n**Key differentiators:** Self-healing, 22 specialized agents, adaptive topology, enterprise-grade observability.',
    answer_es: '**NexusForge vs alternativas:**\n\n**vs LangChain:** NexusForge es una plataforma completa, no solo una librería. Incluye orquestación, memoria, auto-reparación y UI.\n\n**vs CrewAI:** NexusForge ofrece 6 topologías (CrewAI tiene 2), memoria de 3 niveles, auto-reparación y funciones enterprise.\n\n**vs n8n/Zapier:** NexusForge es AI-nativo. Los agentes razonan y se adaptan.\n\n**vs AutoGen:** NexusForge agrega infraestructura de producción: monitoreo, costos, plugins y despliegue Kubernetes.'
  },
  help: {
    question_patterns: ['help', 'ayuda', 'what can you do', 'que puedes hacer', 'commands', 'options'],
    answer_en: 'I can help you with everything about **NexusForge AI**! Ask me about:\n\n• **Agents** — 22 specialized AI agents\n• **Swarms** — 6 topology patterns\n• **Memory** — 3-tier memory system\n• **Self-healing** — Automatic error recovery\n• **Architecture** — Tech stack & infrastructure\n• **RAG** — Document search pipeline\n• **DAG Engine** — Workflow execution\n• **CLI** — 13 terminal commands\n• **SDK** — TypeScript client library\n• **Testing** — 231 pytest tests\n• **Deployment** — Docker, K8s, AWS\n• **Security** — Auth, RBAC, encryption\n• **Plugins** — Extension system\n• **Cost** — LLM pricing & optimization\n• **Comparisons** — vs LangChain, CrewAI, n8n',
    answer_es: '¡Puedo ayudarte con todo sobre **NexusForge AI**! Pregúntame sobre:\n\n• **Agentes** — 22 agentes IA especializados\n• **Enjambres** — 6 patrones de topología\n• **Memoria** — Sistema de 3 niveles\n• **Auto-reparación** — Recuperación automática de errores\n• **Arquitectura** — Stack tecnológico\n• **RAG** — Pipeline de búsqueda en documentos\n• **Motor DAG** — Ejecución de workflows\n• **CLI** — 13 comandos de terminal\n• **SDK** — Librería cliente TypeScript\n• **Testing** — 231 tests con pytest\n• **Despliegue** — Docker, K8s, AWS\n• **Seguridad** — Auth, RBAC, cifrado\n• **Plugins** — Sistema de extensiones\n• **Costos** — Precios y optimización LLM\n• **Comparaciones** — vs LangChain, CrewAI, n8n'
  },
}
